# Claude Power Pack — Installation Script (Windows PowerShell)
# Generates USER_CRITERIA_MEMORY.md and injects doctrine into CLAUDE.md

param(
    [string]$TargetDir = "."
)

$MemoryFile = Join-Path $TargetDir "USER_CRITERIA_MEMORY.md"
$ClaudeFile = Join-Path $TargetDir "CLAUDE.md"
$Marker = "## Claude Power Pack — Execution Doctrine"

Write-Host "========================================"
Write-Host "  Claude Power Pack v4.0 — Installer"
Write-Host "  Memory Flywheel + RCA + Anti-Monolith"
Write-Host "========================================"
Write-Host ""

# 1. Generate USER_CRITERIA_MEMORY.md if not exists
if (-not (Test-Path $MemoryFile)) {
    @"
# User Criteria Memory
<!-- Auto-generated by claude-power-pack. DO NOT delete this file. -->
<!-- This file stores learned preferences, corrections, and governance rules. -->
<!-- The AI reads this BEFORE every task and appends learnings AFTER corrections. -->

## Preferences
<!-- User preferences will be appended here automatically -->

## Corrections
<!-- Patterns learned from user corrections will be logged here -->

## Governance Patches
<!-- Self-healing governance updates from RCA will appear here -->
"@ | Set-Content -Path $MemoryFile -Encoding UTF8
    Write-Host "[OK] Created USER_CRITERIA_MEMORY.md" -ForegroundColor Green
} else {
    Write-Host "[SKIP] USER_CRITERIA_MEMORY.md already exists" -ForegroundColor Yellow
}

# 2. Inject doctrine into CLAUDE.md if not already present
$hasMarker = $false
if (Test-Path $ClaudeFile) {
    $content = Get-Content $ClaudeFile -Raw -ErrorAction SilentlyContinue
    if ($content -and $content.Contains($Marker)) {
        $hasMarker = $true
    }
}

if (-not $hasMarker) {
    $doctrine = @"

## Claude Power Pack — Execution Doctrine

### 0) PROMPT QUALITY GATE (Priority Zero)
BEFORE starting ANY work, evaluate the user's prompt:
- If the prompt requests 3+ disconnected, massive changes in one shot: REJECT it.
- Explain: "This violates Anti-Monolith. Each unrelated change needs its own prompt."
- Propose 2-3 micro-prompts and wait for the first one.
- This does NOT apply to multi-step tasks within ONE coherent goal.

### A) ANTI-MONOLITH: Plan First
- NEVER execute code changes without presenting a plan first.
- Cycle: OBSERVE -> PLAN -> **STOP (await approval)** -> EXECUTE -> VERIFY -> HARDEN
- For ANY task touching >1 file: present plan, wait for explicit y/n.
- For single-file trivial fixes: execute directly but VERIFY before claiming done.

### B) MEMORY FLYWHEEL: Read Before Acting
- BEFORE any task: read ``USER_CRITERIA_MEMORY.md`` if it exists in the project root.
- Apply ALL learned preferences and past corrections silently.
- If a preference conflicts with the current request: ASK, don't assume.

### C) RCA & SELF-HEALING: Fix Governance Before Code
When the user corrects you or rejects code, follow this EXACT order:
1. **HALT** — Stop all execution immediately.
2. **TRACE** — Identify: was this caused by missing context? Missing rule? Wrong assumption?
3. **HEAL GOVERNANCE** — Append the lesson to ``USER_CRITERIA_MEMORY.md`` via the memory engine.
4. **FIX CODE** — ONLY THEN apply the actual code fix.

Memory engine: ``python modules/memory-engine/append_memory.py "category: lesson learned"``

### D) VIBE CODING & SECURITY
- Use the largest model for planning/architecture, fast models for mechanical sub-tasks.
- Prefer Skills over MCP tools (MCP eats 13-14% of context window).
- Organize sub-agents by TASK (Linter, Tester), not by ROLE (Frontend Dev).
- NEVER skip authentication, RLS, or sandboxing. Security is not optional.
- After 3 failed fix attempts on the same bug: STOP, scrap patches, rebuild from scratch.

### E) DYNAMIC INTENT ROUTING & UI TOGGLING
Before processing ANY prompt, evaluate the Blast Radius:
- HIGH RISK (core files, 3+ files, architecture, deploy): operate in Plan Mode.
  First output: "⚠️ ALTO RIESGO. Activa Plan Mode (shift+tab) antes de continuar."
- LOW RISK (single file, read-only, background, audit): Bypass Permissions allowed.
  Notify: "🟢 Riesgo Bajo. Ejecutando en modo autónomo."
- Core files (auth, payments, DB, CI/CD) are ALWAYS high risk. No exceptions.

### F) SESSION REBIRTH & COMMANDS
- ``!kclear``: Abort -> dump memory to USER_CRITERIA_MEMORY.md -> dump task to HANDOFF_TASK.md -> ask user to /clear
- ``Inicia el handoff``: Read HANDOFF_TASK.md -> generate plan -> execute
- ``!phelp`` / ``!payuda``: Show Power Pack command reference table
- If context rot detected (15+ exchanges, re-reading files, quality dropping): suggest !kclear proactively

### G) EXTREME ARCHITECTURAL DEPTH BASELINE (Mandatory for New Systems)
When the user proposes a new idea, product, system, or pipeline:
- A) **NEVER accept the idea at face value.** Challenge surface-level descriptions. Extract the REAL problem being solved.
- B) **Reverse-engineer the sector's best.** Before designing, research how top-tier companies (FAANG, AAA studios, tier-1 SaaS) solve the same class of problem. Integrate their patterns.
- C) **Decompose at two scales:**
  - MACRO: system boundaries, service topology, data flow, integration points, failure domains.
  - MICRO: module internals, data structures, algorithms, API contracts, error handling paths.
- D) **Design tooling before code.** Identify parsers, data ingestion scripts, validators, and transformation pipelines needed to handle complexity BEFORE writing the final implementation.
- This is the DEFAULT depth. The user does NOT need to ask for it — it applies automatically to every new system proposal.
"@
    Add-Content -Path $ClaudeFile -Value $doctrine -Encoding UTF8
    Write-Host "[OK] Injected Power Pack doctrine into CLAUDE.md" -ForegroundColor Green
} else {
    Write-Host "[SKIP] CLAUDE.md already has Power Pack doctrine" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Done! The AI will now:" -ForegroundColor Cyan
Write-Host "  - Plan before acting (Anti-Monolith)"
Write-Host "  - Read your preferences before every task (Memory Flywheel)"
Write-Host "  - Fix governance before code on every correction (RCA Self-Healing)"
