#!/usr/bin/env bash
# Claude Power Pack — Installation Script (Unix/macOS/Linux)
# Generates USER_CRITERIA_MEMORY.md and injects doctrine into CLAUDE.md

set -e

TARGET_DIR="${1:-.}"
MEMORY_FILE="$TARGET_DIR/USER_CRITERIA_MEMORY.md"
CLAUDE_FILE="$TARGET_DIR/CLAUDE.md"
MARKER="## Claude Power Pack — Execution Doctrine"

echo "╔══════════════════════════════════════════╗"
echo "║  Claude Power Pack v4.0 — Installer      ║"
echo "║  Memory Flywheel + RCA + Anti-Monolith    ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# 1. Generate USER_CRITERIA_MEMORY.md if not exists
if [ ! -f "$MEMORY_FILE" ]; then
  cat > "$MEMORY_FILE" << 'MEMEOF'
# User Criteria Memory
<!-- Auto-generated by claude-power-pack. DO NOT delete this file. -->
<!-- This file stores learned preferences, corrections, and governance rules. -->
<!-- The AI reads this BEFORE every task and appends learnings AFTER corrections. -->

## Preferences
<!-- User preferences will be appended here automatically -->

## Corrections
<!-- Patterns learned from user corrections will be logged here -->

## Governance Patches
<!-- Self-healing governance updates from RCA will appear here -->
MEMEOF
  echo "✅ Created USER_CRITERIA_MEMORY.md"
else
  echo "⏭  USER_CRITERIA_MEMORY.md already exists, skipping"
fi

# 2. Inject doctrine into CLAUDE.md if not already present
if [ -f "$CLAUDE_FILE" ] && grep -q "$MARKER" "$CLAUDE_FILE" 2>/dev/null; then
  echo "⏭  CLAUDE.md already has Power Pack doctrine, skipping"
else
  cat >> "$CLAUDE_FILE" << 'DOCEOF'

## Claude Power Pack — Execution Doctrine

### 0) PROMPT QUALITY GATE (Priority Zero)
BEFORE starting ANY work, evaluate the user's prompt:
- If the prompt requests 3+ disconnected, massive changes in one shot: REJECT it.
- Explain: "This violates Anti-Monolith. Each unrelated change needs its own prompt."
- Propose 2-3 micro-prompts and wait for the first one.
- This does NOT apply to multi-step tasks within ONE coherent goal.

### A) ANTI-MONOLITH: Plan First
- NEVER execute code changes without presenting a plan first.
- Cycle: OBSERVE → PLAN → **STOP (await approval)** → EXECUTE → VERIFY → HARDEN
- For ANY task touching >1 file: present plan, wait for explicit y/n.
- For single-file trivial fixes: execute directly but VERIFY before claiming done.

### B) MEMORY FLYWHEEL: Read Before Acting
- BEFORE any task: read `USER_CRITERIA_MEMORY.md` if it exists in the project root.
- Apply ALL learned preferences and past corrections silently.
- If a preference conflicts with the current request: ASK, don't assume.

### C) RCA & SELF-HEALING: Fix Governance Before Code
When the user corrects you or rejects code, follow this EXACT order:
1. **HALT** — Stop all execution immediately.
2. **TRACE** — Identify: was this caused by missing context? Missing rule? Wrong assumption?
3. **HEAL GOVERNANCE** — Append the lesson to `USER_CRITERIA_MEMORY.md` via the memory engine.
4. **FIX CODE** — ONLY THEN apply the actual code fix.

Memory engine: `python modules/memory-engine/append_memory.py "category: lesson learned"`

### D) VIBE CODING & SECURITY
- Use the largest model for planning/architecture, fast models for mechanical sub-tasks.
- Prefer Skills over MCP tools (MCP eats 13-14% of context window).
- Organize sub-agents by TASK (Linter, Tester), not by ROLE (Frontend Dev).
- NEVER skip authentication, RLS, or sandboxing. Security is not optional.
- After 3 failed fix attempts on the same bug: STOP, scrap patches, rebuild from scratch.
DOCEOF
  echo "✅ Injected Power Pack doctrine into CLAUDE.md"
fi

echo ""
echo "Done! The AI will now:"
echo "  • Plan before acting (Anti-Monolith)"
echo "  • Read your preferences before every task (Memory Flywheel)"
echo "  • Fix governance before code on every correction (RCA Self-Healing)"
