#!/usr/bin/env bash
# Claude Power Pack — Installation Script (Unix/macOS/Linux)
# Generates USER_CRITERIA_MEMORY.md and injects doctrine into CLAUDE.md

set -e

TARGET_DIR="${1:-.}"
MEMORY_FILE="$TARGET_DIR/USER_CRITERIA_MEMORY.md"
CLAUDE_FILE="$TARGET_DIR/CLAUDE.md"
MARKER="## Claude Power Pack — Execution Doctrine"

echo "╔══════════════════════════════════════════╗"
echo "║  Claude Power Pack v6.4 — Installer      ║"
echo "║  Memory + RCA + Leash + OmniCapture        ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# 1. Generate USER_CRITERIA_MEMORY.md if not exists
if [ ! -f "$MEMORY_FILE" ]; then
  cat > "$MEMORY_FILE" << 'MEMEOF'
# User Criteria Memory
<!-- Auto-generated by claude-power-pack. DO NOT delete this file. -->
<!-- This file stores learned preferences, corrections, and governance rules. -->
<!-- The AI reads this BEFORE every task and appends learnings AFTER corrections. -->

## Preferences
<!-- User preferences will be appended here automatically -->

## Corrections
<!-- Patterns learned from user corrections will be logged here -->

## Governance Patches
<!-- Self-healing governance updates from RCA will appear here -->
MEMEOF
  echo "✅ Created USER_CRITERIA_MEMORY.md"
else
  echo "⏭  USER_CRITERIA_MEMORY.md already exists, skipping"
fi

# 2. Inject doctrine into CLAUDE.md if not already present
if [ -f "$CLAUDE_FILE" ] && grep -q "$MARKER" "$CLAUDE_FILE" 2>/dev/null; then
  echo "⏭  CLAUDE.md already has Power Pack doctrine, skipping"
else
  cat >> "$CLAUDE_FILE" << 'DOCEOF'

## Claude Power Pack — Execution Doctrine

### 0) PROMPT QUALITY GATE (Priority Zero)
BEFORE starting ANY work, evaluate the user's prompt:
- If the prompt requests 3+ disconnected, massive changes in one shot: REJECT it.
- Explain: "This violates Anti-Monolith. Each unrelated change needs its own prompt."
- Propose 2-3 micro-prompts and wait for the first one.
- This does NOT apply to multi-step tasks within ONE coherent goal.

### A) ANTI-MONOLITH: Plan First
- NEVER execute code changes without presenting a plan first.
- Cycle: OBSERVE → PLAN → **STOP (await approval)** → EXECUTE → VERIFY → HARDEN
- For ANY task touching >1 file: present plan, wait for explicit y/n.
- For single-file trivial fixes: execute directly but VERIFY before claiming done.

### B) MEMORY FLYWHEEL: Read Before Acting
- BEFORE any task: read `USER_CRITERIA_MEMORY.md` if it exists in the project root.
- Apply ALL learned preferences and past corrections silently.
- If a preference conflicts with the current request: ASK, don't assume.

### C) RCA & SELF-HEALING: Fix Governance Before Code
When the user corrects you or rejects code, follow this EXACT order:
1. **HALT** — Stop all execution immediately.
2. **TRACE** — Identify: was this caused by missing context? Missing rule? Wrong assumption?
3. **HEAL GOVERNANCE** — Append the lesson to `USER_CRITERIA_MEMORY.md` via the memory engine.
4. **FIX CODE** — ONLY THEN apply the actual code fix.

Memory engine: `python modules/memory-engine/append_memory.py "category: lesson learned"`

### D) VIBE CODING & SECURITY
- Use the largest model for planning/architecture, fast models for mechanical sub-tasks.
- Prefer Skills over MCP tools (MCP eats 13-14% of context window).
- Organize sub-agents by TASK (Linter, Tester), not by ROLE (Frontend Dev).
- NEVER skip authentication, RLS, or sandboxing. Security is not optional.
- After 3 failed fix attempts on the same bug: STOP, scrap patches, rebuild from scratch.

### E) DYNAMIC INTENT ROUTING & UI TOGGLING
Before processing ANY prompt, evaluate the Blast Radius:
- HIGH RISK (core files, 3+ files, architecture, deploy): operate in Plan Mode.
  First output: "⚠️ ALTO RIESGO. Activa Plan Mode (shift+tab) antes de continuar."
- LOW RISK (single file, read-only, background, audit): Bypass Permissions allowed.
  Notify: "🟢 Riesgo Bajo. Ejecutando en modo autónomo."
- Core files (auth, payments, DB, CI/CD) are ALWAYS high risk. No exceptions.

### F) SESSION REBIRTH & COMMANDS
- \`!kclear\`: Abort → dump memory to USER_CRITERIA_MEMORY.md → dump task to HANDOFF_TASK.md → ask user to /clear
- \`Inicia el handoff\`: Read HANDOFF_TASK.md → generate plan → execute
- \`!phelp\` / \`!payuda\`: Show Power Pack command reference table
- If context rot detected (15+ exchanges, re-reading files, quality dropping): suggest !kclear proactively

### G) EXTREME ARCHITECTURAL DEPTH BASELINE (Mandatory for New Systems)
When the user proposes a new idea, product, system, or pipeline:
- A) **NEVER accept the idea at face value.** Challenge surface-level descriptions. Extract the REAL problem being solved.
- B) **Reverse-engineer the sector's best.** Before designing, research how top-tier companies (FAANG, AAA studios, tier-1 SaaS) solve the same class of problem. Integrate their patterns.
- C) **Decompose at two scales:**
  - MACRO: system boundaries, service topology, data flow, integration points, failure domains.
  - MICRO: module internals, data structures, algorithms, API contracts, error handling paths.
- D) **Design tooling before code.** Identify parsers, data ingestion scripts, validators, and transformation pipelines needed to handle complexity BEFORE writing the final implementation.
- This is the DEFAULT depth. The user does NOT need to ask for it — it applies automatically to every new system proposal.

### H) THE LEASH — Background Command Isolation (MANDATORY)
You are FORBIDDEN from running mass-search or mass-read operations without explicit user permission:
- NEVER run \`grep -r\`, \`find /\`, \`rg\` across entire codebases, or read log files >500 lines in background.
- NEVER launch parallel sub-agents that each read >3 files without asking first.
- If you need to read MORE than 3 files in a single turn: STOP and ask the user:
  "I need to read N files to complete this task. Proceed? (y/n)"
- If a single file exceeds 500 lines: read only the relevant section, not the entire file.
- VIOLATIONS: If you catch yourself running a mass operation, immediately HALT and report what you did and the estimated token cost.
This rule exists because agentic loops can burn an entire daily token limit in minutes. Protecting the user's quota is non-negotiable.
DOCEOF
  echo "✅ Injected Power Pack doctrine into CLAUDE.md"
fi

# 3. Register claude-dispatch global command
SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$HOME/.claude/bin"
DISPATCH_SCRIPT="$SKILL_DIR/modules/dispatcher/dispatch.py"
WRAPPER="$BIN_DIR/claude-dispatch"
PATH_MARKER="# >>> claude-power-pack PATH >>>"

mkdir -p "$BIN_DIR"

cat > "$WRAPPER" << WRAPEOF
#!/usr/bin/env bash
exec python3 "$DISPATCH_SCRIPT" "\$@"
WRAPEOF
chmod +x "$WRAPPER"
echo "✅ Created claude-dispatch at $WRAPPER"

for profile in "$HOME/.bashrc" "$HOME/.zshrc"; do
    if [ -f "$profile" ] && ! grep -q "$PATH_MARKER" "$profile"; then
        printf '\n%s\nexport PATH="$HOME/.claude/bin:$PATH"\n# <<< claude-power-pack PATH <<<\n' "$PATH_MARKER" >> "$profile"
        echo "✅ Added ~/.claude/bin to PATH in $(basename "$profile")"
    fi
done

# 4. Register claude-daemon wrapper
DAEMON_SRC="$SKILL_DIR/modules/daemon/claude-daemon.sh"
DAEMON_WRAPPER="$BIN_DIR/claude-daemon"
SETRAM_SRC="$SKILL_DIR/modules/daemon/set-ram.sh"
SETRAM_WRAPPER="$BIN_DIR/claude-daemon-set-ram"

cp "$DAEMON_SRC" "$DAEMON_WRAPPER"
chmod +x "$DAEMON_WRAPPER"
echo "✅ Created claude-daemon at $DAEMON_WRAPPER"

cp "$SETRAM_SRC" "$SETRAM_WRAPPER"
chmod +x "$SETRAM_WRAPPER"
echo "✅ Created claude-daemon-set-ram at $SETRAM_WRAPPER"

# 5. Register omnicapture-query wrapper
OMNICAPTURE_SCRIPT="$SKILL_DIR/modules/omnicapture/query_telemetry.py"
OMNICAPTURE_WRAPPER="$BIN_DIR/omnicapture-query"

cat > "$OMNICAPTURE_WRAPPER" << OCEOF
#!/usr/bin/env bash
exec python3 "$OMNICAPTURE_SCRIPT" "\$@"
OCEOF
chmod +x "$OMNICAPTURE_WRAPPER"
echo "✅ Created omnicapture-query at $OMNICAPTURE_WRAPPER"

# Check for OmniCapture API key
if [ -n "$OMNICAPTURE_API_KEY" ]; then
  echo "✅ OMNICAPTURE_API_KEY detected — runtime telemetry enabled"
else
  echo "⚠️  OMNICAPTURE_API_KEY not set — runtime telemetry disabled"
  echo "   To enable: export OMNICAPTURE_API_KEY=oc_xxx (from your VPS config)"
  echo "   VPS setup: see modules/omnicapture/vps/ for receiver + nginx + systemd configs"
fi

# 6. Register zero-crash-sandbox wrapper
ZERO_CRASH_DIR="$SKILL_DIR/modules/zero-crash"
if [ -d "$ZERO_CRASH_DIR" ]; then
  SANDBOX_SRC="$ZERO_CRASH_DIR/sandbox-wrapper.sh"
  SANDBOX_WRAPPER="$BIN_DIR/zero-crash-sandbox"

  cp "$SANDBOX_SRC" "$SANDBOX_WRAPPER"
  chmod +x "$SANDBOX_WRAPPER"
  echo "✅ Created zero-crash-sandbox at $SANDBOX_WRAPPER"
  echo "   Hooks: To activate Zero-Crash hooks, add them to ~/.claude/settings.json"
  echo "   See: $ZERO_CRASH_DIR/README.md for hook registration instructions"
else
  echo "⚠️  Zero-Crash module not found — skipping sandbox wrapper"
fi

# 7. Register kobiiclaw VPS wrapper
KOBIICLAW_SRC="$SKILL_DIR/modules/daemon/kobiiclaw.sh"
KOBIICLAW_WRAPPER="$BIN_DIR/kobiiclaw"

if [ -f "$KOBIICLAW_SRC" ]; then
  cp "$KOBIICLAW_SRC" "$KOBIICLAW_WRAPPER"
  chmod +x "$KOBIICLAW_WRAPPER"
  echo "✅ Created kobiiclaw at $KOBIICLAW_WRAPPER"
  echo "   Usage: kobiiclaw [session] [workspace] — persistent tmux session on VPS"
else
  echo "⚠️  KobiiClaw wrapper not found — skipping"
fi

# 8. Register Power-Pack slash commands in ~/.claude/commands/
# Claude Code auto-discovers slash commands from ~/.claude/commands/ (user-global)
# and <project>/.claude/commands/ (project-local). Power-Pack's commands/ directory
# is NOT a discovery path, so we copy them out on install.
COMMANDS_SRC="$SKILL_DIR/commands"
COMMANDS_DST="$HOME/.claude/commands"
if [ -d "$COMMANDS_SRC" ]; then
  mkdir -p "$COMMANDS_DST"
  cmd_count=0
  for cmd in "$COMMANDS_SRC"/*.md; do
    [ -f "$cmd" ] || continue
    cp "$cmd" "$COMMANDS_DST/"
    cmd_count=$((cmd_count + 1))
  done
  echo "✅ Registered $cmd_count Power-Pack slash commands in $COMMANDS_DST"
else
  echo "⚠️  commands/ directory not found — skipping slash-command registration"
fi

echo ""
echo "Done! The AI will now:"
echo "  • Plan before acting (Anti-Monolith)"
echo "  • Read your preferences before every task (Memory Flywheel)"
echo "  • Fix governance before code on every correction (RCA Self-Healing)"
echo "  • Dispatch prompts to any repo (claude-dispatch)"
echo "  • Auto-recover from crashes (claude-daemon)"
echo "  • Query runtime telemetry at DEEP+ tier (OmniCapture Engine)"
echo "  • Sandbox risky processes to prevent TTY corruption (Zero-Crash)"
echo "  • Persistent VPS sessions via tmux (KobiiClaw 2.0)"
echo "  • Serve /resume, /update, /ovo-audit, /vault-sync, /cpp-customclaw, ... globally (type / in any repo)"
