# Claude Power Pack — Installation Script (Windows PowerShell)
# Generates USER_CRITERIA_MEMORY.md and injects doctrine into CLAUDE.md

param(
    [string]$TargetDir = "."
)

$MemoryFile = Join-Path $TargetDir "USER_CRITERIA_MEMORY.md"
$ClaudeFile = Join-Path $TargetDir "CLAUDE.md"
$Marker = "## Claude Power Pack — Execution Doctrine"

Write-Host "========================================"
Write-Host "  Claude Power Pack v6.4 — Installer"
Write-Host "  Memory + RCA + Leash + OmniCapture"
Write-Host "========================================"
Write-Host ""

# 1. Generate USER_CRITERIA_MEMORY.md if not exists
if (-not (Test-Path $MemoryFile)) {
    @"
# User Criteria Memory
<!-- Auto-generated by claude-power-pack. DO NOT delete this file. -->
<!-- This file stores learned preferences, corrections, and governance rules. -->
<!-- The AI reads this BEFORE every task and appends learnings AFTER corrections. -->

## Preferences
<!-- User preferences will be appended here automatically -->

## Corrections
<!-- Patterns learned from user corrections will be logged here -->

## Governance Patches
<!-- Self-healing governance updates from RCA will appear here -->
"@ | Set-Content -Path $MemoryFile -Encoding UTF8
    Write-Host "[OK] Created USER_CRITERIA_MEMORY.md" -ForegroundColor Green
} else {
    Write-Host "[SKIP] USER_CRITERIA_MEMORY.md already exists" -ForegroundColor Yellow
}

# 2. Inject doctrine into CLAUDE.md if not already present
$hasMarker = $false
if (Test-Path $ClaudeFile) {
    $content = Get-Content $ClaudeFile -Raw -ErrorAction SilentlyContinue
    if ($content -and $content.Contains($Marker)) {
        $hasMarker = $true
    }
}

if (-not $hasMarker) {
    $doctrine = @"

## Claude Power Pack — Execution Doctrine

### 0) PROMPT QUALITY GATE (Priority Zero)
BEFORE starting ANY work, evaluate the user's prompt:
- If the prompt requests 3+ disconnected, massive changes in one shot: REJECT it.
- Explain: "This violates Anti-Monolith. Each unrelated change needs its own prompt."
- Propose 2-3 micro-prompts and wait for the first one.
- This does NOT apply to multi-step tasks within ONE coherent goal.

### A) ANTI-MONOLITH: Plan First
- NEVER execute code changes without presenting a plan first.
- Cycle: OBSERVE -> PLAN -> **STOP (await approval)** -> EXECUTE -> VERIFY -> HARDEN
- For ANY task touching >1 file: present plan, wait for explicit y/n.
- For single-file trivial fixes: execute directly but VERIFY before claiming done.

### B) MEMORY FLYWHEEL: Read Before Acting
- BEFORE any task: read ``USER_CRITERIA_MEMORY.md`` if it exists in the project root.
- Apply ALL learned preferences and past corrections silently.
- If a preference conflicts with the current request: ASK, don't assume.

### C) RCA & SELF-HEALING: Fix Governance Before Code
When the user corrects you or rejects code, follow this EXACT order:
1. **HALT** — Stop all execution immediately.
2. **TRACE** — Identify: was this caused by missing context? Missing rule? Wrong assumption?
3. **HEAL GOVERNANCE** — Append the lesson to ``USER_CRITERIA_MEMORY.md`` via the memory engine.
4. **FIX CODE** — ONLY THEN apply the actual code fix.

Memory engine: ``python modules/memory-engine/append_memory.py "category: lesson learned"``

### D) VIBE CODING & SECURITY
- Use the largest model for planning/architecture, fast models for mechanical sub-tasks.
- Prefer Skills over MCP tools (MCP eats 13-14% of context window).
- Organize sub-agents by TASK (Linter, Tester), not by ROLE (Frontend Dev).
- NEVER skip authentication, RLS, or sandboxing. Security is not optional.
- After 3 failed fix attempts on the same bug: STOP, scrap patches, rebuild from scratch.

### E) DYNAMIC INTENT ROUTING & UI TOGGLING
Before processing ANY prompt, evaluate the Blast Radius:
- HIGH RISK (core files, 3+ files, architecture, deploy): operate in Plan Mode.
  First output: "⚠️ ALTO RIESGO. Activa Plan Mode (shift+tab) antes de continuar."
- LOW RISK (single file, read-only, background, audit): Bypass Permissions allowed.
  Notify: "🟢 Riesgo Bajo. Ejecutando en modo autónomo."
- Core files (auth, payments, DB, CI/CD) are ALWAYS high risk. No exceptions.

### F) SESSION REBIRTH & COMMANDS
- ``!kclear``: Abort -> dump memory to USER_CRITERIA_MEMORY.md -> dump task to HANDOFF_TASK.md -> ask user to /clear
- ``Inicia el handoff``: Read HANDOFF_TASK.md -> generate plan -> execute
- ``!phelp`` / ``!payuda``: Show Power Pack command reference table
- If context rot detected (15+ exchanges, re-reading files, quality dropping): suggest !kclear proactively

### G) EXTREME ARCHITECTURAL DEPTH BASELINE (Mandatory for New Systems)
When the user proposes a new idea, product, system, or pipeline:
- A) **NEVER accept the idea at face value.** Challenge surface-level descriptions. Extract the REAL problem being solved.
- B) **Reverse-engineer the sector's best.** Before designing, research how top-tier companies (FAANG, AAA studios, tier-1 SaaS) solve the same class of problem. Integrate their patterns.
- C) **Decompose at two scales:**
  - MACRO: system boundaries, service topology, data flow, integration points, failure domains.
  - MICRO: module internals, data structures, algorithms, API contracts, error handling paths.
- D) **Design tooling before code.** Identify parsers, data ingestion scripts, validators, and transformation pipelines needed to handle complexity BEFORE writing the final implementation.
- This is the DEFAULT depth. The user does NOT need to ask for it — it applies automatically to every new system proposal.

### H) THE LEASH — Background Command Isolation (MANDATORY)
You are FORBIDDEN from running mass-search or mass-read operations without explicit user permission:
- NEVER run ``grep -r``, ``find /``, ``rg`` across entire codebases, or read log files >500 lines in background.
- NEVER launch parallel sub-agents that each read >3 files without asking first.
- If you need to read MORE than 3 files in a single turn: STOP and ask the user:
  "I need to read N files to complete this task. Proceed? (y/n)"
- If a single file exceeds 500 lines: read only the relevant section, not the entire file.
- VIOLATIONS: If you catch yourself running a mass operation, immediately HALT and report what you did and the estimated token cost.
This rule exists because agentic loops can burn an entire daily token limit in minutes. Protecting the user's quota is non-negotiable.
"@
    Add-Content -Path $ClaudeFile -Value $doctrine -Encoding UTF8
    Write-Host "[OK] Injected Power Pack doctrine into CLAUDE.md" -ForegroundColor Green
} else {
    Write-Host "[SKIP] CLAUDE.md already has Power Pack doctrine" -ForegroundColor Yellow
}

# 3. Register claude-dispatch global command
$SkillDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinDir = Join-Path $env:USERPROFILE ".claude\bin"
$DispatchScript = Join-Path $SkillDir "modules\dispatcher\dispatch.py"
$Wrapper = Join-Path $BinDir "claude-dispatch.cmd"

if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
}

@"
@echo off
python "$DispatchScript" %*
"@ | Set-Content -Path $Wrapper -Encoding ASCII
Write-Host "[OK] Created claude-dispatch.cmd at $Wrapper" -ForegroundColor Green

$currentPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($currentPath -notlike "*$BinDir*") {
    [Environment]::SetEnvironmentVariable("PATH", "$BinDir;$currentPath", "User")
    Write-Host "[OK] Added $BinDir to user PATH" -ForegroundColor Green
} else {
    Write-Host "[SKIP] $BinDir already in user PATH" -ForegroundColor Yellow
}

# 4. Register claude-daemon wrapper
$DaemonSrc = Join-Path $SkillDir "modules\daemon\claude-daemon.bat"
$DaemonWrapper = Join-Path $BinDir "claude-daemon.cmd"
$SetRamSrc = Join-Path $SkillDir "modules\daemon\set-ram.bat"
$SetRamWrapper = Join-Path $BinDir "claude-daemon-set-ram.cmd"

Copy-Item -Path $DaemonSrc -Destination $DaemonWrapper -Force
Write-Host "[OK] Created claude-daemon.cmd" -ForegroundColor Green

Copy-Item -Path $SetRamSrc -Destination $SetRamWrapper -Force
Write-Host "[OK] Created claude-daemon-set-ram.cmd" -ForegroundColor Green

# 5. Register omnicapture-query wrapper
$OmniCaptureScript = Join-Path $SkillDir "modules\omnicapture\query_telemetry.py"
$OmniCaptureWrapper = Join-Path $BinDir "omnicapture-query.cmd"

@"
@echo off
python "$OmniCaptureScript" %*
"@ | Set-Content -Path $OmniCaptureWrapper -Encoding ASCII
Write-Host "[OK] Created omnicapture-query.cmd at $OmniCaptureWrapper" -ForegroundColor Green

# Check for OmniCapture API key
if ($env:OMNICAPTURE_API_KEY) {
    Write-Host "[OK] OMNICAPTURE_API_KEY detected — runtime telemetry enabled" -ForegroundColor Green
} else {
    Write-Host "[WARN] OMNICAPTURE_API_KEY not set — runtime telemetry disabled" -ForegroundColor Yellow
    Write-Host "   To enable: set OMNICAPTURE_API_KEY=oc_xxx (from your VPS config)"
    Write-Host "   VPS setup: see modules\omnicapture\vps\ for receiver + nginx + systemd configs"
}

# 6. Register zero-crash-sandbox wrapper
$ZeroCrashDir = Join-Path $SkillDir "modules\zero-crash"
if (Test-Path $ZeroCrashDir) {
    $SandboxSrc = Join-Path $ZeroCrashDir "sandbox-wrapper.ps1"
    $SandboxWrapper = Join-Path $BinDir "zero-crash-sandbox.cmd"

    @"
@echo off
powershell -ExecutionPolicy Bypass -File "$SandboxSrc" %*
"@ | Set-Content -Path $SandboxWrapper -Encoding ASCII
    Write-Host "[OK] Created zero-crash-sandbox.cmd at $SandboxWrapper" -ForegroundColor Green
    Write-Host "   Hooks: To activate Zero-Crash hooks, add them to ~/.claude/settings.json"
    Write-Host "   See: $ZeroCrashDir\README.md for hook registration instructions"
} else {
    Write-Host "[WARN] Zero-Crash module not found — skipping sandbox wrapper" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Done! The AI will now:" -ForegroundColor Cyan
Write-Host "  - Plan before acting (Anti-Monolith)"
Write-Host "  - Read your preferences before every task (Memory Flywheel)"
Write-Host "  - Fix governance before code on every correction (RCA Self-Healing)"
Write-Host "  - Dispatch prompts to any repo (claude-dispatch)"
Write-Host "  - Auto-recover from crashes (claude-daemon)"
Write-Host "  - Query runtime telemetry at DEEP+ tier (OmniCapture Engine)"
Write-Host "  - Sandbox risky processes to prevent TTY corruption (Zero-Crash)"
