"""Zero-model dossier for the R1 recon-factory reforecast.

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_dossier.py
Writes DOSSIER.md next to this file. Every section is copied or counted from a named source whose
sha256 is recorded, so the worker classifies from this file alone and never re-reads the corpus.
A missing source is written as MISSING with its path; it is never silently skipped.
"""
import collections
import hashlib
import json
import os
import re
import subprocess
import sys

PP = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", ".."))
WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
WS = os.path.join(WT, ".planning", "workstreams", "recon-factory")
LEVELS = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\levels.jsonl"
GIT = r"C:\Program Files\Git\cmd\git.exe"
CE = os.path.join(PP, "vault", "programs", "cognitive-economy")
SOURCES = {
    "roadmap": os.path.join(WS, "ROADMAP.md"),
    "state": os.path.join(WS, "STATE.md"),
    "t3_receipt": os.path.join(CE, "gen3", "T3-receipt.md"),
    "stage0": os.path.join(CE, "gen2", "evidence", "stage0", "README.md"),
    "tok18": os.path.join(PP, "vault", "plans", "tok18-pre-rearm-optimization-RESUMPTION.md"),
    "ctx_rent": os.path.join(os.path.expanduser("~"), ".claude", "projects",
                             "C--Users-User--claude-skills-claude-power-pack", "memory",
                             "project_ce_lifecycle_a1_ctx_rent_canary.md"),
}
REMAINING = ["2", "3", "5", "6", "7", "8", "9"]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "DOSSIER.md")


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def sha(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def section(text, start_re, stop_re):
    lines, out, on = text.splitlines(), [], False
    for ln in lines:
        if re.match(start_re, ln):
            on = True
        elif on and re.match(stop_re, ln):
            break
        if on:
            out.append(ln)
    return out


def git(*args):
    r = subprocess.run([GIT, "-C", WT, *args], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.returncode != 0:
        raise RuntimeError("git %s failed: %s" % (" ".join(args), r.stderr.strip()))
    return r.stdout.splitlines()


def main():
    out = ["# R1 dossier (zero-model, generated by build_dossier.py)", "", "## Sources (sha256 prefix)"]
    texts = {}
    for k, p in SOURCES.items():
        if os.path.exists(p):
            texts[k] = read(p)
            out.append("- %s: %s `%s`" % (k, p, sha(p)))
        else:
            out.append("- %s: MISSING %s" % (k, p))
    head = git("rev-parse", "--short", "HEAD")[0]
    out.append("- recon work tree HEAD: `%s`" % head)

    rm = texts.get("roadmap", "")
    out += ["", "## Phase checklist (ROADMAP)"] + [ln for ln in rm.splitlines() if re.match(r"^- \[[ x]\] \*\*Phase", ln)]
    for ph in REMAINING:
        out += ["", "## ROADMAP Phase %s detail" % ph]
        out += section(rm, r"^### Phase %s:" % re.escape(ph), r"^### Phase ") or ["MISSING section"]
    out += ["", "## ROADMAP audit gaps"] + (section(rm, r"^## Audit gaps", r"^## (?!Audit)") or ["MISSING section"])

    out += ["", "## Phase directories (files present)"]
    pdir = os.path.join(WS, "phases")
    for d in sorted(os.listdir(pdir)):
        full = os.path.join(pdir, d)
        if os.path.isdir(full):
            out.append("- %s: %s" % (d, ", ".join(sorted(os.listdir(full)))))
    for d in sorted(os.listdir(pdir)):
        if d.startswith("02-"):
            p = os.path.join(pdir, d, "02-02-SUMMARY.md")
            out += ["", "## 02-02-SUMMARY.md (verbatim)"]
            out += read(p).splitlines() if os.path.exists(p) else ["MISSING %s" % p]

    log = git("log", "--date=short", "--format=%h %ad %s", "--", ".planning/workstreams/recon-factory", "tools/wros/binary/decomp")
    tags = collections.Counter()
    for ln in log:
        m = re.search(r"recon-factory-(\d+(?:\.\d+)?)", ln)
        tags[m.group(1) if m else "untagged"] += 1
    out += ["", "## Commits touching the workstream or decomp/ (%d total)" % len(log)]
    out += ["- by phase tag: %s" % dict(sorted(tags.items()))] + ["- " + ln for ln in log[:25]]

    out += ["", "## levels.jsonl population"]
    if os.path.exists(LEVELS):
        rows, keys, vals = 0, collections.Counter(), collections.defaultdict(collections.Counter)
        with open(LEVELS, encoding="utf-8") as f:
            for ln in f:
                ln = ln.strip()
                if not ln:
                    continue
                rec = json.loads(ln)
                rows += 1
                for dim, d in (rec.get("dimensions") or {}).items():
                    vals["verdict." + dim][d.get("verdict")] += 1
                for k, v in rec.items():
                    keys[k] += 1
                    if isinstance(v, (str, int, bool)) or v is None:
                        vals[k][v if not isinstance(v, str) or len(v) <= 40 else "<long>"] += 1
        out.append("- rows: %d `%s`" % (rows, sha(LEVELS)))
        out.append("- keys: %s" % dict(keys))
        for k, c in vals.items():
            if len(c) <= 12:
                out.append("- %s: %s" % (k, dict(c.most_common())))
    else:
        out.append("- MISSING %s" % LEVELS)

    out += ["", "## T3 receipt (verbatim)"] + texts.get("t3_receipt", "MISSING").splitlines()
    out += ["", "## Stage 0 KSR row"] + [ln for ln in texts.get("stage0", "").splitlines() if "KSR" in ln][:6]
    heads = [ln for ln in texts.get("tok18", "").splitlines() if ln.startswith(("Headlines:", "- Factorial ceilings"))]
    out += ["", "## gen3_t2 / T1 headline lines (tok18 RESUMPTION)"] + (heads or ["MISSING headline lines"])
    out += ["", "## Context Rent owner (ce-lifecycle A1 memory, verbatim)"] + (texts.get("ctx_rent") or "MISSING").splitlines()

    body = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("DOSSIER %s chars=%d lines=%d est_tokens=%d" % (OUT, len(body), body.count("\n"), len(body) // 4))
    return 0


if __name__ == "__main__":
    sys.exit(main())
