"""Zero-model dossier for the P2a lease (recon-factory Phase 2 GEX44 leg, LOCAL half: A/A returned-object leg, AA-gate
capsule in the recon-factory root, second live root in stage.py, build without send).

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_p2a_dossier.py
Writes P2A-DOSSIER.md next to this file: the verbatim source of every function the worker edits or calls (AST-extracted
with line numbers), AA_GATE.md in full, the Owner decisions, measured facts about the factory root and the 032929
return, and P2a policy v1.
"""
import ast
import hashlib
import json
import os
import sys

WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
DEC = os.path.join(WT, "tools", "wros", "binary", "decomp")
G = os.path.join(DEC, "gex44")
F = r"C:\Users\User\Apps\recon_work\match_accel_factory"
F_G = os.path.join(F, "gex44")
RF_ROOT = r"C:\Users\User\Apps\recon_work\recon_factory\gex44"
RETURN = os.path.join(F_G, "returns", "ksrmb-20261001-032929")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "P2A-DOSSIER.md")

# file -> (full-body names, signature-only names). "<consts>" = every top-level assignment before the first def.
SPEC = {
    os.path.join(G, "stage.py"): (["<consts>", "gex44_root", "live_root_problem", "resolve_capsule", "chain_rows",
                                   "chain_append", "chain_verify", "phase_add_count", "_default_preflight",
                                   "find_job_record", "send", "wait", "main"], ["build"]),
    os.path.join(G, "reproduce.py"): (["<consts>", "build_units"], []),
    os.path.join(G, "capsule_build.py"): (["default_inputs", "resolve_units", "build", "main"], ["_stage_and_seal"]),
    os.path.join(G, "custody.py"): ([], ["*"]),
    os.path.join(DEC, "oracle_parity.py"): (["<consts>", "Judge", "verdict_class", "aa_leg", "cross_plane", "run",
                                             "main"], []),
}


def sha(p):
    with open(p, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def tree_digest(root):
    h, n = hashlib.sha256(), 0
    for d, _, files in sorted(os.walk(root)):
        for f in sorted(files):
            p = os.path.join(d, f)
            h.update(os.path.relpath(p, root).encode() + b"\0" + str(os.path.getsize(p)).encode() + b"\n")
            n += 1
    return h.hexdigest(), n


def extract(path, full, sigs):
    src = open(path, encoding="utf-8").read()
    lines = src.splitlines()
    tree = ast.parse(src)
    out, found = [], set()
    first_def = next((n.lineno for n in tree.body if isinstance(n, (ast.FunctionDef, ast.ClassDef))), len(lines))
    if "<consts>" in full:
        consts = [ln for n in tree.body if isinstance(n, (ast.Assign, ast.AnnAssign)) and n.lineno < first_def
                  for ln in lines[n.lineno - 1:n.end_lineno]]
        out += ["", "#### constants (top-level assignments before the first def)", "```python"] + consts + ["```"]
        found.add("<consts>")
    for n in tree.body:
        if not isinstance(n, (ast.FunctionDef, ast.ClassDef)):
            continue
        if n.name in full:
            out += ["", "#### %s (line %d)" % (n.name, n.lineno), "```python"] + lines[n.lineno - 1:n.end_lineno] + ["```"]
            found.add(n.name)
        elif n.name in sigs or "*" in sigs:
            head = lines[n.lineno - 1]
            doc = ast.get_docstring(n) or ""
            out.append("- `%s` (line %d) -- %s" % (head.strip(), n.lineno, doc.splitlines()[0] if doc else "no docstring"))
            found.add(n.name)
    missing = [x for x in full + sigs if x != "*" and x not in found]
    return out, missing


def main():
    body = ["# P2a dossier (zero-model, generated by build_p2a_dossier.py)", "",
            "Everything below is copied or computed from a named source. Read this file only.", "", "## Inputs (sha256)"]
    for p in list(SPEC) + [os.path.join(DEC, "AA_GATE.md")]:
        body.append("- `%s` sha256 `%s`" % (p, sha(p)))

    st = open(os.path.join(WT, ".planning", "workstreams", "recon-factory", "STATE.md"), encoding="utf-8").read().splitlines()
    i = next(n for n, ln in enumerate(st) if ln.startswith("**RESOLVED 2026-10-05"))
    body += ["", "## Owner decisions (STATE.md, verbatim)"] + st[i:i + 9]

    f_digest, f_n = tree_digest(F_G)
    ret_units = os.path.join(RETURN, "run", "units")
    objs = sorted(f for f in os.listdir(ret_units) if f.endswith(".o")) if os.path.isdir(ret_units) else []
    body += ["", "## Measured facts",
             "- Factory gex44 root `%s`: %d files, listing digest %s (path+size). It must be IDENTICAL after P2a." % (F_G, f_n, f_digest),
             "- Recon-factory root `%s` exists: %s." % (RF_ROOT, os.path.isdir(RF_ROOT)),
             "- Return 032929 `%s`: %d .o under run/units (e.g. %s)." % (RETURN, len(objs), objs[:3]),
             "- Reference for the A/A leg: `%s\\ledger.jsonl` (374 rows; canonical match.py e71d426c judged them locally)." % F,
             "- reproduce.build_units refuses ENTITY_NOT_IN_CAPSULE for any entity not in the capsule manifest; the CURRENT"
             " capsule holds only the 298 proven units (5 sealed + 289 donors + 4 model), so AA_GATE's DIFF/SIZE entities need"
             " a new capsule.",
             "- stage.send refuses any root but the factory root (live_root_problem below): the job cap and STOP are counted"
             " against that root's own jobs ledger."]

    body += ["", "## AA_GATE.md (verbatim, the frozen draw and criteria)"]
    body += open(os.path.join(DEC, "AA_GATE.md"), encoding="utf-8").read().splitlines()

    body += ["", "## P2a policy v1 (implement exactly this; design inside the extracted code)",
             "1. Second live root. stage.py gains RF_GEX44_ROOT = %r and a registry of live roots {factory root: existing"
             " PHASE_JOB_CAPS/CURRENT_PHASE, RF_GEX44_ROOT: own caps {2: 2}, current phase 2}. live_root_problem accepts"
             " exactly these two (anything else still refused). send() counts the cap, reads STOP and appends the jobs"
             " ledger of THE ROOT IT WAS GIVEN, never the other one. The factory root's behaviour is byte-for-byte unchanged." % RF_ROOT,
             "2. AA capsule. capsule_build.py gains `--aa-gate <AA_GATE.md> --out-root <root>`: units = the 40 drawn entities"
             " (parsed from the AA_GATE table; source, sha256 and preset from the factory ledger row at that seq, read-only)"
             " plus ONE planted mutant of main:800ECE30: its source with exactly one byte changed inside the function body"
             " (first decimal digit after the first '{' incremented mod 10), carried as a distinct unit whose id cannot"
             " collide. Written under <root>/capsules/<id>/ only; refuses when --out-root resolves inside %s." % F,
             "3. reproduce.build_units accepts an AA-gate capsule (its manifest marks the selection) and builds 41 units;"
             " the existing 298-unit selection rules are unchanged for every other capsule.",
             "4. oracle_parity.py gains aa_returned(job_dir, reference_ledger) per 02-02-PLAN Task 1: judge every returned"
             " run/units/<uid>.o with the canonical judge, join to the reference by entity, report per unit: canonical verdict"
             " equal, object sha equal, .text sha equal, Linux objdiff pct beside the recorded one; MATCH_RELOC_UNVERIFIED"
             " its own class. Plus `aa_gate_verdict(report, AA_GATE)` applying the 5 PASS criteria.",
             "5. Build, NO send: `stage.py build --mode reproduce --capsule <AA capsule id>` with the RF root, printing BUILD=<tag>"
             " and FIT. Nothing contacts the VPS or GEX44 in P2a.",
             "", "## Drill gates (test_p2a.py; PASS/FAIL V-P2A-*, final P2A_DRILL=n/m)",
             "- V-P2A-RETURNED: aa_returned on the real 032929 return judges > 0 units with 0 dropped joins; a planted wrong"
             " reference row is reported DISAGREE.",
             "- V-P2A-CAPSULE: the AA capsule has 41 units (40 + mutant) and custody.verify_manifest passes on it.",
             "- V-P2A-MUTANT: mutant source differs from the original in exactly one byte, inside the body.",
             "- V-P2A-ROOT: live_root_problem(factory root) None, (RF root) None, (a temp dir) refused.",
             "- V-P2A-CAP: send() against an RF-root fixture whose ledger already holds 2 phase-2 rows refuses CAP_REACHED"
             " before any remote call (the injected remote raises if called).",
             "- V-P2A-BUILD: the real build lands in <RF root>/jobs/<tag> with 41 units; nothing sent.",
             "- V-P2A-F-UNTOUCHED: the factory gex44 listing digest equals the one in Measured facts."]

    missing_all = []
    for path, (full, sigs) in SPEC.items():
        part, missing = extract(path, full, sigs)
        missing_all += ["%s:%s" % (os.path.basename(path), m) for m in missing]
        body += ["", "## %s (verbatim extracts)" % os.path.relpath(path, WT)] + part
    body += ["", "Not found by the extractor: %s" % (missing_all or "none")]

    text = "\n".join(body) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("P2A-DOSSIER chars=%d est_tokens=%d objs=%d f_files=%d missing=%s"
          % (len(text), len(text) // 4, len(objs), f_n, missing_all))
    return 0 if not missing_all else 1


if __name__ == "__main__":
    sys.exit(main())
