"""Zero-model dossier for the P7-G0 lease (recon-factory Phase 7, G0 freeze only; no run, no GEX44).

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_p7g0_dossier.py
Writes P7G0-DOSSIER.md next to this file. G0 policy v1 is stated once here and the draw it implies is computed live,
reusing decomp baseline.py's population / cut_points / allocate, so the worker's drill has an oracle (sorted-id sha256
of the draw and of the holdout) it did not write.
"""
import collections
import hashlib
import json
import os
import random
import sys

WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
DECOMP = os.path.join(WT, "tools", "wros", "binary", "decomp")
KSR = r"C:\Users\User\Desktop\Cursor Projects\Wii Projects\KobiiSports Resort\CursorProjects"
PLAN = os.path.join(KSR, ".ksr_vault", "frontier", "KEOS_RECON_FACTORY_PLAN.md")
OC = r"C:\Users\User\Apps\recon_work\match_accel_factory\census\OPPORTUNITY_CENSUS.jsonl"
L0 = r"C:\Users\User\Apps\recon_work\decomp_factory\corpus\main_L0.jsonl"
LEVELS = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\levels.jsonl"
LO, HI = 0x8042529C, 0x80455FF0
SHARED = {0x8043141C, 0x80437F4C}
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "P7G0-DOSSIER.md")

# G0 policy v1 -- the single statement of it.
SALT = "ksr.recon.g0/1"
N_PLN, N_REST, N_HOLDOUT = 100, 200, 60
BLOCKER_GROUPS = (("LIB", "TOOLCHAIN_UNPROBED_LIBRARY"), ("SDA", "FLAGS_BLOCKED_SDA"))

sys.path.insert(0, DECOMP)
import baseline as B  # noqa: E402


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(ln) for ln in f if ln.strip()]


def addr(row_id):
    return int(row_id.split(":")[1], 16)


def blocker_group(blockers):
    return next((g for g, b in BLOCKER_GROUPS if b in blockers), "NONE")


def stratified(rows, cuts, n, seed_hex):
    by = collections.defaultdict(list)
    for r in rows:
        by[(r["class"], B.stratum_of(dict(r, closure=False), cuts)[1], r["bgroup"])].append(r)
    alloc = B.allocate({k: len(v) for k, v in by.items()}, n)
    rng = random.Random(int(seed_hex, 16))
    chosen = []
    for k in sorted(by):
        chosen += rng.sample(sorted(by[k], key=lambda r: r["census_id"]), alloc.get(k, 0))
    return chosen, alloc, by


def ids_sha(rows):
    return hashlib.sha256("\n".join(sorted(r["census_id"] for r in rows)).encode()).hexdigest()


def main():
    oc, l0, lv = jsonl(OC), jsonl(L0), jsonl(LEVELS)
    s_oc, s_l0 = sha(OC), sha(L0)
    corpus = {r["id"]: r for r in l0}
    l3 = {r["id"] for r in lv if r["levels"].get("L3")}
    blk = {r["id"]: r["blockers"] for r in oc}
    pop, excluded = B.population(oc, corpus)
    pop = [dict(r, bgroup=blocker_group(blk[r["census_id"]])) for r in pop if r["census_id"] not in l3]
    cuts = {c: B.cut_points([r["insns"] for r in pop if r["class"] == c]) for c in B.CLASSES}
    is_pln = lambda r: LO <= addr(r["census_id"]) < HI and addr(r["census_id"]) not in SHARED  # noqa: E731
    pln = [r for r in pop if is_pln(r)]
    rest = [r for r in pop if not is_pln(r)]
    seed = hashlib.sha256((s_oc + s_l0 + SALT).encode()).hexdigest()
    seed_h = hashlib.sha256((seed + ":holdout").encode()).hexdigest()
    d_pln, a_pln, _ = stratified(pln, cuts, N_PLN, seed)
    d_rest, a_rest, _ = stratified(rest, cuts, N_REST, hashlib.sha256((seed + ":rest").encode()).hexdigest())
    drawn = d_pln + d_rest
    taken = {r["census_id"] for r in drawn}
    hold, a_hold, _ = stratified([r for r in pop if r["census_id"] not in taken], cuts, N_HOLDOUT, seed_h)

    frozen = json.load(open(B.DRAW_PATH, encoding="utf-8"))
    f_ids = {r["census_id"] for r in frozen["ids"]}
    out = ["# P7-G0 dossier (zero-model, generated by build_p7g0_dossier.py)", "",
           "Everything below is copied or computed from a named source. Read this file only.", "", "## Inputs (sha256)",
           "- `%s` sha256 `%s`" % (OC, s_oc), "- `%s` sha256 `%s`" % (L0, s_l0), "- `%s` sha256 `%s`" % (LEVELS, sha(LEVELS)),
           "- frozen baseline draw `%s` (baseline.DRAW_PATH; `baseline.py check-frozen` -> DRAW_FROZEN freeze_commit="
           "66e99660 n=165): sha256 `%s`, schema %s, id format e.g. %s" % (B.DRAW_PATH, sha(B.DRAW_PATH), frozen["schema"],
                                                                       frozen["ids"][0]["census_id"]),
           "", "## KEOS_RECON_FACTORY_PLAN.md section 16 + D2 + R1 (verbatim)"]
    pl = open(PLAN, encoding="utf-8").read().splitlines()
    out += [ln for ln in pl if ln.startswith("| D2 ")] + pl[120:133] + [ln for ln in pl if ln.startswith("- R1: arm A")]
    out += [ln for ln in pl if "CD#27" in ln and ln.lstrip().startswith("`claude`")]
    rm = open(os.path.join(WT, ".planning", "workstreams", "recon-factory", "ROADMAP.md"), encoding="utf-8").read().splitlines()
    i = next(n for n, ln in enumerate(rm) if ln.startswith("### Phase 7:"))
    out += ["", "## ROADMAP Phase 7 (verbatim, first 5 lines + GAP-4)"] + rm[i:i + 5] + [ln for ln in rm[i:i + 20] if "GAP-4" in ln]
    out += ["", "## Facts that shape G0",
            "- Arm A has NEVER run: decomp_factory/baseline is empty (STATE.md 'Reality at creation'). So no arm-A number exists"
            " and CD#27 forbids fixing a numeric threshold now: G0 freezes the PROCEDURE that turns arm-A numbers into the"
            " threshold at checkpoint 50, never a number.",
            "- Centrality: no corpus-wide caller graph exists in the evidence (closure_profiles answers callers only for"
            " closure functions with a STRUCT record). Centrality is NOT a stratum axis in v1; record it as a named deviation.",
            "- Hard-blocked rows (SDA/LIB/CXX) are drawn on purpose: they are the wall the benchmark must measure. Router v1"
            " routes them BLOCKED_TOOLCHAIN; per-stratum reports show that, never drop them.",
            "- Reused decomp API (import from the decomp dir, `import baseline as B`): B.population(census_rows, corpus_by_id)"
            " -> (rows sorted by census_id with census_id,name,class,insns,closure; excluded MATCH_DRILL_FIVE ids),"
            " B.cut_points(insns_list) -> [q1,q2,q3] (statistics.quantiles n=4 inclusive), B.stratum_of(row, cuts)[1] ->"
            " Q1..Q4 from cuts[row['class']], B.allocate(sizes, n_target) (rule: %s), B.CLASSES = %s." % (B.ALLOCATION_RULE, B.CLASSES)]
    out += ["", "## G0 policy v1 (implement exactly this)",
            "1. Population = B.population(OPPORTUNITY_CENSUS rows, main_L0 rows keyed by id) minus levels L3 rows; n=%d"
            " (excluded drill %d). bgroup = first of %s present in the census row's blockers, else NONE."
            % (len(pop), len(excluded), BLOCKER_GROUPS),
            "2. cuts = {c: B.cut_points(insns of population rows of class c)} for c in B.CLASSES (whole population).",
            "3. Stratum key = (class, B.stratum_of(dict(row, closure=False), cuts)[1], bgroup). Class covers CXX and PS.",
            "4. seed = sha256_hex(census_sha256 + corpus_sha256 + %r); rest_seed = sha256_hex(seed + ':rest');"
            " holdout_seed = sha256_hex(seed + ':holdout'). Hex strings, utf-8." % SALT,
            "5. Draw: Pln part = %d from Pln population rows (M0 region minus the 2 shared helpers) with seed; rest part ="
            " %d from non-Pln rows with rest_seed. Each part: by-stratum allocation B.allocate, then for k in sorted strata"
            " random.Random(int(seed,16)).sample(members sorted by census_id, alloc[k]) with ONE rng per part." % (N_PLN, N_REST),
            "6. Holdout = %d from population minus the draw, same procedure, holdout_seed. Written to its own file; the"
            " freeze record stores only its sha256 and n. No checkpoint before 300 may read it." % N_HOLDOUT,
            "7. Preregistration (text in the freeze record, no numbers): metric = median comparable cost per L3 per stratum as"
            " the vector (wall_s, compiles, LOCAL tokens, PAID tokens), wall_s compared only within one host_plane (GAP-4)."
            " 'Materially falls' at CP50 = for each cost component, arm-B median below the LOWER bound of the 95% bootstrap"
            " CI (10,000 resamples, seed = seed) of the arm-A median on the same stratum and plane; threshold computed from"
            " arm A BEFORE arm B is read. Learning curve (CP50 amendment c): new-cognition cost median of draw-order"
            " functions 31-50 below the lower 95% bootstrap CI bound of functions 1-20; no fall = stop and fix family"
            " solving before Phase 8. Unit for CP50 = novelty cluster / family frontier (amendment b) -- recorded, not"
            " implemented here. Owner may amend this text before the first run; never after.",
            "", "## Expected draw, policy v1 (computed live by this builder -- the drill's oracle)",
            "- population %d (Pln %d, rest %d); strata used Pln %d, rest %d" % (len(pop), len(pln), len(rest),
                                                                                 len([k for k in a_pln if a_pln[k]]),
                                                                                 len([k for k in a_rest if a_rest[k]])),
            "- seed %s" % seed,
            "- draw n=%d sorted-id sha256 %s (Pln %d sha256 %s)" % (len(drawn), ids_sha(drawn), len(d_pln), ids_sha(d_pln)),
            "- holdout n=%d sorted-id sha256 %s" % (len(hold), ids_sha(hold)),
            "- draw by class: %s" % dict(sorted(collections.Counter(r["class"] for r in drawn).items())),
            "- draw by bgroup: %s" % dict(sorted(collections.Counter(r["bgroup"] for r in drawn).items())),
            "- overlap with the frozen n=165: draw %d, holdout %d (report only; arm A has no data to reuse yet)"
            % (len(f_ids & taken), len(f_ids & {r["census_id"] for r in hold}))]
    body = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    ok = len(drawn) == N_PLN + N_REST and len(hold) == N_HOLDOUT and not (taken & {r["census_id"] for r in hold})
    print("P7G0-DOSSIER chars=%d est_tokens=%d pop=%d pln=%d draw=%d holdout=%d ok=%s"
          % (len(body), len(body) // 4, len(pop), len(pln), len(drawn), len(hold), ok))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
