"""Zero-model dossier for the P5b re-lease (recon-factory Phase 5: closure census + population matrix).

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_p5_dossier.py
Writes P5-DOSSIER.md next to this file. P5 (m-6d6bb4cef637) spent 1.41M searching for the M0 source; every premise the
worker needs is pinned here instead: input paths with sha256, row schemas, the M0 method lines, and the M0 histogram
recomputed live from the census so the worker starts from a verified recipe.
"""
import collections
import hashlib
import json
import os
import subprocess
import sys

GIT = r"C:\Program Files\Git\cmd\git.exe"
KSR = r"C:\Users\User\Desktop\Cursor Projects\Wii Projects\KobiiSports Resort\CursorProjects"
WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
OC = r"C:\Users\User\Apps\recon_work\match_accel_factory\census\OPPORTUNITY_CENSUS.jsonl"
L0 = r"C:\Users\User\Apps\recon_work\decomp_factory\corpus\main_L0.jsonl"
LEVELS = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\levels.jsonl"
M0_MD = ".ksr_vault/frontier/island_hopper/M0_CLOSURE_CENSUS.md"
M0_JSON = ".ksr_vault/frontier/island_hopper/M0_closure.json"
LO, HI = 0x8042529C, 0x80455FF0
SHARED = {0x8043141C, 0x80437F4C}
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "P5-DOSSIER.md")


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_show(spec):
    r = subprocess.run([GIT, "-C", KSR, "show", spec], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.returncode != 0:
        raise RuntimeError("git show %s failed: %s" % (spec, r.stderr.strip()))
    return r.stdout


def jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(ln) for ln in f if ln.strip()]


def addr(row):
    return int((row.get("id") or "x:0").split(":")[1], 16)


def short(obj, n=600):
    s = json.dumps(obj, ensure_ascii=False, sort_keys=True)
    return s if len(s) <= n else s[:n] + " ...<truncated>"


def section(lines, start, stop):
    out, on = [], False
    for ln in lines:
        if ln.startswith(start):
            on = True
        elif on and ln.startswith(stop):
            break
        if on:
            out.append(ln)
    return out


def main():
    out = ["# P5b dossier (zero-model, generated by build_p5_dossier.py)", "",
           "Everything below is copied or computed from a named source. Do not re-read these sources; read this file.", "",
           "## Inputs (sha256)"]
    for p in (OC, L0, LEVELS):
        out.append("- `%s` sha256 `%s`" % (p, sha(p)))
    out.append("- `%s` and `%s`: committed at KSR `aa1d82c`; ABSENT on disk in the recon work tree. Read with "
               "`git -C \"%s\" show aa1d82c:<path>` (KSR main checkout)." % (M0_MD, M0_JSON, KSR))

    oc, l0 = jsonl(OC), jsonl(L0)
    reg = [r for r in oc if LO <= addr(r) < HI]
    pln = [r for r in reg if addr(r) not in SHARED]
    out += ["", "## M0 recipe, VERIFIED live by this builder",
            "region = OPPORTUNITY_CENSUS rows with LO <= int(id.split(':')[1],16) < HI, LO=0x8042529C HI=0x80455FF0;",
            "Pln-specific = region minus the 2 shared inline helpers 0x8043141C, 0x80437F4C.",
            "- census rows %d | region %d | Pln-specific %d" % (len(oc), len(reg), len(pln)),
            "- buckets (Pln): %s" % dict(collections.Counter(r["bucket"] for r in pln).most_common()),
            "- blockers (Pln): %s" % dict(collections.Counter(b for r in pln for b in r.get("blockers", [])).most_common()),
            "- M0 expects buckets 541/302/148/115/25 and blockers CLASS_UNPROBED 588, SDA 330, CXX 94, JUMPTABLE 2."]

    out += ["", "## OPPORTUNITY_CENSUS schema (%d rows)" % len(oc), "- example row: " + short(oc[0])]
    keys = collections.Counter(k for r in oc for k in r)
    out.append("- keys (count): %s" % dict(keys))
    for k in ("bucket", "primary", "class"):
        out.append("- %s: %s" % (k, dict(collections.Counter(r.get(k) for r in oc).most_common())))
    out.append("- families (flattened): %s" % dict(collections.Counter(f for r in oc for f in r.get("families", [])).most_common(15)))
    out.append("- blockers (all rows): %s" % dict(collections.Counter(b for r in oc for b in r.get("blockers", [])).most_common()))
    sfs = collections.Counter(min(r.get("shape_family_size", 0), 10) for r in oc)
    out.append("- shape_family_size (10 = 10+): %s" % dict(sorted(sfs.items())))

    out += ["", "## main_L0 corpus schema (%d rows)" % len(l0), "- example row: " + short(l0[0])]
    out.append("- keys (count): %s" % dict(collections.Counter(k for r in l0 for k in r)))
    ids_oc, ids_l0 = {r["id"] for r in oc}, {r["id"] for r in l0}
    out.append("- id join: census-only %d, corpus-only %d, both %d" % (len(ids_oc - ids_l0), len(ids_l0 - ids_oc), len(ids_oc & ids_l0)))

    lv = jsonl(LEVELS)
    out += ["", "## levels.jsonl schema (%d rows)" % len(lv), "- example row: " + short(lv[0], 900)]

    m0 = json.loads(git_show("aa1d82c:" + M0_JSON))
    rows = m0 if isinstance(m0, list) else next((v for v in m0.values() if isinstance(v, list)), [])
    out += ["", "## M0_closure.json (aa1d82c)", "- top-level type: %s; top keys: %s" % (
        type(m0).__name__, list(m0)[:20] if isinstance(m0, dict) else "-"), "- rows: %d" % len(rows)]
    if rows:
        out.append("- example row: " + short(rows[0]))
        out.append("- row keys (count): %s" % dict(collections.Counter(k for r in rows for k in r)))
        if any("depth" in r for r in rows):
            out.append("- depth: %s" % dict(collections.Counter(r.get("depth") for r in rows).most_common()))

    md = git_show("aa1d82c:" + M0_MD).splitlines()
    out += ["", "## M0_CLOSURE_CENSUS.md lines 1-40 (verbatim)"] + md[:40]
    out += ["", "## M0_CLOSURE_CENSUS.md caveats + method (verbatim)"] + section(md, "## Caveats", "## NEXT") + md[-4:]

    rm = open(os.path.join(WT, ".planning", "workstreams", "recon-factory", "ROADMAP.md"), encoding="utf-8").read().splitlines()
    out += ["", "## ROADMAP Phase 5 (verbatim)"] + section(rm, "### Phase 5:", "### Phase 6:")
    out += ["", "## GAP-3 status (ROADMAP)"] + [ln for ln in rm if ln.startswith("| GAP-3")]
    core = os.path.join(WT, "tools", "wros", "binary", "decomp")
    out += ["", "## Canonical core modules (tools/wros/binary/decomp, GAP-3 port: import ONLY from here)",
            ", ".join(sorted(f for f in os.listdir(core) if f.endswith(".py")))]
    full = os.path.join(WT, "tools", "wros", "full")
    out += ["", "## tools/wros/full (where closure_census.py goes; mirror an existing module's style)",
            ", ".join(sorted(f for f in os.listdir(full) if f.endswith(".py")))]
    head = open(os.path.join(full, "resource_census.py"), encoding="utf-8").read().splitlines()[:25]
    out += ["", "### resource_census.py first 25 lines (style reference)", "```python"] + head + ["```"]

    body = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    ok = len(pln) == 1131 and collections.Counter(r["bucket"] for r in pln)["DIRECT_SEARCH"] == 541
    print("P5-DOSSIER %s chars=%d est_tokens=%d M0_reproduced=%s" % (OUT, len(body), len(body) // 4, ok))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
