"""Zero-model dossier for the P3a lease (recon-factory Phase 3a: verified SRC bundle seam + donor intake dry-run).

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_p3a_dossier.py
Writes P3A-DOSSIER.md next to this file. The worker edits levels.py, so the dossier carries the exact source of every
function it touches or calls, extracted by AST (never paraphrased), plus the real row shapes of the registry, the donors
file and the match-accel ledger, and seam policy v1 stated once.
"""
import ast
import collections
import hashlib
import json
import os
import sys

WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
DECOMP = os.path.join(WT, "tools", "wros", "binary", "decomp")
LEVELS_PY = os.path.join(DECOMP, "levels.py")
REGISTRY = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\evidence\src_registry.json"
LEVELS = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\levels.jsonl"
DONORS = r"C:\Users\User\Apps\recon_work\match_accel_factory\donors\DONORS.jsonl"
LEDGER = r"C:\Users\User\Apps\recon_work\match_accel_factory\ledger.jsonl"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "P3A-DOSSIER.md")

FUNCS = ("_result", "_refused", "_unknown", "canonical", "check_src", "_call_checker", "_xform_backed_independently",
         "compute_row", "promote", "seed_src", "load_store")
STORE_METHODS = ("__init__", "_load_src_registry", "_load_xform_bundles", "xform_bundle_sha", "src_entry", "src_text",
                 "words", "fingerprint")


def sha(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(ln) for ln in f if ln.strip()]


def extract(src, tree):
    lines = src.splitlines()
    got = {}
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in FUNCS:
            got[node.name] = (node.lineno, lines[node.lineno - 1:node.end_lineno])
        if isinstance(node, ast.ClassDef) and node.name == "Store":
            for m in node.body:
                if isinstance(m, ast.FunctionDef) and m.name in STORE_METHODS:
                    got["Store." + m.name] = (m.lineno, lines[m.lineno - 1:m.end_lineno])
                elif isinstance(m, ast.Assign):
                    got["Store.<class attrs>"] = (node.lineno, lines[node.lineno - 1:m.end_lineno])
        if isinstance(node, ast.Assign) and any(getattr(t, "id", "") in ("CHECKS", "SECTION1") for t in node.targets):
            name = node.targets[0].id
            body = lines[node.lineno - 1:node.end_lineno]
            got[name] = (node.lineno, body if len(body) <= 40 else body[:40] + ["    ... <truncated>"])
    return got


def main():
    src = open(LEVELS_PY, encoding="utf-8").read()
    got = extract(src, ast.parse(src))
    missing = [n for n in FUNCS if n not in got] + ["Store." + m for m in STORE_METHODS if "Store." + m not in got]
    reg = json.load(open(REGISTRY, encoding="utf-8"))
    lv = {r["id"]: r for r in jsonl(LEVELS)}
    proven = [i for i, r in lv.items() if r["dimensions"]["SRC"]["verdict"] == "PROVEN"]
    donors, ledger = jsonl(DONORS), jsonl(LEDGER)
    by_seq = {r["seq"]: r for r in ledger}
    match = [d for d in donors if d.get("best") == "MATCH"]
    sha_ok = sum(1 for d in match if any(by_seq.get(s, {}).get("source_sha256")
                                         == hashlib.sha256(d["source"].encode("utf-8")).hexdigest() for s in d["seqs"]))
    reg_ids = {r["id"] for r in reg["rows"]}
    src_lines = src.splitlines()

    out = ["# P3a dossier (zero-model, generated by build_p3a_dossier.py)", "",
           "Everything below is copied or computed from a named source. Read this file only.", "", "## Inputs (sha256)"]
    for p in (LEVELS_PY, REGISTRY, LEVELS, DONORS, LEDGER):
        out.append("- `%s` sha256 `%s`" % (p, sha(p)))
    rm = open(os.path.join(WT, ".planning", "workstreams", "recon-factory", "ROADMAP.md"), encoding="utf-8").read().splitlines()
    i = next(n for n, ln in enumerate(rm) if ln.startswith("### Phase 3:"))
    out += ["", "## ROADMAP Phase 3 (verbatim; 3a = GAP-2 seam + GAP-6 intake + GAP-12; bulk promotion is 3b, POST_CP50)"]
    out += [ln for ln in rm[i:i + 6]] + [ln for ln in rm[i:i + 17] if any(g in ln for g in ("GAP-2 ", "GAP-6 ", "GAP-8 ", "GAP-12 "))]

    out += ["", "## Facts that shape 3a",
            "- check_src compiles LOCALLY (X.run + _run_objdiff). Zero local compiles is a hard constraint, so a factory SRC"
            " verdict must come from a GEX44 bundle verified inside levels.py (GAP-2). The GAP-1 GEX44 runner does not exist"
            " yet: NO real bundle exists. 3a builds and drills the seam; no real promotion happens.",
            "- levels.jsonl: %d rows, SRC PROVEN %d: %s. Registry ids: %s." % (len(lv), len(proven), proven, sorted(reg_ids)),
            "- The pinned compiler sha256 as recorded by a PROVEN row: %s." % lv[proven[0]]["dimensions"]["SRC"]["evidence"]["compiler_sha256"],
            "- seed_src (below) refuses any registry other than its own 5 seeds, so GAP-6's 'existing writer' cannot add donors;"
            " and inputs_for() fingerprints src_registry into every row that has an src_entry, so ANY registry write changes"
            " the 5 PROVEN rows' inputs (revalidate would mark them). The registry WRITE is therefore NOT in 3a: intake is a"
            " dry-run report; the write is decided in 3b.",
            "- promote() refuses below 2,048 MB free (HOST_FLOOR_BREACHED) and this host runs near 1.6 GB: drill the seam's"
            " factored functions directly, never through promote().",
            "- DONORS.jsonl: %d rows, best=MATCH %d; keys %s. Donor source sha256 equals a ledger row's source_sha256 (via"
            " seqs) for %d of the MATCH donors." % (len(donors), len(match), sorted(donors[0]), sha_ok),
            "- ledger.jsonl (match-accel): %d rows; keys %s; oracle example %s; command[0] example %s (a LOCAL laptop"
            " compile, not GEX44)." % (len(ledger), sorted(ledger[0]), json.dumps(ledger[0]["oracle"]), ledger[0]["command"][0]),
            "- src_registry.json schema %r, row example %s" % (reg["schema"], json.dumps(reg["rows"][0])),
            "- levels.py constants (verbatim lines 57-66):"]
    out += ["```python"] + src_lines[56:66] + ["```"]

    out += ["", "## Seam policy v1 (implement exactly this)",
            "1. SRC_BUNDLES = os.path.join(EVIDENCE_DIR, 'src_bundles'); one file <id with ':' replaced by '_'>.json; add"
            " 'src_bundles' to Store paths (default SRC_BUNDLES, overridable like xform_bundles) and a Store.src_bundle(eid)"
            " that returns (parsed dict, file sha256) or None.",
            "2. Bundle schema 'ksr.decomp.src_bundle/1', keys: schema, id, src_sha256, preset, compiler_sha256,"
            " target_words_sha256 (= sha256 of canonical(store.words(id))), match_py {verdict, reloc_verified},"
            " objdiff_percent, oracle_disagreement, host_plane, runner {job_key, job_id}, produced_utc.",
            "3. verify_src_bundle(eid, store, bundle) -> list of refusal tokens (empty = verified), checked in this order:"
            " BUNDLE_SCHEMA (schema or any key missing), BUNDLE_ID (bundle id != eid), SRC_NOT_REGISTERED (no src_entry),"
            " SRC_SHA_MISMATCH (bundle src_sha256 != the entry's source_sha256, or store.src_text(eid) is None),"
            " COMPILER_MISMATCH (!= PINNED_COMPILER_SHA256, a new constant = the sha256 in Facts), TARGET_MISMATCH"
            " (target_words_sha256 != the recomputed one: a swapped object fails here), MATCH_PY_NOT_MATCH,"
            " OBJDIFF_NOT_100, ORACLE_DISAGREEMENT (flag true, or MATCH with objdiff != 100), PLANE_NOT_GEX44"
            " (host_plane != 'GEX44').",
            "4. check_src: when store.src_bundle(eid) exists, decide from the bundle ONLY (never X.run, never objdiff):"
            " verified -> backed source_registered, compiler_pinned, match_py_MATCH, objdiff_100 and evidence {bundle_sha256,"
            " match_py, objdiff_percent, compiler_sha256, src_sha256, oracle_disagreement, host_plane}; not verified ->"
            " _unknown(cl, ['SRC_BUNDLE_REFUSED ' + first token], {'bundle': tokens}). Without a bundle: the existing path,"
            " byte-for-byte unchanged.",
            "5. _src_unbacked(computed, store, checks) -> sorted ids: rows whose SRC verdict is PROVEN while checks overrides"
            " 'SRC', and which are NOT backed independently (a bundle exists, verifies, and canonical(SRC dim) equals"
            " canonical(check_src(eid, store, {}) via the bundle path)). promote() raises Refused('SRC_UNBACKED ' + first)"
            " right after the XFORM_UNBACKED check, before anything is written. A bare checks['SRC'] lambda is thereby refused.",
            "6. GAP-12: promote() adds to the manifest 'ledger_sha256_before' (sha256 of the ledger file bytes before the"
            " write, None when absent) and 'promoted_id_list' (sorted ids). levels.jsonl schema /1 unchanged.",
            "7. src_intake(donors=DONORS, ledger=LEDGER, store=None) -> report, DRY-RUN, writes nothing: for each MATCH donor,"
            " would_register {id, name, source_sha256, preset=best_preset, origin 'match_accel donors seqs ...'} or"
            " refused_at_intake with one token: NOT_IN_CENSUS, SOURCE_SHA_UNBACKED (no ledger seq with that source_sha256"
            " and verdict MATCH), ALREADY_REGISTERED_DIFFERENT. Report counts registered vs refused by token.",
            "",
            "## Expected intake (computed live by this builder -- the drill's oracle)",
            "- MATCH donors %d; source sha backed by a ledger row %d; already in registry %d"
            % (len(match), sha_ok, len([d for d in match if d["donor_id"] in reg_ids])),
            "", "## levels.py source the seam touches or calls (verbatim, AST-extracted; line numbers as of the sha above)"]
    for name in list(FUNCS) + ["Store.<class attrs>"] + ["Store." + m for m in STORE_METHODS] + ["CHECKS", "SECTION1"]:
        if name in got:
            ln, body = got[name]
            out += ["", "### %s (line %d)" % (name, ln), "```python"] + body + ["```"]
    out += ["", "Not found by the extractor: %s" % (missing or "none")]

    body = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("P3A-DOSSIER chars=%d est_tokens=%d proven=%d match_donors=%d sha_backed=%d missing=%s"
          % (len(body), len(body) // 4, len(proven), len(match), sha_ok, missing))
    return 0 if not missing else 1


if __name__ == "__main__":
    sys.exit(main())
