"""Zero-model dossier for the P6 lease (recon-factory Phase 6: router, S3).

Run: python vault/programs/cognitive-economy/gen3/recon-reforecast/build_p6_dossier.py
Writes P6-DOSSIER.md next to this file. Same grammar as build_p5_dossier.py: every premise the worker needs is pinned
here (input sha256, the census bucket and blocker rules in their own words, the admission / workunit APIs it calls,
the ROADMAP criteria) and the router policy v1 is stated once with its expected histogram computed live, so the worker's
drill has an oracle it did not write.
"""
import collections
import hashlib
import json
import os
import sys

WT = r"C:\Users\User\Apps\recon_work\wt_keosdtk_home"
KSR = r"C:\Users\User\Desktop\Cursor Projects\Wii Projects\KobiiSports Resort\CursorProjects"
OC = r"C:\Users\User\Apps\recon_work\match_accel_factory\census\OPPORTUNITY_CENSUS.jsonl"
OCS = r"C:\Users\User\Apps\recon_work\match_accel_factory\census\OPPORTUNITY_CENSUS_SUMMARY.json"
LEVELS = r"C:\Users\User\Apps\recon_work\decomp_factory\levels\levels.jsonl"
WU_LOG = r"C:\Users\User\Apps\recon_work\decomp_factory\workunits\wu.jsonl"
DECOMP = os.path.join(WT, "tools", "wros", "binary", "decomp")
PLAN = os.path.join(KSR, ".ksr_vault", "frontier", "KEOS_RECON_FACTORY_PLAN.md")
LO, HI = 0x8042529C, 0x80455FF0
SHARED = {0x8043141C, 0x80437F4C}
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "P6-DOSSIER.md")

# Router policy v1 -- the single statement of it; the packet and the worker's module both cite this table.
HARD_BLOCKERS = ("FLAGS_BLOCKED_SDA", "FLAGS_BLOCKED_CXX", "TOOLCHAIN_UNPROBED_LIBRARY", "JUMPTABLE")
BASE_TIER = {"TRIVIAL_DETERMINISTIC": "DET", "LIBRARY_SIGNATURE": "DET", "CHEAP_SEARCH": "DET",
             "DIRECT_SEARCH": "DET", "FAMILY_PROPAGATABLE": "FAMILY", "FRONTIER_MODEL_CANDIDATE": "LOCAL"}
LADDER = ("DET", "FAMILY", "LOCAL", "PAID")
TIER_BUDGET = {"DET": 3, "FAMILY": 2, "LOCAL": 2, "PAID": 1}
PAID_CAP = 84
FLOOR_MB = 2048


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def jsonl(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(ln) for ln in f if ln.strip()]


def addr(row_id):
    return int(row_id.split(":")[1], 16)


def lines_of(path, start, stop):
    with open(path, encoding="utf-8") as f:
        return f.read().splitlines()[start - 1:stop]


def expected(rows, l3, donor_shapes, free_mb):
    """Policy v1 with no WU log (no attempt evidence): the oracle the worker's drill must reproduce exactly."""
    out = collections.Counter()
    for r in rows:
        if l3.get(r["id"]):
            out["DONE"] += 1
            continue
        hard = [b for b in HARD_BLOCKERS if b in r["blockers"]]
        if hard:
            out["BLOCKED_TOOLCHAIN"] += 1
            continue
        if r["bucket"] == "NOT_WORTH_MATCHING_YET":
            out["DEFERRED"] += 1
            continue
        tier = BASE_TIER[r["bucket"]]
        if tier == "FAMILY" and r["shape_id"] not in donor_shapes:
            tier = "DET"
        if tier == "LOCAL" and free_mb < FLOOR_MB:
            out["HELD_ADMISSION"] += 1
            continue
        out[tier] += 1
    return dict(sorted(out.items()))


def main():
    oc, lv = jsonl(OC), jsonl(LEVELS)
    l3 = {r["id"]: bool(r["levels"].get("L3")) for r in lv}
    donor_shapes = {r["shape_id"] for r in oc if l3.get(r["id"])}
    pln = [r for r in oc if LO <= addr(r["id"]) < HI and addr(r["id"]) not in SHARED]
    summ = json.load(open(OCS, encoding="utf-8"))

    out = ["# P6 dossier (zero-model, generated by build_p6_dossier.py)", "",
           "Everything below is copied or computed from a named source. Read this file only.", "", "## Inputs (sha256)"]
    for p in (OC, OCS, LEVELS):
        out.append("- `%s` sha256 `%s`" % (p, sha(p)))
    out.append("- WU log `%s`: %s. With no log there is NO attempt evidence: every row routes from its census row."
               % (WU_LOG, "PRESENT %d bytes" % os.path.getsize(WU_LOG) if os.path.isfile(WU_LOG) else "ABSENT"))

    out += ["", "## Census bucket rules (verbatim from OPPORTUNITY_CENSUS_SUMMARY.json `rules`, first match wins)"]
    out += ["- %s: %s" % (k, v) for k, v in summ["rules"]]
    out += ["", "## Census blocker rules (verbatim, `blocker_rules`)"] + ["- %s: %s" % (k, v) for k, v in summ["blocker_rules"]]
    out += ["", "## Census row keys (all 34,159 rows carry all of them)",
            "asm_unit, bctr, bctrl, bl, blockers (list), blr, bucket, class, corpus_insns, families (list), fp, frame, ha_lo,"
            " id (\"main:XXXXXXXX\"), insns, jumptable, labels, name, paired_single, primary, savegpr, sda21,"
            " shape_family_size, shape_id, size, tail_b, unit"]
    out += ["", "## levels.jsonl (34,159 rows)",
            "- row keys: %s" % sorted(lv[0]), "- `levels` field example: %s" % json.dumps(lv[0]["levels"]),
            "- L3 true (MATCH promoted) rows: %d total, %d in Pln; donor shape_ids (shape of an L3 row): %d"
            % (sum(l3.values()), sum(1 for r in pln if l3.get(r["id"])), len(donor_shapes))]

    adm = os.path.join(DECOMP, "admission.py")
    out += ["", "## admission.py API (decomp core, GAP-3 port; verbatim lines 20-24 and 47-52)", "```python"]
    out += lines_of(adm, 20, 24) + ["..."] + lines_of(adm, 47, 52) + ["```"]
    wu = os.path.join(DECOMP, "workunit.py")
    out += ["", "## workunit.py derive() shape (verbatim; decomp modules import siblings as `import admission as A`)",
            "```python"] + lines_of(wu, 53, 57) + ["..."] + lines_of(wu, 317, 327) + ["..."] + lines_of(wu, 334, 352)
    out += ["```", "Unit snapshot fields (from the OPENED reducer): binary_sha256, function_addr, state, opened_utc, attempts,"
            " last_tx_seq, last_level, route, blocked_cause, cost{compiles,tokens_local,tokens_paid,wall_s_by_plane,"
            "tier{TIER: n}}, open_lease. Key = \"<binary_sha256>:0x%08X\"."]
    tx = os.path.join(DECOMP, "transaction.py")
    out += ["", "## transaction.py tier constants (verbatim)", "```python"] + lines_of(tx, 45, 49) + lines_of(tx, 150, 150) + ["```"]

    rm = open(os.path.join(WT, ".planning", "workstreams", "recon-factory", "ROADMAP.md"), encoding="utf-8").read().splitlines()
    i = next(n for n, ln in enumerate(rm) if ln.startswith("### Phase 6:"))
    out += ["", "## ROADMAP Phase 6 (verbatim)"] + rm[i:i + 7]
    out += ["", "## ROADMAP constraints (verbatim)"] + [ln for ln in rm if ln.startswith(("- PAID model", "- <= 2 concurrent", "- **Zero local"))]
    pl = open(PLAN, encoding="utf-8").read().splitlines()
    out += ["", "## KEOS_RECON_FACTORY_PLAN.md (KSR main checkout) D3, S3, sections 8 and 14 (verbatim)"]
    out += [ln for ln in pl if ln.startswith(("| D3 ", "| S3 "))] + pl[81:88] + pl[113:115]

    names = sorted(f for f in os.listdir(DECOMP) if f.endswith(".py"))
    out += ["", "## decomp core files (router.py and test_router.py do NOT exist yet)", ", ".join(names)]

    e_pln = expected(pln, l3, donor_shapes, 4096)
    e_all = expected(oc, l3, donor_shapes, 4096)
    e_low = expected(oc, l3, donor_shapes, FLOOR_MB - 1)
    hard_pln = sum(1 for r in pln if any(b in r["blockers"] for b in HARD_BLOCKERS))
    out += ["", "## Router policy v1 (the Owner-facing statement; implement exactly this)",
            "Per census row, first rule that fires:",
            "1. levels L3 true -> DONE (no tier).",
            "2. WU unit state BLOCKED -> BLOCKED_WU:<blocked_cause>; WU last_level L3 -> DONE.",
            "3. any hard blocker in fixed order %s -> BLOCKED_TOOLCHAIN:<first one>. The pinned presets cannot compile"
            " these, so no tier can produce a MATCH. CLASS_UNPROBED is NOT hard: the row routes and carries"
            " class_probe=True." % (HARD_BLOCKERS,),
            "4. bucket NOT_WORTH_MATCHING_YET -> DEFERRED.",
            "5. base tier = %s. FAMILY only when the row's shape_id is a donor shape (some row with that shape_id is"
            " L3); otherwise DET." % json.dumps(BASE_TIER),
            "6. escalation (only with WU evidence): while unit.cost.tier[tier] >= TIER_BUDGET[tier] move to the next tier"
            " of %s; TIER_BUDGET = %s; past PAID -> BLOCKED_EXHAUSTED. Without a WU log no row escalates, so a"
            " DET/FAMILY base never reaches LOCAL/PAID." % (LADDER, json.dumps(TIER_BUDGET)),
            "7. LOCAL needs admission.admit('compile', reading)['verdict'] == 'ADMIT' (floor %d MB); otherwise"
            " HELD_ADMISSION. Low RAM never pushes a row up to PAID." % FLOOR_MB,
            "8. PAID needs paid_used < %d, where paid_used = sum of cost.tier['PAID'] over all WU units + PAID routes"
            " already issued in this run (escalations, GAP-13); otherwise HELD_PAID_CAP. Report distinct functions"
            " routed PAID separately." % PAID_CAP,
            "", "## Expected histograms, policy v1, no WU log (computed live by this builder -- the drill's oracle)",
            "- Pln 1,131 rows, free_mb=4096: %s" % e_pln,
            "- Pln rows with a hard blocker (independent count): %d" % hard_pln,
            "- full 34,159 rows, free_mb=4096: %s" % e_all,
            "- full 34,159 rows, free_mb=%d (below floor): %s" % (FLOOR_MB - 1, e_low)]

    body = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    ok = len(pln) == 1131 and sum(e_pln.values()) == 1131 and sum(e_all.values()) == len(oc) == 34159
    print("P6-DOSSIER %s chars=%d est_tokens=%d pln=%s all=%s low=%s ok=%s"
          % (OUT, len(body), len(body) // 4, e_pln, e_all, e_low, ok))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
