#!/usr/bin/env python3
"""ADS doc generator (D2).

Builds the four documents for a module from REAL source:
  * PRD          -- tier-aware (composes prd_generator.generate_prd for the
                    tier + section skeleton; AUTO content is code-derived,
                    NOT the render_prd "<...>" scaffold -- audit note).
  * Arch Spec    -- components, public interface, dependencies, metrics.
  * Constitution -- the module's behavioural contract (public API surface
                    as the invariant the Owner promises to keep stable).
  * Changelog    -- append-only dated entries (AUTO block).

Every doc has exactly one AUTO marker pair (code-derived, regenerated by
the updater) and one OWNER marker pair (Owner-authored, never touched).
The ADS source carries ZERO slop-token literals (audit gap #9) so the
Stop-chain scaffold-auditor cannot quine-trip on it.

stdlib-only. Public API: build_docs, write_docs, DOC_TYPES, markers.
"""
from __future__ import annotations

import ast
import sys
from dataclasses import dataclass, field as dc_field
from datetime import datetime, timezone
from pathlib import Path

_PP_ROOT = Path(__file__).resolve().parents[2]
if str(_PP_ROOT) not in sys.path:
    sys.path.insert(0, str(_PP_ROOT))

from modules.ads.detector import _PKG_MARKERS, module_slug
from modules.sdd_os.prd_generator import generate_prd
from modules.setup_os.scanner import _LANG_EXT

DOC_TYPES = ("prd", "arch", "constitution", "changelog")

AUTO_OPEN = "<!-- ADS:AUTO -->"
AUTO_CLOSE = "<!-- /ADS:AUTO -->"
OWNER_OPEN = "<!-- ADS:OWNER -->"
OWNER_CLOSE = "<!-- /ADS:OWNER -->"

_AUTO_NOTE = ("_Auto-generated from source by ADS. This block is "
              "regenerated on change; edits here are overwritten._")
_OWNER_NOTE = ("_Owner-authored. ADS never modifies this block._")


# --- interface extraction ------------------------------------------------

@dataclass
class _Symbol:
    name: str
    kind: str          # "function" | "class"
    signature: str
    file: str


@dataclass
class _Interface:
    symbols: list[_Symbol] = dc_field(default_factory=list)
    imports: list[str] = dc_field(default_factory=list)
    files: list[str] = dc_field(default_factory=list)
    loc: int = 0
    docstring: str | None = None


def _is_package(repo: Path, key: str) -> bool:
    target = repo / key
    return target.is_dir() and any((target / m).exists() for m in _PKG_MARKERS)


def _module_files(repo: Path, key: str, is_pkg: bool) -> list[Path]:
    target = repo / key
    if is_pkg and target.is_dir():
        return sorted(f for f in target.rglob("*")
                      if f.is_file() and f.suffix in _LANG_EXT
                      and "__pycache__" not in f.parts)
    if target.is_file():
        return [target]
    return []


def _py_signature(node: ast.AST) -> str:
    try:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            return f"{node.name}({ast.unparse(node.args)})"
        if isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(b) for b in node.bases)
            return f"{node.name}({bases})" if bases else node.name
    except Exception:
        pass
    return getattr(node, "name", "?")


def _extract_python(path: Path, rel: str, iface: _Interface) -> None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except (OSError, SyntaxError):
        return
    if iface.docstring is None:
        iface.docstring = ast.get_docstring(tree)
    for node in tree.body:        # top-level only -> public surface
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef,
                             ast.ClassDef)):
            if node.name.startswith("_"):
                continue
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            iface.symbols.append(_Symbol(
                node.name, kind, _py_signature(node), rel))
        elif isinstance(node, ast.Import):
            for a in node.names:
                iface.imports.append(a.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module:
            iface.imports.append(node.module.split(".")[0])


def _extract_generic(path: Path, rel: str, iface: _Interface) -> None:
    """Lightweight export scan for non-Python source (JS/TS/etc.)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("export ") and ("function" in s or "class" in s
                                         or "const" in s):
            iface.symbols.append(_Symbol(
                s[:80], "export", s[:80], rel))


def _collect_interface(repo: Path, key: str, is_pkg: bool) -> _Interface:
    iface = _Interface()
    for f in _module_files(repo, key, is_pkg):
        rel = f.relative_to(repo).as_posix()
        iface.files.append(rel)
        try:
            iface.loc += sum(1 for _ in f.open("rb"))
        except OSError:
            pass
        if f.suffix == ".py":
            _extract_python(f, rel, iface)
        else:
            _extract_generic(f, rel, iface)
    # de-dup imports, drop self/relative
    seen: list[str] = []
    for imp in iface.imports:
        if imp and imp not in seen and imp != "modules":
            seen.append(imp)
    iface.imports = seen
    return iface


# --- doc assembly --------------------------------------------------------

def _block(open_m: str, close_m: str, note: str, lines: list[str]) -> str:
    return "\n".join([open_m, note, "", *lines, close_m])


def _iface_lines(iface: _Interface) -> list[str]:
    out: list[str] = []
    out.append(f"**Files:** {len(iface.files)}  ·  "
               f"**LOC:** {iface.loc}  ·  "
               f"**Public symbols:** {len(iface.symbols)}")
    out.append("")
    out.append("### Public interface")
    if iface.symbols:
        for s in iface.symbols:
            out.append(f"- `{s.signature}` ({s.kind}, `{s.file}`)")
    else:
        out.append("- (no public symbols detected)")
    out.append("")
    out.append("### Dependencies")
    if iface.imports:
        out.append(", ".join(f"`{i}`" for i in iface.imports))
    else:
        out.append("(none external)")
    return out


def _owner_lines(prompts: list[str]) -> list[str]:
    # Neutral fill-in prose -- no slop-token literals (audit gap #9).
    return [f"- {p}: _(Owner-defined; fill in during planning.)_"
            for p in prompts]


def _assemble(title: str, key: str, auto_lines: list[str],
              owner_prompts: list[str]) -> str:
    return "\n".join([
        f"# {title} -- `{key}`",
        "",
        _block(AUTO_OPEN, AUTO_CLOSE, _AUTO_NOTE, auto_lines),
        "",
        _block(OWNER_OPEN, OWNER_CLOSE, _OWNER_NOTE,
               _owner_lines(owner_prompts)),
        "",
    ])


def _now_str(now: str | None) -> str:
    if now:
        return now
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_docs(key: str, repo: str | Path, now: str | None = None,
               is_package: bool | None = None) -> dict[str, str]:
    """Return {doc_type: markdown} for a module. Pure (no writes)."""
    repo = Path(repo).resolve()
    is_pkg = _is_package(repo, key) if is_package is None else is_package
    iface = _collect_interface(repo, key, is_pkg)
    prd = generate_prd(key)        # tier + section skeleton (compose, #SCS C28)
    ts = _now_str(now)

    auto = _iface_lines(iface)
    if iface.docstring:
        summary = iface.docstring.strip().splitlines()[0]
        auto = [f"> {summary}", ""] + auto

    docs: dict[str, str] = {}

    # PRD -- tier-aware: AUTO carries interface; OWNER carries the strategic
    # sections from the matched tier template.
    prd_owner = [f"{sec.title}" for sec in prd.sections][:8] or ["Objective"]
    docs["prd"] = _assemble(
        f"PRD (Tier {prd.tier} -- {prd.tier_name})", key, auto, prd_owner)

    # Arch Spec
    arch_auto = auto + ["", "### Module type",
                        f"- {'package' if is_pkg else 'single-file module'}"]
    docs["arch"] = _assemble(
        "Architecture Spec", key, arch_auto,
        ["Design decisions", "Tradeoffs", "What this module does NOT do"])

    # Constitution -- the public API is the invariant contract.
    const_auto = ["The following public surface is the module's behavioural "
                  "contract. Removing or breaking any of it is a breaking "
                  "change.", ""] + (
        [f"- `{s.signature}`" for s in iface.symbols]
        or ["- (no public surface yet)"])
    docs["constitution"] = _assemble(
        "Constitution", key, const_auto,
        ["Invariants that must never change", "Hard rules specific to this module",
         "What breaks downstream if violated"])

    # Changelog -- AUTO block is the running entry list (append-only).
    cl_auto = [f"- {ts} — created ({iface.loc} LOC, "
               f"{len(iface.symbols)} public symbols)"]
    docs["changelog"] = _assemble("Changelog", key, cl_auto, ["Notes"])

    return docs


def write_docs(key: str, repo: str | Path, now: str | None = None,
               is_package: bool | None = None) -> dict[str, Path]:
    """Build and WRITE the four docs under repo/docs/<type>/<slug>.md."""
    repo = Path(repo).resolve()
    docs = build_docs(key, repo, now, is_package)
    slug = module_slug(key)
    paths: dict[str, Path] = {}
    for doc_type, content in docs.items():
        out_dir = repo / "docs" / doc_type
        out_dir.mkdir(parents=True, exist_ok=True)
        out = out_dir / f"{slug}.md"
        out.write_text(content, encoding="utf-8")
        paths[doc_type] = out
    return paths


__all__ = [
    "DOC_TYPES", "AUTO_OPEN", "AUTO_CLOSE", "OWNER_OPEN", "OWNER_CLOSE",
    "build_docs", "write_docs",
]
