#!/usr/bin/env python3
"""SDD-OS pre-execution gate -- closes RC-3 (BL-SDD-ACT-001).

"Spec First. Execution Second. Validation Always." (Dataset SDD-OS 1,
PARTE I sec. 1). PARTE I sec. 4 is explicit: for a task that trips a PRD
trigger, "ejecutar sin PRD queda prohibido".

The prior surface was a one-sentence advisory sitting at slot 10 of 13
behind a 3-advisory cap, which produced nothing and -- per its own
throttle records -- never fired outside tests. This gate is different in
two ways that matter:

  1. It is PROPORTIONAL. Tier 0 gets a three-line inline mini-spec; only
     Tier 2+ requires a written artifact. A gate that demands a full PRD
     to fix a typo gets disabled by the human within a day, and a
     disabled gate governs nothing.
  2. It GENERATES. When a Tier 2+ task has no bound spec, it writes the
     spec skeleton -- with a `covers` declaration so the task actually
     binds (OD-1) -- instead of asking the agent to remember to.

Non-destructive by contract: an existing file is never overwritten.
Stdlib only, cwd-relative, no hardcoded paths (E11).
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

PP_ROOT = Path(__file__).resolve().parents[2]
if str(PP_ROOT) not in sys.path:
    sys.path.insert(0, str(PP_ROOT))

from modules.sdd_os.spec_binding import (  # noqa: E402
    SpecBinding, find_bound_spec, infer_covers,
)

TIER_LABEL: dict[int, str] = {
    0: "Micro Task",
    1: "Standard Task",
    2: "Feature / System Task",
    3: "Strategic / Platform Task",
}

# Where a generated spec lands, in order of preference. The first
# directory that already exists in the repo wins, so the gate adopts the
# repo's own convention instead of imposing one. Falls back to the first
# entry when the repo has none of them.
SPEC_DIR_PREFERENCE: tuple[str, ...] = (
    "vault/specs", ".specify/specs", "docs/specs", "specs",
)

_SLUG_RX = re.compile(r"[^a-z0-9]+")
_MAX_SLUG_LEN = 48


@dataclass
class GateDecision:
    tier: int
    tier_label: str
    requires_written_spec: bool
    binding: SpecBinding
    action: str            # "proceed" | "inline_mini_spec" | "write_spec"
    directive: str
    spec_path: Path | None = None
    spec_written: bool = False


def slugify(text: str, max_len: int = _MAX_SLUG_LEN) -> str:
    """Filename-safe slug. Never empty -- an unnameable task still needs
    a deterministic path."""
    slug = _SLUG_RX.sub("-", (text or "").lower()).strip("-")
    if len(slug) > max_len:
        slug = slug[:max_len].rstrip("-")
    return slug or "untitled-task"


def resolve_spec_dir(cwd: Path) -> Path:
    for rel in SPEC_DIR_PREFERENCE:
        candidate = cwd / rel
        if candidate.is_dir():
            return candidate
    return cwd / SPEC_DIR_PREFERENCE[0]


def spec_path_for(task: str, cwd: Path, tier: int) -> Path:
    return resolve_spec_dir(cwd) / f"t{tier}-{slugify(task)}.md"


def _classify(task: str) -> tuple[int, str]:
    """Tier via the sealed SDD-OS classifier. Escalates under failure.

    A classifier error must not silently downgrade a Strategic task to
    Micro, so the failure default is Tier 1 (Standard) -- the same safe
    non-trivial default the dataset uses under ambiguity.
    """
    try:
        from modules.spec_gate.gate import classify_tier
        result = classify_tier(task)
        return int(result.tier), str(result.reason)
    except Exception as exc:  # classifier unavailable -> stay useful
        return 1, f"classifier unavailable ({type(exc).__name__}); default Standard"


def _mini_spec_block(task: str, tier: int, reason: str) -> str:
    return (
        f"SDD-OS Tier {tier} ({TIER_LABEL[tier]}) -- {reason}.\n"
        f"Before editing, state inline (three lines is enough):\n"
        f"  Objective  -- what observable thing is true when this is done?\n"
        f"  Scope      -- which files/behaviours are in, and which are out?\n"
        f"  Acceptance -- what check proves it, beyond 'it compiles'?"
    )


def _brief_spec_body(task: str, tier: int, covers: list[str]) -> str:
    """Tier 1 brief spec: objective, scope, AC, impact, regression risk."""
    return f"""---
title: {task.strip()[:120]}
covers: [{', '.join(covers)}]
tier: {tier}
date: {date.today().isoformat()}
status: draft
---

# Brief Spec -- {task.strip()[:120]}

SDD-OS Tier {tier} ({TIER_LABEL[tier]}). Generated by the pre-execution
gate because no existing spec declared coverage of this task.

## Objective

State the outcome in observable terms. Not "improve X" -- rather, what is
measurably true afterwards that is not true now.

## Scope

In scope:

Out of scope (guards against scope creep):

## Impact map

Which files, modules, callers, configs and docs does this touch?

## Acceptance criteria

- AC-001:
- AC-002:

## Regression risk

What could this break that currently works, and what check would catch it?

## Validation

The command whose observed output proves this works. Compilation is not
validation (PARTE I sec. 10).
"""


def _full_spec_body(task: str, tier: int, covers: list[str]) -> str:
    """Tier 2/3 spec: PRD + Architecture Spec + gates, per PARTE I 5-8."""
    strategic = ""
    if tier == 3:
        strategic = """
## Governance spec (Tier 3)

Who decides, who approves, and what authority does this create?

## Cross-repo applicability (Tier 3)

Which repos inherit this, and what must be true in each before it applies?

## Compatibility matrix and migration strategy (Tier 3)

What existing behaviour changes, and how does an in-flight repo move over?

## Kill switches (Tier 3)

Conditions under which this system must stop rather than degrade
(PARTE I sec. 6.5). At minimum: objective not understood, impact not
identifiable, result not validatable, implementation contradicts the PRD.

## Standardization rule (Tier 3)

What becomes permanent doctrine once this ships, and where is it sealed?
"""

    return f"""---
title: {task.strip()[:120]}
covers: [{', '.join(covers)}]
tier: {tier}
date: {date.today().isoformat()}
status: draft
---

# Spec -- {task.strip()[:120]}

SDD-OS Tier {tier} ({TIER_LABEL[tier]}). Generated by the pre-execution
gate because no existing spec declared coverage of this task. Per PARTE I
sec. 4, a task at this tier may not be executed without this document
completed.

## 1. Problem

Current pain, the risk of not solving it, and which errors it prevents.
A generic answer is not accepted (PARTE I sec. 5.1).

## 2. Objective

Observable, not aspirational (PARTE I sec. 5.2).

## 3. Non-goals

What is explicitly not being solved yet.

## 4. Actors

Who or what depends on this: humans, Claude Code, the Power Pack, the
target repo, CI, internal agents, future maintainers.

## 5. Functional requirements

- FR-001:
- FR-002:

## 6. Non-functional requirements

Security, robustness, speed, cost, compatibility, observability,
reversibility, cross-repo portability -- whichever apply.

- NFR-001:

## 7. Acceptance criteria

Done is defined here, or it is not defined at all.

- AC-001:
- AC-002:

## 8. Architecture spec

### 8.1 Components affected

Files, modules, services, agents, workflows, configs, docs, tests, CLI.

### 8.2 System flow

Input, decision, execution, validation, output, fallback, error handling.

### 8.3 Contracts

For each: what it receives, what it produces, what it must never
produce, what invalidates execution, and what happens on failure.

### 8.4 Failure modes

Ambiguity, missing context, absent tests, unknown architecture, broken
dependencies, partial implementation, shallow validation, drift from the
objective, false completeness.

### 8.5 Rollback plan

How this is undone if it lands wrong.

## 9. Test plan

Happy path, error paths, and the regression check.

## 10. Validation

The command whose observed output proves this works.
{strategic}
## 11. Completion gate

- Spec gate: is the task classified and the spec sufficient?
- Architecture gate: components, contracts, failure modes, rollback?
- Execution gate: does the implementation follow the spec without scope creep?
- Validation gate: real behaviour proven, not just compilation?
- Standardization gate: does anything here become a permanent rule?
"""


def evaluate(task_description: str,
             cwd: Path | str | None = None) -> GateDecision:
    """Classify the task and resolve whether a spec covers it. No writes."""
    root = Path(cwd) if cwd else Path.cwd()
    tier, reason = _classify(task_description)
    binding = find_bound_spec(task_description, root)

    if binding.bound:
        return GateDecision(
            tier=tier, tier_label=TIER_LABEL[tier],
            requires_written_spec=tier >= 2, binding=binding,
            action="proceed", spec_path=binding.spec_path,
            directive=(
                f"SDD-OS Tier {tier} ({TIER_LABEL[tier]}). Spec bound: "
                f"{binding.spec_path}. Read it before editing -- scope and "
                f"done-gate live there, not in your head."))

    if tier < 2:
        return GateDecision(
            tier=tier, tier_label=TIER_LABEL[tier],
            requires_written_spec=False, binding=binding,
            action="inline_mini_spec",
            directive=_mini_spec_block(task_description, tier, reason))

    target = spec_path_for(task_description, root, tier)
    return GateDecision(
        tier=tier, tier_label=TIER_LABEL[tier],
        requires_written_spec=True, binding=binding,
        action="write_spec", spec_path=target,
        directive=(
            f"SDD-OS Tier {tier} ({TIER_LABEL[tier]}) -- {reason}. No spec "
            f"declares coverage of this task ({binding.reason}). PARTE I "
            f"sec. 4: execution without a spec is not permitted at this "
            f"tier. Write {target.name} first, then implement against it."))


def generate_spec(task_description: str,
                  cwd: Path | str | None = None,
                  tier: int | None = None,
                  overwrite: bool = False) -> tuple[Path, bool]:
    """Write the tier-appropriate spec skeleton. Returns (path, written).

    Non-destructive: an existing file is left untouched and written=False
    is returned. The generated front matter carries a `covers` list so the
    spec binds to the task that caused it (OD-1) rather than joining the
    pile of undeclared files that created RC-2.
    """
    root = Path(cwd) if cwd else Path.cwd()
    if tier is None:
        tier, _ = _classify(task_description)
    tier = max(0, min(3, int(tier)))

    target = spec_path_for(task_description, root, tier)
    if target.exists() and not overwrite:
        return target, False

    covers = infer_covers(task_description) or [slugify(task_description)]
    body = (_full_spec_body(task_description, tier, covers) if tier >= 2
            else _brief_spec_body(task_description, tier, covers))

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return target, True


def enforce(task_description: str,
            cwd: Path | str | None = None,
            auto_generate: bool = True) -> GateDecision:
    """Evaluate and, for Tier 2+ with no bound spec, write the skeleton."""
    decision = evaluate(task_description, cwd)
    if decision.action != "write_spec" or not auto_generate:
        return decision
    try:
        path, written = generate_spec(
            task_description, cwd, tier=decision.tier)
    except OSError as exc:
        decision.directive += (
            f"\n(Spec could not be written automatically: "
            f"{type(exc).__name__}. Create it by hand before editing.)")
        return decision
    decision.spec_path = path
    decision.spec_written = written
    if written:
        decision.directive += (
            f"\nSkeleton written to {path}. Fill Objective, Acceptance "
            f"Criteria and Regression risk BEFORE the first code edit; the "
            f"`covers` front matter already binds it to this task.")
    return decision


__all__ = [
    "TIER_LABEL",
    "SPEC_DIR_PREFERENCE",
    "GateDecision",
    "slugify",
    "resolve_spec_dir",
    "spec_path_for",
    "evaluate",
    "generate_spec",
    "enforce",
]
