#!/usr/bin/env node
/**
 * ceps_correction_stop.js -- Owner-correction capture, Stop-chain child.
 *
 * Calls tools/ceps.py from-stop with the genuine Owner turns of this session.
 * from_stop_hook() writes LOW-confidence drafts to vault/ceps/drafts/; a human
 * resolves them with `/ceps confirm|dismiss`. Nothing here creates an event.
 *
 * Why this file exists: from_stop_hook() shipped with no caller anywhere in the
 * estate and vault/ceps/drafts/ did not exist on disk, so the only mechanism
 * that notices the OWNER correcting the agent had provably never run.
 *
 * THE CORRECTNESS POINT -- read before editing the filter below. In a Claude
 * Code transcript, `type: "user"` does NOT mean "the human typed this". Tool
 * results, system reminders, hook output and slash-command stdout are all
 * recorded as user records. Feeding those to the correction detector would
 * manufacture drafts out of the harness talking to itself -- a
 * <system-reminder> quoting the word "incorrect", or a tool_result containing
 * "revert", would each forge an Owner correction that never happened. Every
 * such record is dropped here, and only free-text the human actually wrote is
 * forwarded.
 *
 * Fail-open ABSOLUTE: any read, parse or spawn problem is a logged no-op. A
 * Stop hook must never break turn end.
 *
 * Owner registration (HR-001 -- the agent may not write ~/.claude/hooks):
 * add this file to hooks/hook-dispatcher.js CHAIN_MAP['Stop-chain'], then copy
 * canonical -> live. Until that lands this producer does not fire, and the
 * reader shipped in f3639da simply has an empty pending set.
 */
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');

const PP_PATH = path.resolve(__dirname, '..');
const PYTHON_EXE =
  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\python.exe';
const CEPS = path.join(PP_PATH, 'tools', 'ceps.py');
const LOG = path.join(os.tmpdir(), 'pp-stop-hooks.log');
const STDIN_TIMEOUT_MS = 3000;
const TAIL_BYTES = 512 * 1024;
const MAX_TURNS = 5;      // from_stop_hook itself only inspects the last 5
const MAX_CHARS = 2000;   // a correction is short; a pasted log is not one

// Harness-injected wrappers. A record carrying any of these is the system
// speaking, not the Owner. Mirrors conversation_quality_audit.py::_HARNESS_RX,
// which draws the same line for the same reason.
const HARNESS_RX = new RegExp(
  [
    '<system-reminder>', '<command-name>', '<command-message>',
    '<command-args>', '<local-command-stdout>', '<local-command-caveat>',
    '<bash-input>', '<bash-stdout>', '<bash-stderr>', '<user-prompt-submit-hook>',
    '<task-notification>', '<persisted-output>',
    'generated by the user while running local commands',
  ].join('|'),
  'i',
);

function logLine(msg) {
  try {
    fs.appendFileSync(LOG, new Date().toISOString() + ' ceps-correction ' + msg + '\n');
  } catch (writeErr) {
    void writeErr;
  }
}

/** Genuine Owner turns, newest last. Bounded tail read: transcripts grow
 *  unbounded and a Stop hook may not pay for the whole file. */
function ownerTurns(transcriptPath) {
  if (!transcriptPath || typeof transcriptPath !== 'string') return [];
  let raw;
  try {
    const { size } = fs.statSync(transcriptPath);
    const start = size > TAIL_BYTES ? size - TAIL_BYTES : 0;
    const fd = fs.openSync(transcriptPath, 'r');
    try {
      const buf = Buffer.alloc(size - start);
      fs.readSync(fd, buf, 0, buf.length, start);
      raw = buf.toString('utf8');
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return [];
  }

  const out = [];
  const lines = raw.split('\n');
  // Walk backwards so the bound is on the NEWEST turns, and a truncated first
  // line simply fails JSON.parse and is skipped.
  for (let i = lines.length - 1; i >= 0 && out.length < MAX_TURNS; i--) {
    const line = lines[i].trim();
    if (!line) continue;
    let rec;
    try { rec = JSON.parse(line); } catch { continue; }
    if (rec.type !== 'user') continue;
    // Meta/compact records are bookkeeping, never Owner prose.
    if (rec.isMeta || rec.isCompactSummary || rec.isVisibleInTranscript === false) continue;

    const content = rec.message && rec.message.content;
    let text = '';
    if (typeof content === 'string') {
      text = content;
    } else if (Array.isArray(content)) {
      // A block list containing a tool_result is the harness returning data.
      if (content.some((b) => b && b.type === 'tool_result')) continue;
      text = content
        .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
        .map((b) => b.text)
        .join('\n');
    }
    text = text.trim();
    if (!text || text.length > MAX_CHARS) continue;
    if (HARNESS_RX.test(text)) continue;
    out.push(text);
  }
  return out.reverse();
}

function dispatch(data) {
  if (!fs.existsSync(PYTHON_EXE) || !fs.existsSync(CEPS)) {
    logLine('SKIP (missing python or ceps.py)');
    return;
  }
  const turns = ownerTurns(data && data.transcript_path);
  if (turns.length === 0) {
    logLine('SKIP (no owner turns in tail)');
    return;
  }
  let turnsFile;
  try {
    turnsFile = path.join(
      os.tmpdir(), `pp-ceps-turns-${process.pid}-${Date.now()}.json`,
    );
    fs.writeFileSync(turnsFile, JSON.stringify(turns), 'utf8');
  } catch (err) {
    logLine('SKIP (cannot stage turns) ' + (err && err.message ? err.message : err));
    return;
  }
  const child = spawn(PYTHON_EXE, [CEPS, 'from-stop', turnsFile], {
    detached: true,
    stdio: 'ignore',
    cwd: PP_PATH,
    windowsHide: true,
    env: Object.assign({}, process.env, { PYTHONIOENCODING: 'utf-8' }),
  });
  child.unref();
  logLine('dispatched pid=' + (child.pid || '?') + ' turns=' + turns.length);
}

function finish() {
  try { process.exit(0); } catch (exitErr) { void exitErr; }
}

// Runtime block runs ONLY as a hook. Under require() -- which the gate uses to
// drive ownerTurns() directly -- registering stdin listeners and an exit timer
// would terminate the test process before it could assert anything.
if (require.main === module) {
  let input = '';
  const timer = setTimeout(() => {
    // No payload means no transcript path, so there is nothing to scan. Exit
    // clean rather than guessing at a transcript location.
    logLine('SKIP (stdin timeout)');
    finish();
  }, STDIN_TIMEOUT_MS);

  process.stdin.setEncoding('utf8');
  process.stdin.on('data', (chunk) => { input += chunk; });
  process.stdin.on('end', () => {
    clearTimeout(timer);
    let data = {};
    try { data = JSON.parse(input); } catch (parseErr) { void parseErr; }
    try { dispatch(data); } catch (err) {
      logLine('ERROR ' + (err && err.message ? err.message : err));
    }
    finish();
  });
  process.stdin.on('error', (err) => {
    clearTimeout(timer);
    logLine('STDIN ERROR ' + (err && err.message ? err.message : err));
    finish();
  });
}

module.exports = { ownerTurns, HARNESS_RX };
