#!/usr/bin/env python3
"""
Claude Power Pack — Memory Engine
Appends learned preferences, corrections, and governance patches to USER_CRITERIA_MEMORY.md.

Usage:
    python append_memory.py "Preference: always use TypeScript strict mode in this project"
    python append_memory.py "Correction: never close and reopen UI in the same frame — defer by 1 tick"
    python append_memory.py "Governance Patch: every display-only UI must block user modifications"
    python append_memory.py "Pattern: when debugging 'X doesnt work', trace the full call chain upward"

Categories auto-detected from prefix, or defaults to "Pattern".
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path

MEMORY_FILENAME = "USER_CRITERIA_MEMORY.md"
MAX_ENTRIES = 500
CATEGORIES = ["Preference", "Correction", "Governance Patch", "Pattern"]
VALID_TAGS = {"GOLDEN_PATTERN"}

TEMPLATE = """# User Criteria Memory
<!-- Auto-generated by claude-power-pack. DO NOT delete this file. -->
<!-- This file stores learned preferences, corrections, and governance rules. -->
<!-- The AI reads this BEFORE every task and appends learnings AFTER corrections. -->

## Preferences
<!-- User preferences will be appended here automatically -->

## Corrections
<!-- Patterns learned from user corrections will be logged here -->

## Governance Patches
<!-- Self-healing governance updates from RCA will appear here -->
"""


def find_memory_file() -> Path:
    """Walk up from CWD to find USER_CRITERIA_MEMORY.md."""
    current = Path.cwd()
    for _ in range(10):  # Max 10 levels up
        candidate = current / MEMORY_FILENAME
        if candidate.exists():
            return candidate
        parent = current.parent
        if parent == current:
            break
        current = parent
    # Not found — create in CWD
    return Path.cwd() / MEMORY_FILENAME


def detect_category(text: str) -> str:
    """Auto-detect category from text prefix."""
    lower = text.lower()
    for cat in CATEGORIES:
        if lower.startswith(cat.lower() + ":"):
            return cat
    return "Pattern"


def strip_category_prefix(text: str, category: str) -> str:
    """Remove the category prefix if present."""
    prefix = category.lower() + ":"
    if text.lower().startswith(prefix):
        return text[len(prefix):].strip()
    return text


def count_entries(content: str) -> int:
    """Count ### entries in the file."""
    return content.count("\n### [")


def archive_old_entries(file_path: Path, content: str) -> str:
    """If >MAX_ENTRIES, archive oldest 100 to .archive file."""
    if count_entries(content) <= MAX_ENTRIES:
        return content

    lines = content.split("\n")
    entry_indices = [i for i, line in enumerate(lines) if line.startswith("### [")]

    # Keep last (MAX_ENTRIES - 100) entries, archive the rest
    cutoff = entry_indices[100] if len(entry_indices) > 100 else entry_indices[0]
    archived = "\n".join(lines[:cutoff])
    remaining_header = "\n".join(lines[:3])  # Keep title + comments
    remaining_body = "\n".join(lines[cutoff:])

    # Write archive
    archive_path = file_path.with_suffix(".archive.md")
    with open(archive_path, "a", encoding="utf-8") as f:
        f.write(f"\n\n<!-- Archived {datetime.now().isoformat()} -->\n")
        f.write(archived)

    return remaining_header + "\n" + remaining_body


def emit_reward(category: str, text: str) -> None:
    """Emit a reward signal to the Agent Lightning trace buffer."""
    traces_dir = Path.home() / ".claude" / "traces"
    traces_dir.mkdir(parents=True, exist_ok=True)

    session_id = os.environ.get("CLAUDE_SESSION_ID", "unknown")
    reward_value = -1.0 if category == "Correction" else -0.5

    reward = {
        "trace_id": f"{session_id}_rca_{int(datetime.now().timestamp())}",
        "session_id": session_id,
        "timestamp": datetime.now().isoformat(),
        "type": "reward",
        "value": reward_value,
        "source": "rca_correction" if category == "Correction" else "governance_heal",
        "error_class": text[:100],
    }

    buffer_path = traces_dir / f"pending_{session_id}.jsonl"
    try:
        with open(buffer_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(reward) + "\n")
    except OSError:
        pass  # Best effort — never block memory append


def append_memory(text: str, tag: str | None = None) -> None:
    """Append a memory entry with timestamp and category. Optional --tag surfaces grep-friendly markers (e.g. GOLDEN_PATTERN)."""
    file_path = find_memory_file()

    # Create if doesn't exist
    if not file_path.exists():
        file_path.write_text(TEMPLATE, encoding="utf-8")
        print(f"Created {file_path}")

    category = detect_category(text)
    clean_text = strip_category_prefix(text, category)
    timestamp = datetime.now().isoformat(timespec="seconds")

    # Emit reward signal to Agent Lightning trace buffer
    if category in ("Correction", "Governance Patch"):
        emit_reward(category, clean_text)

    tag_suffix = f" #{tag}" if tag else ""
    entry = f"\n### [{timestamp}] {category}{tag_suffix}\n{clean_text}\n"

    # Read, archive if needed, append
    content = file_path.read_text(encoding="utf-8")
    content = archive_old_entries(file_path, content)

    # Find the right section to append to
    section_map = {
        "Preference": "## Preferences",
        "Correction": "## Corrections",
        "Governance Patch": "## Governance Patches",
        "Pattern": "## Governance Patches",  # Patterns go to governance
    }
    section_header = section_map.get(category, "## Governance Patches")

    if section_header in content:
        # Insert after the section header (and its comment line)
        idx = content.index(section_header)
        # Find end of section header + comment
        next_newline = content.index("\n", idx)
        # Skip comment line if present
        comment_end = next_newline
        remaining = content[next_newline + 1:]
        if remaining.startswith("<!--"):
            comment_end = content.index("\n", next_newline + 1)

        content = content[:comment_end + 1] + entry + content[comment_end + 1:]
    else:
        # Just append at end
        content += entry

    file_path.write_text(content, encoding="utf-8")
    print(f"[{category}] Appended to {file_path.name}: {clean_text[:80]}...")


def main():
    args = sys.argv[1:]
    if not args:
        print("Usage: python append_memory.py [--tag GOLDEN_PATTERN] \"Category: your lesson here\"")
        print("Categories: Preference, Correction, Governance Patch, Pattern")
        print(f"Valid tags: {sorted(VALID_TAGS)}")
        sys.exit(1)

    tag: str | None = None
    if args[0] == "--tag":
        if len(args) < 3:
            print("Error: --tag requires a tag value and a message")
            sys.exit(1)
        tag = args[1]
        if tag not in VALID_TAGS:
            print(f"Error: unknown tag '{tag}'. Valid: {sorted(VALID_TAGS)}")
            sys.exit(1)
        args = args[2:]

    text = " ".join(args)
    append_memory(text, tag=tag)


if __name__ == "__main__":
    main()
