#!/usr/bin/env python3
"""background_verifier_run.py - the heavy work for Component C (Zero-Command).

Invoked detached by ~/.claude/hooks/background-verifier.js. Performs:
  1. Mirror parity check (global apex vs PP baseline doctrine).
  2. OVO staleness check (last verdict age + uncommitted/ahead).
  3. Spec coherence check (bracketed clarifications vs chain advance).

Writes vault/handoffs/<kind>-<ts>.md only when a check fires AND no
recent (<10 min) handoff of the same kind exists. Never auto-fixes,
never auto-pushes, never auto-runs OVO.

Fail-open: any exception inside any check logs to
~/.claude/logs/background-verifier.log and skips that check; never
crashes the process so the Stop hook child doesn't leave zombies.
"""
from __future__ import annotations
import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

HOME = Path(os.path.expanduser("~"))
PP_ROOT = HOME / ".claude" / "skills" / "claude-power-pack"
LOG_FILE = HOME / ".claude" / "logs" / "background-verifier.log"

GIT_EXE = "git"
for cand in (
    Path("C:/Program Files/Git/cmd/git.exe"),
    Path("C:/Program Files (x86)/Git/cmd/git.exe"),
):
    if cand.is_file():
        GIT_EXE = str(cand)
        break

DEDUPE_WINDOW_SEC = 600  # 10 min - matches the plan's "no log spam" rule
OVO_STALE_SEC = 24 * 3600

MIRROR_PAIRS = [
    (HOME / ".claude" / "knowledge_vault" / "core" / "apex-completion-standard.md",
     PP_ROOT / "vault" / "knowledge_base" / "apex_baseline_doctrine.md"),
]

# Bracketed clarification markers the chain emits then resolves.
SPEC_MARKER_RX = re.compile(r"\[NEEDS\s+CLARIFICATION:[^\]]+\]", re.I)


def log(msg: str) -> None:
    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"{datetime.now(timezone.utc).isoformat()} [verifier] {msg}\n")
    except Exception as e:
        sys.stderr.write(f"background_verifier log fail: {e}\n")


def recent_handoff_exists(handoff_dir: Path, kind: str) -> bool:
    try:
        if not handoff_dir.is_dir():
            return False
        cutoff = time.time() - DEDUPE_WINDOW_SEC
        for p in handoff_dir.glob(f"{kind}-*.md"):
            if p.stat().st_mtime > cutoff:
                return True
        return False
    except OSError as e:
        log(f"recent_handoff_exists({kind}) error: {e}")
        return False


def write_handoff(handoff_dir: Path, kind: str, body: str) -> Path:
    handoff_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    path = handoff_dir / f"{kind}-{ts}.md"
    path.write_text(body, encoding="utf-8")
    return path


def check_mirror_parity(cwd: Path) -> None:
    handoff_dir = cwd / "vault" / "handoffs"
    if recent_handoff_exists(handoff_dir, "mirror-drift"):
        return
    for global_path, pp_path in MIRROR_PAIRS:
        try:
            if not global_path.is_file() or not pp_path.is_file():
                continue
            g_body = global_path.read_text(encoding="utf-8", errors="replace")
            p_body = pp_path.read_text(encoding="utf-8", errors="replace")
            if g_body == p_body:
                continue
            # Drift: line-count + simple diff size signal (lightweight, not unified diff).
            g_lines = g_body.splitlines()
            p_lines = p_body.splitlines()
            body = (
                f"# Mirror Drift Detected\n\n"
                f"- **Global path**: `{global_path}`\n"
                f"- **PP path**: `{pp_path}`\n"
                f"- **Global lines**: {len(g_lines)}\n"
                f"- **PP lines**: {len(p_lines)}\n"
                f"- **Line delta**: {len(g_lines) - len(p_lines)}\n"
                f"- **Byte delta**: {len(g_body) - len(p_body)}\n\n"
                f"## Action\n"
                f"Run `python tools/verify_global_mirrors.py` to see the unified diff; "
                f"resolve by editing the lagging side; commit; re-run mirror verifier.\n"
                f"\n*Generated by background-verifier (Zero-Command Component C).*\n"
            )
            write_handoff(handoff_dir, "mirror-drift", body)
            log(f"mirror drift handoff written ({global_path} vs {pp_path})")
            return  # one handoff per cycle is enough
        except Exception as e:
            log(f"mirror check error: {e}")


def check_ovo_staleness(cwd: Path) -> None:
    handoff_dir = cwd / "vault" / "handoffs"
    if recent_handoff_exists(handoff_dir, "ovo-stale"):
        return
    try:
        verdicts = cwd / "vault" / "audits" / "verdicts.jsonl"
        if not verdicts.is_file():
            return
        # Read last line; verdicts are append-only.
        last_ts = None
        with open(verdicts, "rb") as f:
            f.seek(0, 2)
            sz = f.tell()
            chunk = min(sz, 4096)
            f.seek(sz - chunk)
            tail = f.read().decode("utf-8", errors="replace")
        for line in reversed(tail.splitlines()):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            ts_raw = row.get("ts") or row.get("timestamp")
            if not ts_raw:
                continue
            try:
                if isinstance(ts_raw, (int, float)):
                    last_ts = float(ts_raw)
                else:
                    last_ts = datetime.fromisoformat(
                        str(ts_raw).replace("Z", "+00:00")
                    ).timestamp()
                break
            except Exception:
                continue
        if last_ts is None:
            return
        age_sec = time.time() - last_ts
        if age_sec < OVO_STALE_SEC:
            return
        # Check uncommitted/ahead.
        status = subprocess.run(
            [GIT_EXE, "-C", str(cwd), "status", "--porcelain"],
            capture_output=True, text=True, timeout=10,
        )
        ahead = subprocess.run(
            [GIT_EXE, "-C", str(cwd), "rev-list", "--count", "origin/HEAD..HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        dirty = bool(status.stdout.strip())
        ahead_n = 0
        try:
            ahead_n = int(ahead.stdout.strip() or "0")
        except ValueError:
            ahead_n = 0
        if not dirty and ahead_n == 0:
            return  # nothing to push; stale but no work waiting
        hours = int(age_sec / 3600)
        body = (
            f"# OVO Verdict Stale\n\n"
            f"- **Last verdict age**: {hours} h\n"
            f"- **Uncommitted changes**: {'yes' if dirty else 'no'}\n"
            f"- **Commits ahead of remote**: {ahead_n}\n\n"
            f"## Action\n"
            f"Run `/ovo-audit` before pushing. The OVO push gate requires verdict A or A+ within 600 s TTL.\n"
            f"\n*Generated by background-verifier (Zero-Command Component C); no auto-OVO per Owner constraint.*\n"
        )
        write_handoff(handoff_dir, "ovo-stale", body)
        log(f"ovo-stale handoff written age={hours}h dirty={dirty} ahead={ahead_n}")
    except Exception as e:
        log(f"ovo check error: {e}")


def check_spec_coherence(cwd: Path) -> None:
    handoff_dir = cwd / "vault" / "handoffs"
    if recent_handoff_exists(handoff_dir, "spec-incoherent"):
        return
    try:
        specs_root = cwd / ".specify" / "specs"
        if not specs_root.is_dir():
            return
        for feature_dir in specs_root.iterdir():
            if not feature_dir.is_dir():
                continue
            spec_md = feature_dir / "spec.md"
            if not spec_md.is_file():
                continue
            body = spec_md.read_text(encoding="utf-8", errors="replace")
            markers = SPEC_MARKER_RX.findall(body)
            if not markers:
                continue
            # Has unresolved markers - check if chain has advanced past spec.
            plan_md = feature_dir / "plan.md"
            tasks_md = feature_dir / "tasks.md"
            if not (plan_md.is_file() or tasks_md.is_file()):
                continue  # spec is still being authored; OK
            handoff = (
                f"# Spec Incoherence Detected\n\n"
                f"- **Feature**: `{feature_dir.relative_to(cwd)}`\n"
                f"- **Unresolved clarifications**: {len(markers)}\n"
                f"- **Plan exists**: {plan_md.is_file()}\n"
                f"- **Tasks exist**: {tasks_md.is_file()}\n\n"
                f"## Sample unresolved markers\n\n"
                + "\n".join(f"- {m}" for m in markers[:5])
                + "\n\n## Action\n"
                f"Resolve markers in `spec.md` BEFORE iterating plan/tasks - downstream artifacts inherit ambiguity.\n"
                f"\n*Generated by background-verifier (Zero-Command Component C).*\n"
            )
            write_handoff(handoff_dir, "spec-incoherent", handoff)
            log(f"spec-incoherent handoff written feature={feature_dir.name} markers={len(markers)}")
            return  # one per cycle
    except Exception as e:
        log(f"spec check error: {e}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cwd", required=True)
    ap.add_argument("--session", default="unknown")
    args = ap.parse_args()

    cwd = Path(args.cwd)
    if not cwd.is_dir():
        log(f"cwd not a directory: {cwd}")
        return 0

    log(f"start cwd={cwd} session={args.session}")
    check_mirror_parity(cwd)
    check_ovo_staleness(cwd)
    check_spec_coherence(cwd)
    log("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
