"""Boundary receipts: one receipt per model call, generated by the RUNTIME from the transcript.

The model logs nothing. A receipt carries what a call cost (context, processed), which claims it served,
and the NEW semantic identities first seen in it: events derived from tool_use inputs and tool_result text,
and `ADVANCED:` lines the assistant wrote in its own text. A call with no new identity is a candidate for a
stall (a run of >= --stall such calls); this is a shadow governor: it reports, it never stops anything.

  boundary_receipts.py --transcript S.jsonl --packet PACKET.md [--since ISO] [--stall 5] [--out R.json]

Events: evidence_new, artifact_delta, test_transition, failure_signature_new, obligation_closed.
Calls are deduplicated by assistant message.id (one API call is streamed as several transcript lines).
Subagent transcripts (<transcript stem>/subagents/*.jsonl) are merged in timestamp order.
"""
from __future__ import annotations

import argparse
import base64
import fnmatch
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

SHELL_TOOLS = ("Bash", "PowerShell")
EDIT_TOOLS = ("Edit", "Write", "MultiEdit")
EVIDENCE_TOOLS = ("Read", "Grep", "Glob") + SHELL_TOOLS
DEFAULT_STALL = 5

_TS = re.compile(r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?Z?")
_DUR = re.compile(r"\b\d+(?:\.\d+)?\s?(?:ms|s)\b")
_HEX = re.compile(r"0x[0-9a-fA-F]+|\b[0-9a-fA-F]{7,}\b")
_LINECOL = re.compile(r":\d+(?::\d+)?")
_DIGITS = re.compile(r"\d+")
_WS = re.compile(r"\s+")
_ERR_TYPE = re.compile(r"\b([A-Za-z_.]*(?:Error|Exception))\b")
_FRAME = re.compile(r"([\w./\\-]+\.(?:py|ts|tsx|js|jsx|mjs|cjs|java|ex|exs|rs|go|ps1|json))")
_FAIL_LINE = re.compile(r"^\s*(?:FAILED|FAIL|ERROR|✗|×|✘)\s+(\S.*?)(?:\s+-\s+.*)?\s*$")
_PASS_LINE = re.compile(r"^\s*(?:PASSED|PASS|✓|✔)\s+(\S.*?)\s*$")
_PYTEST_V = re.compile(r"^(\S+::\S+)\s+(PASSED|FAILED)\b")
_FAIL_WORDS = re.compile(r"Traceback|FAILED|\bFAIL\b|✗|×|✘|Error|Exception|Exit code:? [1-9]")
_BAD_RESULT = re.compile(r"Traceback|\bFAILED\b|\b[1-9]\d* failed\b|Exit code:? [1-9]|exit code:? [1-9]")


def _sha(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8", "replace")).hexdigest()


def _norm_light(s: str) -> str:
    return _WS.sub(" ", _DUR.sub("", _TS.sub("", s))).strip()


def _norm_sig(s: str) -> str:
    s = _TS.sub("", s)
    s = _HEX.sub("", s)
    s = _LINECOL.sub("", s)
    s = _DIGITS.sub("", s)
    return _WS.sub(" ", s).strip()


def _norm_text(s: str) -> str:
    return _WS.sub(" ", re.sub(r"[^\w\s]", "", s.lower())).strip()


def load_packet(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    unit, section, sec = None, None, {"Claims": [], "Context": [], "Affected": [], "Acceptance": []}
    for ln in text.splitlines():
        if ln.startswith("unit: ") and unit is None:
            unit = ln[6:].strip()
        elif ln.startswith("## "):
            section = ln[3:].strip()
        elif section in sec and ln.startswith("- "):
            sec[section].append(ln[2:].strip())
    claims = [c.split(":", 1)[0].strip() for c in sec["Claims"]]
    # `## Affected` holds the unit's file globs. Context is prose in a real packet; it is used as globs
    # only by packets written before Affected existed (canary T, 2026-10-06, dropped every write that way).
    globs = sec["Affected"] or sec["Context"]
    return {"unit": unit, "claims": claims, "globs": globs, "acceptance": sec["Acceptance"]}


def _result_text(block: dict) -> str:
    c = block.get("content")
    if isinstance(c, list):
        c = "\n".join(x.get("text", "") for x in c if isinstance(x, dict))
    return str(c or "")


def image_dimensions(data: bytes) -> tuple[int | None, int | None]:
    """(width, height) from the bytes' own header (PNG, GIF, JPEG SOFn, WebP); (None, None) when not understood."""
    try:
        if data[:8] == b"\x89PNG\r\n\x1a\n" and data[12:16] == b"IHDR":
            return struct.unpack(">II", data[16:24])
        if data[:6] in (b"GIF87a", b"GIF89a"):
            return struct.unpack("<HH", data[6:10])
        if data[:2] == b"\xff\xd8":
            i = 2
            while i + 9 < len(data):
                if data[i] != 0xFF:
                    i += 1
                    continue
                marker = data[i + 1]
                if marker == 0xFF:
                    i += 1
                    continue
                if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                    i += 2
                    continue
                if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                    h, w = struct.unpack(">HH", data[i + 5:i + 9])
                    return w, h
                i += 2 + struct.unpack(">H", data[i + 2:i + 4])[0]
        if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
            kind = data[12:16]
            if kind == b"VP8X":
                return 1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")
            if kind == b"VP8L" and data[20] == 0x2F:
                bits = int.from_bytes(data[21:25], "little")
                return (bits & 0x3FFF) + 1, ((bits >> 14) & 0x3FFF) + 1
            if kind == b"VP8 ":
                w, h = struct.unpack("<HH", data[26:30])
                return w & 0x3FFF, h & 0x3FFF
    except (struct.error, IndexError):
        pass
    return None, None


def _result_images(block: dict) -> list[dict]:
    """Image blocks of a tool result as identity records (key = data hash); the pixel data is never kept."""
    c, out = block.get("content"), []
    for x in c if isinstance(c, list) else []:
        if not (isinstance(x, dict) and x.get("type") == "image"):
            continue
        src = x.get("source") if isinstance(x.get("source"), dict) else {}
        try:
            data = base64.b64decode(src.get("data") or "")
        except (ValueError, TypeError):
            data = b""
        w, h = image_dimensions(data)
        sha = hashlib.sha256(data).hexdigest()
        out.append({"sha": sha, "key": sha[:12], "media_type": src.get("media_type"),
                    "width": w, "height": h, "bytes": len(data)})
    return out


def read_transcripts(paths: list[Path]) -> tuple[list[dict], dict]:
    calls: dict = {}
    results: dict = {}
    for p in paths:
        for raw in p.read_text(encoding="utf-8", errors="replace").splitlines():
            try:
                row = json.loads(raw)
            except ValueError:
                continue
            msg = row.get("message") if isinstance(row, dict) else None
            if not isinstance(msg, dict):
                continue
            content = msg.get("content")
            if row.get("type") == "assistant" and msg.get("id"):
                call = calls.setdefault(msg["id"], {"id": msg["id"], "ts": row.get("timestamp") or "",
                                                    "model": msg.get("model"), "usage": {}, "tools": [],
                                                    "text": [], "seen_blocks": set()})
                if msg.get("usage"):
                    call["usage"] = msg["usage"]
                for b in content if isinstance(content, list) else []:
                    key = b.get("id") or json.dumps(b, sort_keys=True)
                    if key in call["seen_blocks"]:
                        continue
                    call["seen_blocks"].add(key)
                    if b.get("type") == "tool_use":
                        call["tools"].append(b)
                    elif b.get("type") == "text":
                        call["text"].append(b.get("text", ""))
            elif isinstance(content, list):
                for b in content:
                    if isinstance(b, dict) and b.get("type") == "tool_result":
                        results[b.get("tool_use_id")] = {"text": _result_text(b), "is_error": bool(b.get("is_error")),
                                                         "images": _result_images(b)}
    return sorted(calls.values(), key=lambda c: c["ts"]), results


def _glob_match(path: str, globs: list[str]) -> bool:
    if not globs:
        return True
    p = path.replace("\\", "/")
    for g in globs:
        g = g.replace("\\", "/").lstrip("/")
        if fnmatch.fnmatch(p, g) or fnmatch.fnmatch(p, "*/" + g) or (g.endswith("/") and g in p):
            return True
    return False


def _test_states(text: str) -> dict:
    states: dict = {}
    for ln in text.splitlines():
        m = _PYTEST_V.match(ln)
        if m:
            states[m.group(1)] = "pass" if m.group(2) == "PASSED" else "fail"
            continue
        m = _FAIL_LINE.match(ln)
        if m:
            states[_clean_test_id(m.group(1))] = "fail"
            continue
        m = _PASS_LINE.match(ln)
        if m:
            states[_clean_test_id(m.group(1))] = "pass"
    return {k: v for k, v in states.items() if k}


def _clean_test_id(s: str) -> str:
    s = re.sub(r"\(\d+(?:\.\d+)?\s?m?s\)\s*$", "", s).strip()
    return re.sub(r"^\d+\s+", "", s)


def _signatures(text: str, states: dict) -> list[str]:
    typ = _ERR_TYPE.search(text)
    frame = _FRAME.search(text)
    frame_name = Path(frame.group(1).replace("\\", "/")).name if frame else ""
    fails = [t for t, s in states.items() if s == "fail"] or [""]
    return sorted({_norm_sig(f"{typ.group(1) if typ else 'Failure'}|{t}|{frame_name}") for t in fails})


def build_receipts(calls: list[dict], results: dict, packet: dict, *, since: str | None = None) -> list[dict]:
    seen_evidence: set = set()
    file_state: dict = {}
    file_seen: dict = {}
    test_state: dict = {}
    seen_sigs: set = set()
    seen_adv: set = set()
    seen_images: set = set()
    closed: set = set()
    receipts = []
    for call in calls:
        if since and call["ts"] < since:
            continue
        u = call["usage"] or {}
        context = int(u.get("input_tokens") or 0) + int(u.get("cache_read_input_tokens") or 0) \
            + int(u.get("cache_creation_input_tokens") or 0)
        events, advancements, dups, n_images, img_dups = [], [], 0, 0, 0
        for t in call["tools"]:
            name, inp = t.get("name"), t.get("input") or {}
            res = results.get(t.get("id"), {"text": "", "is_error": False, "images": []})
            text = res["text"]
            for im in res.get("images", []):
                n_images += 1
                if im["sha"][:12] in seen_images:
                    img_dups += 1
                else:
                    seen_images.add(im["sha"][:12])
                    events.append({"kind": "image_new", "key": im["sha"][:12], "media_type": im["media_type"],
                                   "width": im["width"], "height": im["height"], "bytes": im["bytes"],
                                   "model": call["model"]})
            if name in EDIT_TOOLS:
                path = str(inp.get("file_path") or "")
                if not path or not _glob_match(path, packet["globs"]):
                    continue
                prev = file_state.get(path)
                if name == "Write":
                    content = inp.get("content") or ""
                    new = content
                    h = _sha(content)
                else:
                    edits = inp.get("edits") if name == "MultiEdit" else [inp]
                    cur = prev
                    for e in edits or []:
                        old, rep = e.get("old_string") or "", e.get("new_string") or ""
                        if old == rep:
                            continue
                        cur = cur.replace(old, rep, 1) if isinstance(cur, str) else \
                            "\x00chain:" + _sha(f"{cur}|{old}|{rep}")
                    new, h = cur, _sha(cur if isinstance(cur, str) else str(cur))
                    if cur == prev:
                        continue
                file_state[path] = new
                bucket = file_seen.setdefault(path, set())
                if h in bucket:
                    dups += 1
                else:
                    bucket.add(h)
                    events.append({"kind": "artifact_delta", "key": f"{path}@{h[:12]}"})
                continue
            if name in EVIDENCE_TOOLS and text:
                h = _sha(_norm_light(text))
                if h in seen_evidence:
                    dups += 1
                else:
                    seen_evidence.add(h)
                    events.append({"kind": "evidence_new", "key": h[:12]})
            if name in SHELL_TOOLS and text:
                states = _test_states(text)
                for tid, st in states.items():
                    if test_state.get(tid) != st:
                        test_state[tid] = st
                        events.append({"kind": "test_transition", "key": f"{tid}:{st}"})
                    else:
                        dups += 1
                if res["is_error"] or _FAIL_WORDS.search(text):
                    for sig in _signatures(text, states):
                        if sig in seen_sigs:
                            dups += 1
                        else:
                            seen_sigs.add(sig)
                            events.append({"kind": "failure_signature_new", "key": sig})
                ok = not res["is_error"] and not _BAD_RESULT.search(text)
                cmd = str(inp.get("command") or "")
                for acc in packet["acceptance"]:
                    if acc and acc not in closed and ok and acc in cmd:
                        closed.add(acc)
                        events.append({"kind": "obligation_closed", "key": acc})
        for blob in call["text"]:
            for ln in blob.splitlines():
                m = re.match(r"^\s*ADVANCED:\s*(.+?)\s*$", ln)
                if not m:
                    continue
                h = _sha(_norm_text(m.group(1)))
                if h in seen_adv:
                    dups += 1
                else:
                    seen_adv.add(h)
                    advancements.append({"text": m.group(1), "key": h[:12]})
        receipts.append({"msg": call["id"], "ts": call["ts"], "model": call["model"], "context": context,
                         "processed": context + int(u.get("output_tokens") or 0),
                         "tools": [t.get("name") for t in call["tools"]], "unit": packet["unit"],
                         "consumer_claims": list(packet["claims"]), "events": events,
                         "advancements": advancements, "duplicates": dups, "images": n_images, "image_dups": img_dups})
    return receipts


def summarize(receipts: list[dict], stall: int = DEFAULT_STALL) -> dict:
    n = len(receipts)
    fresh = [bool(r["events"] or r["advancements"]) for r in receipts]
    runs, cur = [], 0
    for f in fresh:
        if f:
            if cur:
                runs.append(cur)
            cur = 0
        else:
            cur += 1
    if cur:
        runs.append(cur)
    return {"calls": n, "processed": sum(r["processed"] for r in receipts),
            "avg_context": round(sum(r["context"] for r in receipts) / n) if n else 0,
            "semantic_interrupt_density": round(sum(fresh) / n, 4) if n else 0.0,
            "longest_run_without_new_identity": max(runs, default=0),
            "stalls": sum(1 for r in runs if r >= stall), "stall_threshold": stall}


def transcript_paths(main: Path) -> list[Path]:
    sub = main.with_suffix("") / "subagents"
    return [main] + (sorted(sub.glob("*.jsonl")) if sub.is_dir() else [])


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="boundary_receipts")
    ap.add_argument("--transcript", required=True)
    ap.add_argument("--packet", required=True)
    ap.add_argument("--since")
    ap.add_argument("--stall", type=int, default=DEFAULT_STALL)
    ap.add_argument("--out")
    args = ap.parse_args(argv)
    try:
        packet = load_packet(Path(args.packet))
        calls, results = read_transcripts(transcript_paths(Path(args.transcript)))
    except OSError as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2
    receipts = build_receipts(calls, results, packet, since=args.since)
    summary = summarize(receipts, args.stall)
    if args.out:
        Path(args.out).write_text(json.dumps({"summary": summary, "receipts": receipts}, indent=1), encoding="utf-8")
    print(json.dumps(summary, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
