<#
  build_pane_map.ps1 -- derive the resumable-pane recovery map from DISK TRUTH.

  Single source of truth for the PP Sessions extension and for manual recovery.

  Source of truth = the transcript .jsonl files on disk, NOT the snapshot. The
  session_snapshot.json under-records in TWO ways and we correct BOTH:
    (a) within a repo it misses sids (it only holds sessions the SessionStart
        hub processed) -- fixed by unioning disk transcripts per repo;
    (b) it can drop a whole repo from its active-cwd set (e.g. it listed 0
        TUA-X panes while disk had 6 touched 90 min ago) -- fixed by ALSO
        discovering active repos from disk: any transcript touched within
        RecentHours contributes its own recorded `cwd` to the active set.
  So we:
    1. take the set of ACTIVE repos = snapshot cwds UNION cwds discovered from
       recently-touched transcripts on disk (additive -- never drops a repo),
    2. for each repo, UNION the snapshot's sids with EVERY recent transcript on
       disk for that cwd (disk is complete),
    3. filter out sub-sessions (local-command caveats, research/SERP agent
       prompts) -- those are spawned under a tab, they are not tabs,
    4. classify and emit.
  Never invents a session id; every emitted pane has a transcript on disk.

  LIVE vs RECENT (added 2026-06-22 after the InfinityOps reload RCA): the map is
  deliberately over-inclusive (any transcript <=RecentHours) so it never DROPS a
  recoverable pane. That over-inclusion conflated "open tab at risk on reload"
  with "closed conversation you could reopen". We now mark each pane `live`:
    live = sid is in the snapshot live-registry  OR  transcript written within
           LiveMinutes (actively being written == an open tab right now).
  `live:true`  -> an OPEN tab; persistent-sessions is supposed to revive it, the
                  card is the deterministic fallback if it does not.
  `live:false` -> a RECENT but closed conversation; a reopen candidate, not a
                  pane you "lost". `status` (RESUMABLE/OLD) is unchanged so the
                  extension needs no rebuild; `live` is purely additive.

  Outputs (all under ~/.claude/state):
    pane_map.json            machine-readable, read by the PP Sessions extension
    pane_map.md              human-readable recovery map, grouped by repo
    reload_recovery_card.md  paste-ready resume commands, grouped by repo

  Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools/build_pane_map.ps1
#>
[CmdletBinding()]
param(
  [string]$StateDir = (Join-Path $env:USERPROFILE ".claude\state"),
  [string]$ProjBase = (Join-Path $env:USERPROFILE ".claude\projects"),
  [int]$RecentHours = 24,
  [int]$OldHours = 48,
  [int]$LiveMinutes = 12,
  [string]$TabOrderFile = (Join-Path $StateDir "tab_order.json")
)
$ErrorActionPreference = "Stop"
$nowUtc = (Get-Date).ToUniversalTime()

# Sub-session prefixes: a transcript whose first user message starts with one of
# these is NOT an interactive tab (it is a local-command shell-out or a research
# sub-agent spawned inside a tab).
# Matched as substrings (contains) against the first user message. Distinctive
# enough not to false-positive on a real tab.
$SUB_PREFIXES = @(
  'messages below were generated by the user while running local commands',
  'expert and insightful researcher',
  'contents from a SERP search',
  'generate a list of SERP',
  'generate a list of search queries'
)

function Get-SessionMeta($jsonl) {
  # Streams the head of the transcript: returns topic, isSub. Bounded scan.
  $topic = ""; $firstUser = ""; $n = 0
  foreach ($ln in [System.IO.File]::ReadLines($jsonl, [System.Text.Encoding]::UTF8)) {
    $n++; if ($n -gt 200) { break }
    try { $o = $ln | ConvertFrom-Json -EA Stop } catch { continue }
    if (-not $topic -and $o.type -eq 'summary' -and $o.summary) { $topic = $o.summary }
    if (-not $firstUser -and $o.type -eq 'user' -and $o.message.role -eq 'user') {
      $c = $o.message.content
      if ($c -is [string]) { $t = $c } elseif ($c) { $t = ($c | Where-Object { $_.type -eq 'text' } | Select-Object -First 1).text }
      if ($t) { $firstUser = ($t -replace '<[^>]+>', ' ' -replace '\s+', ' ').Trim() }
    }
    if ($topic -and $firstUser) { break }
  }
  $isSub = $false
  foreach ($p in $SUB_PREFIXES) { if ($firstUser -like ('*' + $p + '*')) { $isSub = $true; break } }
  if (-not $topic) { $topic = $firstUser }
  $topic = ($topic -replace '[^\x20-\x7E]', ' ' -replace '\s+', ' ').Trim()
  if ($topic.Length -gt 90) { $topic = $topic.Substring(0, 90) + '...' }
  return @{ topic = $topic; isSub = $isSub }
}

function Get-TranscriptCwd($jsonl) {
  # Reads the transcript's own recorded cwd (cheap regex, no full JSON parse).
  # Claude Code stamps "cwd":"C:\\..." on transcript records; this lets us learn
  # the real working dir without inverting the lossy project-dir encoding.
  $n = 0
  foreach ($ln in [System.IO.File]::ReadLines($jsonl, [System.Text.Encoding]::UTF8)) {
    $n++; if ($n -gt 40) { break }
    if ($ln -match '"cwd"\s*:\s*"((?:[^"\\]|\\.)*)"') { return ($matches[1] -replace '\\\\', '\') }
  }
  return $null
}

function Get-LastInternalAgeMin($jsonl, $nowUtc) {
  # Age (minutes) of the transcript's NEWEST internal "timestamp" record -- i.e.
  # when a real conversation turn last landed, NOT the file's LastWriteTime.
  # File mtime is unreliable for liveness: any batch sweep (heartbeat merger,
  # backup, git checkout, AV scan) rewrites mtimes en masse and makes every
  # transcript look "written seconds ago" (proven 2026-07-06: 35 files shared one
  # mtime spike while their real last turn was 14h-7d old). The internal timestamp
  # is content, so a metadata-only touch cannot forge it. Reads a bounded tail.
  try {
    $fs = [System.IO.File]::Open($jsonl, 'Open', 'Read', 'ReadWrite')
    try {
      $len = $fs.Length
      $back = [Math]::Min($len, 200000)
      [void]$fs.Seek($len - $back, 'Begin')
      $buf = New-Object byte[] $back
      [void]$fs.Read($buf, 0, $back)
    } finally { $fs.Close() }
    $text = [System.Text.Encoding]::UTF8.GetString($buf)
    $lastTs = $null
    foreach ($m in [regex]::Matches($text, '"timestamp"\s*:\s*"([^"]+)"')) { $lastTs = $m.Groups[1].Value }
    if ($lastTs) {
      $t = [datetime]::Parse($lastTs, $null,
        ([System.Globalization.DateTimeStyles]::AdjustToUniversal -bor [System.Globalization.DateTimeStyles]::AssumeUniversal))
      return ($nowUtc - $t).TotalMinutes
    }
  } catch { }
  return [double]::PositiveInfinity
}

# 1. active repos = snapshot cwds UNION cwds discovered from recent disk transcripts
$snapPath = Join-Path $StateDir "session_snapshot.json"
$activeCwds = @{}
$snap = $null
$snapSids = @{}
if (Test-Path $snapPath) {
  $snap = Get-Content $snapPath -Raw -Encoding UTF8 | ConvertFrom-Json
  foreach ($p in $snap) {
    if ($p.cwd) { $activeCwds[$p.cwd] = $true }
    if ($p.session_id) { $snapSids[$p.session_id] = $true }   # live registry
  }
}
# disk discovery: any project dir holding a transcript touched within RecentHours
# contributes its own recorded cwd -- this rescues repos the snapshot dropped.
foreach ($dir in (Get-ChildItem $ProjBase -Directory -EA SilentlyContinue)) {
  $recent = Get-ChildItem $dir.FullName -Filter *.jsonl -File -EA SilentlyContinue |
    Where-Object { ($nowUtc - $_.LastWriteTime.ToUniversalTime()).TotalHours -le $RecentHours }
  foreach ($rf in $recent) {
    $cwd = Get-TranscriptCwd $rf.FullName
    if ($cwd -and (Test-Path $cwd)) { $activeCwds[$cwd] = $true }
  }
}

# 2+3. per repo: union snapshot sids with recent disk transcripts; filter subs
$seen = @{}; $items = @()
foreach ($cwd in $activeCwds.Keys) {
  $enc = ($cwd -replace '[^a-zA-Z0-9]', '-')
  $pd = Join-Path $ProjBase $enc
  if (-not (Test-Path $pd)) { continue }
  $repo = Split-Path $cwd -Leaf
  $files = Get-ChildItem $pd -Filter *.jsonl -File -EA SilentlyContinue |
    Where-Object { ($nowUtc - $_.LastWriteTime.ToUniversalTime()).TotalHours -le $OldHours }
  foreach ($f in $files) {
    $sid = $f.BaseName
    if ($seen.ContainsKey($sid)) { continue }
    $ageH = ($nowUtc - $f.LastWriteTime.ToUniversalTime()).TotalHours
    $ageMin = ($nowUtc - $f.LastWriteTime.ToUniversalTime()).TotalMinutes
    # recency gate: keep sessions touched within the work window OR still
    # registered in the snapshot (idle-but-open tabs)
    $inSnap = $snapSids.ContainsKey($sid)
    if ($ageH -gt $RecentHours -and -not $inSnap) { continue }
    $meta = Get-SessionMeta $f.FullName
    if ($meta.isSub) { continue }                          # not a tab
    $seen[$sid] = $true
    $status = if ($ageH -gt $OldHours) { "OLD" } else { "RESUMABLE" }
    # LIVE = in the snapshot live-registry OR a REAL conversation turn landed
    # within LiveMinutes. We use the internal-timestamp age (content), NOT the
    # file mtime ($ageMin), because a batch mtime-touch forges mtime-based
    # liveness and floods the map with false-LIVE panes (RCA 2026-07-06,
    # T-PANE-MAP-FALSE-LIVE-MTIME-001). $ageMin is retained only for display.
    $internalAgeMin = Get-LastInternalAgeMin $f.FullName $nowUtc
    $isLive = $inSnap -or ($internalAgeMin -le $LiveMinutes)
    $items += [ordered]@{
      repo = $repo; cwd = $cwd; sessionId = $sid; topic = $meta.topic
      lastActivity = $f.LastWriteTime.ToUniversalTime().ToString('o')
      ageHours = [math]::Round($ageH, 1)
      status = $status; live = $isLive; resumeCmd = "kclaude --resume $sid"; confidence = "HIGH"
    }
  }
}
# --- tab-order overlay (SCS C78 addendum v2) --------------------------------
# If the PP Sessions extension has recorded the real left-to-right tab order
# (~/.claude/state/tab_order.json via vscode.window.tabGroups), lead the map with
# panes in that visual order; the rest stay most-recent-first (prior behavior).
# The join key is the 8-hex session-id prefix the extension embeds in each pane
# terminal's name (T-TAB-ORDER-EXTENSION-ONLY-001). Fail-open: absent/malformed
# file, or zero matches -> every pane ties at rank MaxValue and the map is pure
# lastActivity order, exactly as before.
$tabRank = @{}
if (Test-Path $TabOrderFile) {
  try {
    $to = Get-Content $TabOrderFile -Raw -Encoding UTF8 | ConvertFrom-Json
    $r = 0
    foreach ($t in @($to.tabs)) {
      $pfx = ("" + $t.sidPrefix).ToLower()
      if ($pfx -and -not $tabRank.ContainsKey($pfx)) { $tabRank[$pfx] = $r; $r++ }
    }
  } catch { $tabRank = @{} }   # malformed JSON -> fail-open to lastActivity
}
function Get-TabRank($sid) {
  $s = "" + $sid
  $pfx = $s.Substring(0, [Math]::Min(8, $s.Length)).ToLower()
  if ($tabRank.ContainsKey($pfx)) { return $tabRank[$pfx] }
  return [int]::MaxValue
}
# matched panes first in real tab order; unmatched tail most-recent-first
$items = @($items | Sort-Object @{ Expression = { Get-TabRank $_.sessionId }; Ascending = $true }, @{ Expression = { [datetime]$_.lastActivity }; Descending = $true })

$counts = [ordered]@{
  resumable = ($items | Where-Object { $_.status -eq 'RESUMABLE' }).Count
  old       = ($items | Where-Object { $_.status -eq 'OLD' }).Count
  live      = ($items | Where-Object { $_.live }).Count
  repos     = (@($items | ForEach-Object { $_.repo }) | Sort-Object -Unique).Count
}
$payload = [ordered]@{ generatedAt = $nowUtc.ToString('o'); source = "transcripts-on-disk (active repos = snapshot UNION disk-discovered cwds)"; liveMinutes = $LiveMinutes; counts = $counts; panes = $items }

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.json"), ($payload | ConvertTo-Json -Depth 6), $utf8)

$repoNames = @(@($items | ForEach-Object { $_.repo }) | Sort-Object -Unique)

# --- pane_map.md : human-readable recovery map, grouped by repo ---
$sb = New-Object System.Text.StringBuilder
function W($s) { [void]$sb.AppendLine($s) }
W "# PP PANE MAP -- Recovery Safety Net"
W ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local | Source: transcripts-on-disk (active repos = snapshot UNION disk-discovered)")
W ("LIVE = open tab right now (in snapshot or written < {0} min ago) -- at risk on reload. recent = closed conversation, a reopen candidate." -f $LiveMinutes)
W "If a Cursor reload loses a pane, paste the exact command below into a terminal in the right repo."
W ""
foreach ($rn in $repoNames) {
  $grpItems = @($items | Where-Object { $_.repo -eq $rn })
  $liveN = @($grpItems | Where-Object { $_.live }).Count
  W ("## {0} ({1} -- {2} LIVE)" -f $rn, $grpItems.Count, $liveN); W ""
  foreach ($it in $grpItems) {
    $tag = if ($it.live) { "LIVE" } else { "recent" }
    W ("- **[{0}] {1}** ({2}h ago, {3})" -f $tag, $it.topic, $it.ageHours, $it.status)
    W ("  - ``cd `"{0}`" ; {1}``" -f $it.cwd, $it.resumeCmd); W ""
  }
}
W "---"
W "Built from disk transcripts. Active repos = snapshot UNION disk-discovered cwds. Sub-sessions (local-command, research/SERP agent prompts) are excluded. Every entry has a transcript on disk (confidence HIGH)."
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.md"), $sb.ToString(), $utf8)

# --- reload_recovery_card.md : paste-ready resume commands, grouped by repo ---
$cb = New-Object System.Text.StringBuilder
function C($s) { [void]$cb.AppendLine($s) }
C "=== RELOAD RECOVERY CARD ==="
C ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local  (" + $items.Count + " panes / " + $counts.repos + " repos / " + $counts.live + " LIVE)")
C ""
C ("[LIVE] = an OPEN tab right now (snapshot or written < {0} min ago); these are the ones a reload can drop." -f $LiveMinutes)
C "[recent] = a closed conversation you can reopen. Every command resumes the EXACT conversation (no 'History restored')."
C "If a pane does NOT survive Ctrl+Shift+P -> Reload Window, paste its command in a terminal in the right repo."
C ""
foreach ($rn in $repoNames) {
  $grp = @($items | Where-Object { $_.repo -eq $rn })
  $liveN = @($grp | Where-Object { $_.live }).Count
  C ("---- {0} ({1} -- {2} LIVE) ----" -f $rn, $grp.Count, $liveN)
  foreach ($it in $grp) {
    $tag = if ($it.live) { "LIVE  " } else { "recent" }
    C ("  # [{0}] {1}  ({2}h ago)" -f $tag, $it.topic, $it.ageHours)
    C ("  cd `"{0}`" ; {1}" -f $it.cwd, $it.resumeCmd)
    C ""
  }
}
C "=== END CARD ==="
[System.IO.File]::WriteAllText((Join-Path $StateDir "reload_recovery_card.md"), $cb.ToString(), $utf8)

Write-Output ("pane_map written | resumable={0} old={1} live={2} repos={3} total={4}" -f $counts.resumable, $counts.old, $counts.live, $counts.repos, $items.Count)
