<#
  build_pane_map.ps1 -- derive the resumable-pane recovery map from DISK TRUTH.

  Single source of truth for the PP Sessions extension and for manual recovery.

  Source of truth = the transcript .jsonl files on disk, NOT the snapshot. The
  session_snapshot.json under-records (it only holds sessions the SessionStart
  hub processed) -- e.g. it listed 5 TUA-X panes while disk had 10. So we:
    1. take the set of ACTIVE repos (distinct cwds the snapshot knows are open),
    2. for each repo, UNION the snapshot's sids with EVERY recent transcript on
       disk for that cwd (this is the fix -- disk is complete),
    3. filter out sub-sessions (local-command caveats, research/SERP agent
       prompts) -- those are spawned under a tab, they are not tabs,
    4. classify and emit.
  Never invents a session id; every emitted pane has a transcript on disk.

  Outputs:
    ~/.claude/state/pane_map.json   (machine-readable, read by the extension)
    ~/.claude/state/pane_map.md     (human-readable recovery map)

  Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools/build_pane_map.ps1
#>
[CmdletBinding()]
param(
  [string]$StateDir = (Join-Path $env:USERPROFILE ".claude\state"),
  [string]$ProjBase = (Join-Path $env:USERPROFILE ".claude\projects"),
  [int]$RecentHours = 24,
  [int]$OldHours = 48
)
$ErrorActionPreference = "Stop"
$nowUtc = (Get-Date).ToUniversalTime()

# Sub-session prefixes: a transcript whose first user message starts with one of
# these is NOT an interactive tab (it is a local-command shell-out or a research
# sub-agent spawned inside a tab).
# Matched as substrings (contains) against the first user message. Distinctive
# enough not to false-positive on a real tab.
$SUB_PREFIXES = @(
  'messages below were generated by the user while running local commands',
  'expert and insightful researcher',
  'contents from a SERP search',
  'generate a list of SERP',
  'generate a list of search queries'
)

function Get-SessionMeta($jsonl) {
  # Streams the head of the transcript: returns topic, isSub. Bounded scan.
  $topic = ""; $firstUser = ""; $n = 0
  foreach ($ln in [System.IO.File]::ReadLines($jsonl, [System.Text.Encoding]::UTF8)) {
    $n++; if ($n -gt 200) { break }
    try { $o = $ln | ConvertFrom-Json -EA Stop } catch { continue }
    if (-not $topic -and $o.type -eq 'summary' -and $o.summary) { $topic = $o.summary }
    if (-not $firstUser -and $o.type -eq 'user' -and $o.message.role -eq 'user') {
      $c = $o.message.content
      if ($c -is [string]) { $t = $c } elseif ($c) { $t = ($c | Where-Object { $_.type -eq 'text' } | Select-Object -First 1).text }
      if ($t) { $firstUser = ($t -replace '<[^>]+>', ' ' -replace '\s+', ' ').Trim() }
    }
    if ($topic -and $firstUser) { break }
  }
  $isSub = $false
  foreach ($p in $SUB_PREFIXES) { if ($firstUser -like ('*' + $p + '*')) { $isSub = $true; break } }
  if (-not $topic) { $topic = $firstUser }
  $topic = ($topic -replace '[^\x20-\x7E]', ' ' -replace '\s+', ' ').Trim()
  if ($topic.Length -gt 90) { $topic = $topic.Substring(0, 90) + '...' }
  return @{ topic = $topic; isSub = $isSub }
}

# 1. active repos = distinct cwds the snapshot knows are open
$snapPath = Join-Path $StateDir "session_snapshot.json"
$activeCwds = @{}
if (Test-Path $snapPath) {
  $snap = Get-Content $snapPath -Raw -Encoding UTF8 | ConvertFrom-Json
  foreach ($p in $snap) { if ($p.cwd) { $activeCwds[$p.cwd] = $true } }
}

# 2+3. per repo: union snapshot sids with recent disk transcripts; filter subs
$seen = @{}; $items = @()
foreach ($cwd in $activeCwds.Keys) {
  $enc = ($cwd -replace '[^a-zA-Z0-9]', '-')
  $pd = Join-Path $ProjBase $enc
  if (-not (Test-Path $pd)) { continue }
  $repo = Split-Path $cwd -Leaf
  $files = Get-ChildItem $pd -Filter *.jsonl -File -EA SilentlyContinue |
    Where-Object { ($nowUtc - $_.LastWriteTime.ToUniversalTime()).TotalHours -le $OldHours }
  foreach ($f in $files) {
    $sid = $f.BaseName
    if ($seen.ContainsKey($sid)) { continue }
    $ageH = ($nowUtc - $f.LastWriteTime.ToUniversalTime()).TotalHours
    # recency gate: keep sessions touched within the work window OR still
    # registered in the snapshot (idle-but-open tabs)
    $inSnap = $false
    if ($snap) { foreach ($p in $snap) { if ($p.session_id -eq $sid) { $inSnap = $true; break } } }
    if ($ageH -gt $RecentHours -and -not $inSnap) { continue }
    $meta = Get-SessionMeta $f.FullName
    if ($meta.isSub) { continue }                          # not a tab
    $seen[$sid] = $true
    $status = if ($ageH -gt $OldHours) { "OLD" } else { "RESUMABLE" }
    $items += [ordered]@{
      repo = $repo; cwd = $cwd; sessionId = $sid; topic = $meta.topic
      lastActivity = $f.LastWriteTime.ToUniversalTime().ToString('o')
      ageHours = [math]::Round($ageH, 1)
      status = $status; resumeCmd = "claude --resume $sid"; confidence = "HIGH"
    }
  }
}
# most-recent-first within the whole map
$items = @($items | Sort-Object { [datetime]$_.lastActivity } -Descending)

$counts = [ordered]@{
  resumable = ($items | Where-Object { $_.status -eq 'RESUMABLE' }).Count
  old       = ($items | Where-Object { $_.status -eq 'OLD' }).Count
  repos     = (@($items | ForEach-Object { $_.repo }) | Sort-Object -Unique).Count
}
$payload = [ordered]@{ generatedAt = $nowUtc.ToString('o'); source = "transcripts-on-disk (per active repo) + snapshot union"; counts = $counts; panes = $items }

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.json"), ($payload | ConvertTo-Json -Depth 6), $utf8)

# Markdown view, grouped by repo (most-recent-first)
$sb = New-Object System.Text.StringBuilder
function W($s) { [void]$sb.AppendLine($s) }
W "# PP PANE MAP -- Recovery Safety Net"
W ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local | Source: transcripts-on-disk per active repo (complete; snapshot is union-only)")
W "If a Cursor reload loses a pane, paste the exact command below into a terminal in the right repo."
W ""
$repoNames = @(@($items | ForEach-Object { $_.repo }) | Sort-Object -Unique)
foreach ($rn in $repoNames) {
  $grpItems = @($items | Where-Object { $_.repo -eq $rn })
  W ("## {0} ({1})" -f $rn, $grpItems.Count); W ""
  foreach ($it in $grpItems) {
    W ("- **{0}** ({1}h ago, {2})" -f $it.topic, $it.ageHours, $it.status)
    W ("  - ``cd `"{0}`" ; {1}``" -f $it.cwd, $it.resumeCmd); W ""
  }
}
W "---"
W "Built from disk transcripts per active repo. Sub-sessions (local-command, research/SERP agent prompts) are excluded. Every entry has a transcript on disk (confidence HIGH)."
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.md"), $sb.ToString(), $utf8)

Write-Output ("pane_map written | resumable={0} old={1} repos={2} total={3}" -f $counts.resumable, $counts.old, $counts.repos, $items.Count)
