<#
  build_pane_map.ps1 -- derive the resumable-pane recovery map from DISK TRUTH.

  Single source of truth for the PP Sessions extension and for manual recovery.

  Source of truth = the transcript .jsonl files on disk, NOT the snapshot. The
  session_snapshot.json under-records in TWO ways and we correct BOTH:
    (a) within a repo it misses sids (it only holds sessions the SessionStart
        hub processed) -- fixed by unioning disk transcripts per repo;
    (b) it can drop a whole repo from its active-cwd set (e.g. it listed 0
        TUA-X panes while disk had 6 touched 90 min ago) -- fixed by ALSO
        discovering active repos from disk: any transcript touched within
        RecentHours contributes its own recorded `cwd` to the active set.

  FOUR-TIER MODEL (SCS C80, Owner-approved 2026-07-06). Each pane is classed by
  its INTERNAL-timestamp age (content, immune to batch mtime-touch) into:
    OPEN-NOW : in the snapshot live-registry OR a real turn landed <= LiveMinutes
               ago. An open tab right now -- at risk on reload.
    ACTIVE   : real turn within ActiveMinutes (default 2h). Worked-on today.
    RECENT   : real turn within RecentDays (default 7d). A reopen candidate.
    ARCHIVE  : older content that a batch mtime-touch dragged into the collection
               window. NOT shown in the panel -- written to pane_map_archive.*.
  The panel-facing map (pane_map.json/.md) carries OPEN-NOW+ACTIVE+RECENT only;
  ARCHIVE is the "historial separado". The legacy `live` (==OPEN-NOW) and
  `status` fields are preserved additively so the extension needs no rebuild.
  "54 panes in a repo" was a display bug: it led with the total; the map now
  leads with OPEN-NOW and demotes stale-content panes to ARCHIVE (PR-PANE-MAP-
  LIVE-ONLY-001).

  Versioning + Workspace Session Registry (Sprints 2-3): after writing the
  current map, this script calls tools/pane_map_snapshot.py (fail-open) which
  snapshots to pane_map_history/ when the pane SET changed AND >=15 min elapsed,
  prunes snapshots older than 7 days, and appends a workspace_sessions.jsonl line
  recording which repos held OPEN-NOW panes at that instant.

  Outputs (all under ~/.claude/state):
    pane_map.json            machine-readable, read by the PP Sessions extension
    pane_map.md              human-readable recovery map, grouped by repo
    pane_map_archive.json    ARCHIVE-tier panes (separated history)
    pane_map_archive.md      human-readable archive
    reload_recovery_card.md  paste-ready resume commands, grouped by repo

  Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools/build_pane_map.ps1
#>
[CmdletBinding()]
param(
  [string]$StateDir = (Join-Path $env:USERPROFILE ".claude\state"),
  [string]$ProjBase = (Join-Path $env:USERPROFILE ".claude\projects"),
  [int]$RecentHours = 24,       # repo-discovery window (disk-discovered active cwds)
  [int]$RecentDays  = 7,        # pane collection window + RECENT tier boundary
  [int]$LiveMinutes = 12,       # OPEN-NOW threshold (anti-false-LIVE floor -- proven)
  [int]$ActiveMinutes = 120,    # ACTIVE tier threshold (2h)
  [string]$TabOrderFile = (Join-Path $StateDir "tab_order.json")
)
$ErrorActionPreference = "Stop"

# D5 session-active gate (SCS strategic-gaps): the pane map is regenerated at
# SessionStart, and with no Claude session active recently there are no live panes
# to (re)map -- so skip the full build when idle. Internal-timestamp based
# (session_active.py), NOT file mtime. Fail-open: skip ONLY on an explicit IDLE
# (exit 1); any guard error builds as before. The last active-build still marks the
# open panes for recovery (idle = no new turns, so the map does not go stale).
try {
  $__saPy = Join-Path $env:LOCALAPPDATA 'Programs\Python\Python312\python.exe'
  if (-not (Test-Path $__saPy)) { $__c = Get-Command python -ErrorAction SilentlyContinue; if ($__c) { $__saPy = $__c.Source } }
  $__saGuard = Join-Path $PSScriptRoot 'session_active.py'
  if ((Test-Path $__saPy) -and (Test-Path $__saGuard)) {
    & $__saPy $__saGuard --quiet 2>$null
    if ($LASTEXITCODE -eq 1) { exit 0 }
  }
} catch { }

$nowUtc = (Get-Date).ToUniversalTime()
$OldHours = 48                   # legacy status boundary (RESUMABLE/OLD) -- unchanged
$RecentMin = $RecentDays * 24 * 60

# Sub-session prefixes: a transcript whose first user message starts with one of
# these is NOT an interactive tab (it is a local-command shell-out or a research
# sub-agent spawned inside a tab). Matched as substrings against the first user
# message. Distinctive enough not to false-positive on a real tab.
$SUB_PREFIXES = @(
  'messages below were generated by the user while running local commands',
  'expert and insightful researcher',
  'contents from a SERP search',
  'generate a list of SERP',
  'generate a list of search queries'
)

function Get-SessionMeta($jsonl) {
  # Streams the head of the transcript: returns topic, isSub. Bounded scan.
  $topic = ""; $firstUser = ""; $n = 0
  foreach ($ln in [System.IO.File]::ReadLines($jsonl, [System.Text.Encoding]::UTF8)) {
    $n++; if ($n -gt 200) { break }
    try { $o = $ln | ConvertFrom-Json -EA Stop } catch { continue }
    if (-not $topic -and $o.type -eq 'summary' -and $o.summary) { $topic = $o.summary }
    if (-not $firstUser -and $o.type -eq 'user' -and $o.message.role -eq 'user') {
      $c = $o.message.content
      if ($c -is [string]) { $t = $c } elseif ($c) { $t = ($c | Where-Object { $_.type -eq 'text' } | Select-Object -First 1).text }
      if ($t) { $firstUser = ($t -replace '<[^>]+>', ' ' -replace '\s+', ' ').Trim() }
    }
    if ($topic -and $firstUser) { break }
  }
  $isSub = $false
  foreach ($p in $SUB_PREFIXES) { if ($firstUser -like ('*' + $p + '*')) { $isSub = $true; break } }
  if (-not $topic) { $topic = $firstUser }
  $topic = ($topic -replace '[^\x20-\x7E]', ' ' -replace '\s+', ' ').Trim()
  if ($topic.Length -gt 90) { $topic = $topic.Substring(0, 90) + '...' }
  return @{ topic = $topic; isSub = $isSub }
}

function Get-TranscriptCwd($jsonl) {
  # Reads the transcript's own recorded cwd (cheap regex, no full JSON parse).
  $n = 0
  foreach ($ln in [System.IO.File]::ReadLines($jsonl, [System.Text.Encoding]::UTF8)) {
    $n++; if ($n -gt 40) { break }
    if ($ln -match '"cwd"\s*:\s*"((?:[^"\\]|\\.)*)"') { return ($matches[1] -replace '\\\\', '\') }
  }
  return $null
}

function Get-LastInternalAgeMin($jsonl, $nowUtc) {
  # Age (minutes) of the transcript's NEWEST internal "timestamp" record -- i.e.
  # when a real conversation turn last landed, NOT the file's LastWriteTime.
  # File mtime is unreliable for liveness: any batch sweep (heartbeat merger,
  # backup, git checkout, AV scan) rewrites mtimes en masse and makes every
  # transcript look "written seconds ago" (proven 2026-07-06: 35 files shared one
  # mtime spike while their real last turn was 14h-7d old). The internal timestamp
  # is content, so a metadata-only touch cannot forge it. Reads a bounded tail.
  try {
    $fs = [System.IO.File]::Open($jsonl, 'Open', 'Read', 'ReadWrite')
    try {
      $len = $fs.Length
      $back = [Math]::Min($len, 200000)
      [void]$fs.Seek($len - $back, 'Begin')
      $buf = New-Object byte[] $back
      [void]$fs.Read($buf, 0, $back)
    } finally { $fs.Close() }
    $text = [System.Text.Encoding]::UTF8.GetString($buf)
    $lastTs = $null
    foreach ($m in [regex]::Matches($text, '"timestamp"\s*:\s*"([^"]+)"')) { $lastTs = $m.Groups[1].Value }
    if ($lastTs) {
      $t = [datetime]::Parse($lastTs, $null,
        ([System.Globalization.DateTimeStyles]::AdjustToUniversal -bor [System.Globalization.DateTimeStyles]::AssumeUniversal))
      return ($nowUtc - $t).TotalMinutes
    }
  } catch { }
  return [double]::PositiveInfinity
}

# 1. active repos = snapshot cwds UNION cwds discovered from recent disk transcripts
$snapPath = Join-Path $StateDir "session_snapshot.json"
$activeCwds = @{}
$snap = $null
$snapSids = @{}
if (Test-Path $snapPath) {
  $snap = Get-Content $snapPath -Raw -Encoding UTF8 | ConvertFrom-Json
  foreach ($p in $snap) {
    if ($p.cwd) { $activeCwds[$p.cwd] = $true }
    if ($p.session_id) { $snapSids[$p.session_id] = $true }   # live registry
  }
}
# disk discovery: any project dir holding a transcript touched within RecentHours
# contributes its own recorded cwd -- this rescues repos the snapshot dropped.
foreach ($dir in (Get-ChildItem $ProjBase -Directory -EA SilentlyContinue)) {
  $recent = Get-ChildItem $dir.FullName -Filter *.jsonl -File -EA SilentlyContinue |
    Where-Object { ($nowUtc - $_.LastWriteTime.ToUniversalTime()).TotalHours -le $RecentHours }
  foreach ($rf in $recent) {
    $cwd = Get-TranscriptCwd $rf.FullName
    if ($cwd -and (Test-Path $cwd)) { $activeCwds[$cwd] = $true }
  }
}

# 2+3. per repo: union snapshot sids with disk transcripts within RecentDays;
#      filter subs; classify into the four tiers by internal-timestamp age.
$seen = @{}; $items = @()
foreach ($cwd in $activeCwds.Keys) {
  $enc = ($cwd -replace '[^a-zA-Z0-9]', '-')
  $pd = Join-Path $ProjBase $enc
  if (-not (Test-Path $pd)) { continue }
  $repo = Split-Path $cwd -Leaf
  $files = Get-ChildItem $pd -Filter *.jsonl -File -EA SilentlyContinue |
    Where-Object { ($nowUtc - $_.LastWriteTime.ToUniversalTime()).TotalHours -le $RecentMin / 60 }
  foreach ($f in $files) {
    $sid = $f.BaseName
    if ($seen.ContainsKey($sid)) { continue }
    $ageH = ($nowUtc - $f.LastWriteTime.ToUniversalTime()).TotalHours
    $inSnap = $snapSids.ContainsKey($sid)
    # collection gate: keep transcripts touched within RecentDays OR still
    # registered in the snapshot (idle-but-open tabs).
    if ($ageH -gt ($RecentDays * 24) -and -not $inSnap) { continue }
    $meta = Get-SessionMeta $f.FullName
    if ($meta.isSub) { continue }                          # not a tab
    $seen[$sid] = $true
    $status = if ($ageH -gt $OldHours) { "OLD" } else { "RESUMABLE" }
    # Tier from INTERNAL-timestamp age (content), NOT file mtime -- a batch
    # mtime-touch forges mtime-based liveness (RCA 2026-07-06,
    # T-PANE-MAP-FALSE-LIVE-MTIME-001). $ageH/$ageMin retained for display only.
    $internalAgeMin = Get-LastInternalAgeMin $f.FullName $nowUtc
    $tier =
      if ($inSnap -or $internalAgeMin -le $LiveMinutes) { 'OPEN-NOW' }
      elseif ($internalAgeMin -le $ActiveMinutes) { 'ACTIVE' }
      elseif ($internalAgeMin -le $RecentMin) { 'RECENT' }
      else { 'ARCHIVE' }
    $isLive = ($tier -eq 'OPEN-NOW')
    $items += [ordered]@{
      repo = $repo; cwd = $cwd; sessionId = $sid; topic = $meta.topic
      lastActivity = $f.LastWriteTime.ToUniversalTime().ToString('o')
      ageHours = [math]::Round($ageH, 1)
      internalAgeMin = if ([double]::IsInfinity($internalAgeMin)) { -1 } else { [math]::Round($internalAgeMin, 1) }
      status = $status; live = $isLive; tier = $tier
      resumeCmd = "kclaude --resume $sid"; confidence = "HIGH"
    }
  }
}

# partition: panel-facing (non-archive) vs separated history (archive)
$mainItems = @($items | Where-Object { $_.tier -ne 'ARCHIVE' })
$archiveItems = @($items | Where-Object { $_.tier -eq 'ARCHIVE' } | Sort-Object @{ Expression = { [datetime]$_.lastActivity }; Descending = $true })

# --- tab-order overlay (SCS C78 addendum v2) --------------------------------
# Lead the panel-facing map with panes in the extension-recorded left-to-right
# tab order (~/.claude/state/tab_order.json). Join key = 8-hex sid prefix. Fail-
# open: absent/malformed file or zero matches -> pure lastActivity order.
$tabRank = @{}
if (Test-Path $TabOrderFile) {
  try {
    $to = Get-Content $TabOrderFile -Raw -Encoding UTF8 | ConvertFrom-Json
    $r = 0
    foreach ($t in @($to.tabs)) {
      $pfx = ("" + $t.sidPrefix).ToLower()
      if ($pfx -and -not $tabRank.ContainsKey($pfx)) { $tabRank[$pfx] = $r; $r++ }
    }
  } catch { $tabRank = @{} }   # malformed JSON -> fail-open to lastActivity
}
function Get-TabRank($sid) {
  $s = "" + $sid
  $pfx = $s.Substring(0, [Math]::Min(8, $s.Length)).ToLower()
  if ($tabRank.ContainsKey($pfx)) { return $tabRank[$pfx] }
  return [int]::MaxValue
}
# tier order weight (used only for DISPLAY ordering in the .md / card render
# loops below). The JSON `panes` array keeps the historical sort -- tab-rank
# first, then lastActivity desc -- so the extension's contract and the
# V-SORTED-RECENT-FIRST gate (unmatched panes stay lastActivity-desc) hold.
$tierWeight = @{ 'OPEN-NOW' = 0; 'ACTIVE' = 1; 'RECENT' = 2 }
$mainItems = @($mainItems | Sort-Object `
  @{ Expression = { Get-TabRank $_.sessionId }; Ascending = $true }, `
  @{ Expression = { [datetime]$_.lastActivity }; Descending = $true })

$byTier = [ordered]@{
  openNow = (@($mainItems | Where-Object { $_.tier -eq 'OPEN-NOW' })).Count
  active  = (@($mainItems | Where-Object { $_.tier -eq 'ACTIVE' })).Count
  recent  = (@($mainItems | Where-Object { $_.tier -eq 'RECENT' })).Count
  archive = $archiveItems.Count
}
$counts = [ordered]@{
  resumable = ($mainItems | Where-Object { $_.status -eq 'RESUMABLE' }).Count
  old       = ($mainItems | Where-Object { $_.status -eq 'OLD' }).Count
  live      = $byTier.openNow
  repos     = (@($mainItems | ForEach-Object { $_.repo }) | Sort-Object -Unique).Count
  byTier    = $byTier
}
$payload = [ordered]@{ generatedAt = $nowUtc.ToString('o'); source = "transcripts-on-disk (active repos = snapshot UNION disk-discovered cwds); 4-tier by internal-ts"; liveMinutes = $LiveMinutes; activeMinutes = $ActiveMinutes; recentDays = $RecentDays; counts = $counts; panes = $mainItems }

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.json"), ($payload | ConvertTo-Json -Depth 6), $utf8)

$archivePayload = [ordered]@{ generatedAt = $nowUtc.ToString('o'); note = "ARCHIVE tier -- content older than RecentDays, dragged into the window by a batch mtime-touch. Separated from the panel-facing map."; count = $archiveItems.Count; panes = $archiveItems }
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map_archive.json"), ($archivePayload | ConvertTo-Json -Depth 6), $utf8)

$repoNames = @(@($mainItems | ForEach-Object { $_.repo }) | Sort-Object -Unique)

# --- pane_map.md : human-readable recovery map, grouped by repo ---
$sb = New-Object System.Text.StringBuilder
function W($s) { [void]$sb.AppendLine($s) }
W "# PP PANE MAP -- Recovery Safety Net"
W ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local | Source: transcripts-on-disk | 4-tier by internal-timestamp age")
W ("Tiers: **OPEN-NOW** (<= {0} min -- open tab, at risk on reload) | **ACTIVE** (<= {1} min) | **RECENT** (<= {2} d). ARCHIVE is separated -> pane_map_archive.md." -f $LiveMinutes, $ActiveMinutes, $RecentDays)
W ("Totals: {0} OPEN-NOW | {1} ACTIVE | {2} RECENT | {3} archived | {4} repos" -f $byTier.openNow, $byTier.active, $byTier.recent, $byTier.archive, $counts.repos)
W "If a Cursor reload loses a pane, paste the exact command below into a terminal in the right repo."
W ""
foreach ($rn in $repoNames) {
  # DISPLAY order within a repo: OPEN-NOW leads, then ACTIVE, then RECENT, each
  # most-recent-first. (JSON order is unchanged; this is render-only.)
  $grpItems = @($mainItems | Where-Object { $_.repo -eq $rn } | Sort-Object `
    @{ Expression = { $tierWeight[$_.tier] }; Ascending = $true }, `
    @{ Expression = { [datetime]$_.lastActivity }; Descending = $true })
  $oN = @($grpItems | Where-Object { $_.tier -eq 'OPEN-NOW' }).Count
  $aC = @($grpItems | Where-Object { $_.tier -eq 'ACTIVE' }).Count
  $rC = @($grpItems | Where-Object { $_.tier -eq 'RECENT' }).Count
  W ("## {0} -- {1} OPEN-NOW / {2} active / {3} recent" -f $rn, $oN, $aC, $rC); W ""
  foreach ($it in $grpItems) {
    W ("- **[{0}] {1}** ({2}h ago, {3})" -f $it.tier, $it.topic, $it.ageHours, $it.status)
    W ("  - ``cd `"{0}`" ; {1}``" -f $it.cwd, $it.resumeCmd); W ""
  }
}
W "---"
W "Built from disk transcripts. Active repos = snapshot UNION disk-discovered cwds. Sub-sessions (local-command, research/SERP agent prompts) are excluded. Tier = internal-timestamp age (immune to batch mtime-touch). Every entry has a transcript on disk (confidence HIGH)."
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map.md"), $sb.ToString(), $utf8)

# --- pane_map_archive.md : separated history ---
$ab = New-Object System.Text.StringBuilder
function A($s) { [void]$ab.AppendLine($s) }
A "# PP PANE MAP -- ARCHIVE (separated history)"
A ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local | " + $archiveItems.Count + " panes")
A "These have a transcript touched within the collection window but whose LAST REAL TURN is older than the RECENT boundary (a batch mtime-touch dragged them in). Not shown in the panel; reopen from here if you need them."
A ""
foreach ($it in $archiveItems) {
  A ("- **{0}** [{1}] ({2}h ago by mtime, internal {3} min)" -f $it.topic, $it.repo, $it.ageHours, $it.internalAgeMin)
  A ("  - ``cd `"{0}`" ; {1}``" -f $it.cwd, $it.resumeCmd)
}
[System.IO.File]::WriteAllText((Join-Path $StateDir "pane_map_archive.md"), $ab.ToString(), $utf8)

# --- reload_recovery_card.md : paste-ready resume commands (OPEN-NOW + ACTIVE) ---
$cb = New-Object System.Text.StringBuilder
function C($s) { [void]$cb.AppendLine($s) }
C "=== RELOAD RECOVERY CARD ==="
C ("Generated: " + (Get-Date).ToString('yyyy-MM-dd HH:mm') + " local  (" + $byTier.openNow + " OPEN-NOW / " + $byTier.active + " active / " + $counts.repos + " repos)")
C ""
C ("[OPEN-NOW] = an OPEN tab right now (snapshot or real turn < {0} min ago); these are the ones a reload can drop." -f $LiveMinutes)
C "[ACTIVE] = worked on today, still resumable. Every command resumes the EXACT conversation (no 'History restored')."
C "If a pane does NOT survive Ctrl+Shift+P -> Reload Window, paste its command in a terminal in the right repo."
C ""
foreach ($rn in $repoNames) {
  $grp = @($mainItems | Where-Object { $_.repo -eq $rn -and ($_.tier -eq 'OPEN-NOW' -or $_.tier -eq 'ACTIVE') } | Sort-Object `
    @{ Expression = { $tierWeight[$_.tier] }; Ascending = $true }, `
    @{ Expression = { [datetime]$_.lastActivity }; Descending = $true })
  if ($grp.Count -eq 0) { continue }
  $oN = @($grp | Where-Object { $_.tier -eq 'OPEN-NOW' }).Count
  C ("---- {0} ({1} OPEN-NOW / {2} shown) ----" -f $rn, $oN, $grp.Count)
  foreach ($it in $grp) {
    C ("  # [{0}] {1}  ({2}h ago)" -f $it.tier, $it.topic, $it.ageHours)
    C ("  cd `"{0}`" ; {1}" -f $it.cwd, $it.resumeCmd)
    C ""
  }
}
C "=== END CARD ==="
[System.IO.File]::WriteAllText((Join-Path $StateDir "reload_recovery_card.md"), $cb.ToString(), $utf8)

# --- versioning + workspace registry (Sprints 2-3) : fail-open ---------------
# Snapshot the just-written map to pane_map_history/ when the pane SET changed
# AND >= 15 min elapsed; prune snapshots older than 7 days; append a workspace
# session-registry line. Any failure here MUST NOT fail the build (the current
# map is already written above). Python resolved via PATH, then canonical path.
try {
  $py = (Get-Command python -EA SilentlyContinue).Source
  if (-not $py) { $py = "C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe" }
  $snapScript = Join-Path $PSScriptRoot "pane_map_snapshot.py"
  if ((Test-Path $py) -and (Test-Path $snapScript)) {
    & $py $snapScript --snapshot --state-dir $StateDir 2>$null | Out-Null
  }
} catch { }   # versioning is best-effort; the live map is already on disk

Write-Output ("pane_map written | openNow={0} active={1} recent={2} archive={3} repos={4} main={5}" -f $byTier.openNow, $byTier.active, $byTier.recent, $byTier.archive, $counts.repos, $mainItems.Count)
