#!/usr/bin/env python3
"""conversation_quality_audit.py -- behavioral (qualitative) inefficiency audit.

Complement of token_corpus_audit.py: that one measured VOLUME (tokens, cache),
this one measures BEHAVIOR -- 5 repeated conversational inefficiency patterns in
the real .jsonl content. Reuses token_corpus_audit.iter_transcripts (no reader
re-implementation). Every "tokens spent" figure is the REAL
message.usage.output_tokens of the offending assistant turn -- measured.

Patterns (design: vault/plans/conversation-quality-audit-2026-07-03.md):
  P1 agent self-correction   -- consecutive assistant turns, 2nd corrects 1st
  P2 owner repeats instruction-- two similar Owner msgs, agent didn't act between
  P3 duplicate reality scan  -- same repo re-scans within 7 days (>0.6 overlap)
  P4 plan->exec divergence   -- approved plan's files != executed files (LOW conf)
  P5 question already answered-- agent re-asks a resolved question in-session

FP hardening (post-first-run audit 2026-07-03):
  - P2 excludes harness-injected user wrappers (<local-command-caveat> etc.):
    those are not Owner instructions and overlap only on shared boilerplate.
  - P5 extracts the interrogative CLAUSE (needs a question cue), not any turn
    that merely contains a '?': kills preflight/table false positives.
  - P4 requires a plan-intent cue near the path list and dedups identical
    (planned,exec) pairs per session: kills status-mention re-counts.

Reporting: freq < 5 -> "not found significantly", no fix. freq >= 5 -> concrete
fix. Evidence snippets capped at 3 lines. Fail-open per-file.

Usage:
  python tools/conversation_quality_audit.py                  # stdout summary
  python tools/conversation_quality_audit.py --report out.md
  python tools/conversation_quality_audit.py --proj-base <dir>  # testing
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

_HERE = Path(__file__).resolve().parent


def _load(name):
    spec = importlib.util.spec_from_file_location(name, _HERE / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_TCA = _load("token_corpus_audit")
iter_transcripts = _TCA.iter_transcripts

FIX_MIN = 5  # freq below this -> no fix proposed

_STOP = set("""the a an of to and or in on for with is are was were be been
this that it its as at by from we you i he she they them our your my me
if then else so do does did done can could would should will just not no
yes ok si el la los las de que un una y o en con es por para se lo su al
del mas más como este esta esto ese esa eso muy ya lo the""".split())

_CORRECTION_RX = re.compile(
    r"\bi\s+made\s+an?\s+error\b|\bmy\s+mistake\b|\bthat\s+was\s+incorrect\b"
    r"|\blet\s+me\s+fix\s+that\b|\bcorrection:\b|\bi\s+was\s+wrong\b"
    r"|\bi\s+apologi[sz]e\b|\bme\s+equivoqu[eé]\b|\berror\s+m[ií]o\b"
    r"|\bme\s+equivoco\b|\bcorrijo\b|\ben\s+realidad\s+me\b"
    r"|\bstrike\s+that\b|\bscratch\s+that\b", re.I)

_SCAN_RX = re.compile(
    r"reality\s+scan|fase\s*-?\s*1|preflight|leer\s+antes\s+de"
    r"|read\s+before|corpus\s+scan", re.I)

_APPROVAL_RX = re.compile(
    r"^\s*(?:s[ií]|ok(?:ay)?|adelante|go|aprobado|dale|hazlo|perfecto|"
    r"vale|listo|continua|continúa|yes|proceed|approved|👍)\b", re.I)

_PATH_RX = re.compile(r"\b[\w./-]+\.(?:py|js|ts|tsx|jsx|md|json|yml|yaml|"
                      r"toml|sh|ps1|sql|css|html|txt|cfg|ini)\b")

# Harness-injected user wrappers -- NOT genuine Owner instructions.
_HARNESS_RX = re.compile(
    r"<local-command-caveat>|<command-name>|<command-message>|<command-args>"
    r"|<bash-input>|<bash-stdout>|<local-command-stdout>|<system-reminder>"
    r"|generated by the user while running local commands", re.I)

# Interrogative cue -- a genuine question directed at the Owner.
_QCUE_RX = re.compile(
    r"\b(should\s+i|should\s+we|which\s+\w+|could\s+you|can\s+you|do\s+you"
    r"|would\s+you|which\s+(?:one|option|approach)|what\s+do\s+you"
    r"|how\s+should|prefer|confirm|approve"
    r"|quieres|prefieres|deber[ií]a(?:mos)?|te\s+parece|cu[aá]l|apruebas"
    r"|confirmas|proceed\s+with|opci[oó]n)\b|¿", re.I)

_PLAN_CUE_RX = re.compile(
    r"\bplan\b|propuesta|micro-?commit|voy\s+a\b|i\s+will\b|i'?ll\b"
    r"|\bsteps?\b|\bpasos?\b|implementar|ejecutar[ée]|fase\s+\d", re.I)


def _sig(text: str) -> set:
    words = re.findall(r"[a-záéíóúñü][a-záéíóúñü0-9_-]{1,}", (text or "").lower())
    return {w for w in words if w not in _STOP and len(w) > 2}


def _jac(a: set, b: set) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def _snippet(text: str, maxlines: int = 3, width: int = 110) -> str:
    out = []
    for ln in (text or "").split("\n"):
        ln = ln.strip()
        if not ln:
            continue
        out.append(ln[:width])
        if len(out) >= maxlines:
            break
    return " / ".join(out)


def _question_clause(text: str) -> str:
    """Return the interrogative clause (with a question cue) or '' if the turn
    is not genuinely asking. Splits on '?' and keeps the ~220 chars before each
    '?' that contain a cue and >=5 words. Kills 'turn merely contains a ?' FPs."""
    if "?" not in text:
        return ""
    # A real question = a single sentence (no . ! ? or newline inside) ending
    # in '?', 5-40 words, carrying an interrogative cue. Bounding to one
    # sentence kills the "220 chars of analysis ending at an incidental ?" FP.
    for m in re.finditer(r"([^.!?\n]{5,200})\?", text):
        clause = m.group(1).strip()
        wc = len(clause.split())
        if 5 <= wc <= 40 and _QCUE_RX.search(clause):
            return clause
    return ""


def _parse_ts(s):
    if not isinstance(s, str) or len(s) < 19:
        return None
    try:
        d = datetime.fromisoformat(s.replace("Z", "+00:00"))
        return d if d.tzinfo else d.replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def _extract(msg):
    """(text, out_tokens, tools, write_paths, is_owner) from one message.

    is_owner is False for harness-injected wrappers (local-command caveats,
    system-reminders) -- those are not Owner instructions."""
    text_parts, tools, writes = [], [], []
    has_tool_result = False
    out_tok = 0
    role = msg.get("role")
    usage = msg.get("usage")
    if isinstance(usage, dict):
        out_tok = usage.get("output_tokens", 0) or 0
    content = msg.get("content")
    if isinstance(content, str):
        text_parts.append(content)
    elif isinstance(content, list):
        for blk in content:
            if not isinstance(blk, dict):
                continue
            bt = blk.get("type")
            if bt == "text" and isinstance(blk.get("text"), str):
                text_parts.append(blk["text"])
            elif bt == "tool_result":
                has_tool_result = True
            elif bt == "tool_use":
                nm = blk.get("name") or ""
                tools.append(nm)
                if nm in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
                    fp = (blk.get("input") or {}).get("file_path")
                    if isinstance(fp, str):
                        writes.append(fp)
    text = "\n".join(text_parts).strip()
    is_owner = (role == "user" and bool(text) and not has_tool_result
                and not _HARNESS_RX.search(text[:200]))
    return text, out_tok, tools, writes, is_owner


def parse_conversation(fp: Path) -> dict | None:
    try:
        raw = fp.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    msgs = []
    for line in raw.split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        msg = entry.get("message")
        if not isinstance(msg, dict):
            continue
        text, out_tok, tools, writes, is_owner = _extract(msg)
        role = msg.get("role")
        if role not in ("user", "assistant"):
            continue
        msgs.append({
            "role": role, "text": text, "out": out_tok, "tools": tools,
            "writes": writes, "is_owner": is_owner,
            "ts": _parse_ts(entry.get("timestamp")), "idx": len(msgs),
        })
    if not msgs:
        return None
    last = next((m["ts"] for m in reversed(msgs) if m["ts"]), None)
    date = last.strftime("%Y-%m-%d") if last else "unknown"
    return {"sid": fp.stem, "project": fp.parent.name, "date": date,
            "msgs": msgs}


class _Pat:
    def __init__(self, name, conf="normal"):
        self.name = name
        self.conf = conf
        self.count = 0
        self.tokens = 0
        self.examples = []  # (cost, project, sid, snippet)

    def hit(self, cost, project, sid, snippet):
        self.count += 1
        self.tokens += cost
        self.examples.append((cost, project[:26], sid[:8], snippet))
        self.examples.sort(key=lambda x: x[0], reverse=True)
        self.examples = self.examples[:3]


def _detect(session, pats, scan_index):
    msgs = session["msgs"]
    proj, sid = session["project"], session["sid"]

    last_asst = None          # idx into msgs of previous assistant turn
    last_owner = -1           # idx of last genuine owner msg
    asst_questions = []       # (idx, sigwords) for P5
    owner_msgs = []           # (idx, sigwords) for P2
    pending_plan = None       # planned path-name set (P4)
    pending_approve = False
    p4_seen = set()           # dedupe (frozenset planned, frozenset exec)

    for m in msgs:
        i = m["idx"]
        if m["is_owner"]:
            # ---- P2: owner repeats instruction ----
            sg = _sig(m["text"])
            if len(sg) >= 5:
                for (pj, psg) in owner_msgs[-12:]:
                    if pj == i - 1:
                        continue  # adjacent
                    if _jac(sg, psg) > 0.7:
                        between = [x for x in msgs[pj + 1:i]
                                   if x["role"] == "assistant"]
                        if between and all(not x["tools"] for x in between):
                            cost = sum(x["out"] for x in between)
                            pats["P2"].hit(cost, proj, sid, _snippet(m["text"]))
                            break
                owner_msgs.append((i, sg))
            # ---- P4: short approval after a plan ----
            if pending_plan is not None and _APPROVAL_RX.search(m["text"]) \
                    and len(m["text"].split()) < 20:
                pending_approve = True
            last_owner = i
            continue

        if m["role"] != "assistant":
            continue

        head = m["text"][:240]
        # ---- P1: self-correction (consecutive assistant, no owner between) ----
        if _CORRECTION_RX.search(head) and last_asst is not None \
                and last_owner < last_asst:
            cost = msgs[last_asst]["out"] + m["out"]
            pats["P1"].hit(cost, proj, sid, _snippet(head))

        # ---- P5: repeated question (interrogative clause, cue-gated) ----
        qc = _question_clause(m["text"])
        if qc:
            qsig = _sig(qc)
            if len(qsig) >= 4:
                for (eidx, esig) in asst_questions:
                    if _jac(qsig, esig) > 0.7 and any(
                            x["is_owner"] for x in msgs[eidx + 1:i]):
                        pats["P5"].hit(m["out"], proj, sid, _snippet(qc))
                        break
                asst_questions.append((i, qsig))

        # ---- P4: plan->exec divergence (plan-cue gated, deduped) ----
        if pending_approve and pending_plan is not None and m["writes"]:
            executed = frozenset(Path(w).name for w in m["writes"])
            planned = frozenset(Path(p).name for p in pending_plan)
            key = (planned, executed)
            if planned and _jac(set(planned), set(executed)) < 0.4 \
                    and key not in p4_seen:
                p4_seen.add(key)
                pats["P4"].hit(m["out"], proj, sid,
                               f"planned={sorted(planned)[:3]} "
                               f"exec={sorted(executed)[:3]}")
            pending_plan, pending_approve = None, False
        # arm a plan only when the turn shows plan INTENT + a path list
        paths = set(_PATH_RX.findall(m["text"]))
        if len(paths) >= 2 and _PLAN_CUE_RX.search(m["text"]) \
                and re.search(r"^\s*(?:[-*]|\d+[.)])\s", m["text"], re.M):
            pending_plan, pending_approve = paths, False

        last_asst = i

    # ---- P3: cross-session duplicate scan (index first-assistant scans) ----
    first_asst = next((m for m in msgs if m["role"] == "assistant"
                       and m["text"]), None)
    if first_asst and _SCAN_RX.search(first_asst["text"][:600]):
        scan_index[proj].append({
            "sid": sid, "date": session["date"],
            "sig": _sig(first_asst["text"][:600]),
            "out": first_asst["out"], "text": first_asst["text"],
        })


def _resolve_p3(scan_index, pat):
    for proj, scans in scan_index.items():
        scans = [s for s in scans if s["date"] != "unknown"]
        scans.sort(key=lambda s: s["date"])
        for a in range(len(scans)):
            for b in range(a + 1, len(scans)):
                try:
                    d1 = datetime.strptime(scans[a]["date"], "%Y-%m-%d")
                    d2 = datetime.strptime(scans[b]["date"], "%Y-%m-%d")
                except ValueError:
                    continue
                if (d2 - d1).days > 7:
                    break
                if _jac(scans[a]["sig"], scans[b]["sig"]) > 0.6:
                    pat.hit(scans[b]["out"], proj, scans[b]["sid"],
                            _snippet(scans[b]["text"]))
                    break


def pm03_health(state_dir=None):
    """L-SELFCORR/P5 root-cause probe (C70): is the PM-03 Findings Bus actually
    populated? P5 (repeated in-session question, 90k tok) is supposed to be
    prevented by RedundancyTax consulting the bus -- but the bus only helps if it
    HOLDS findings. Measures real population across all repos. `wired` is False
    when the bus has zero findings anywhere: then P5's fix is 'WIRE PM-03'
    (Owner-side SessionStart digest + Stop publish, HR-001), NOT a new gate.
    Fail-open: any error -> unknown (wired=None)."""
    try:
        d = Path(state_dir) if state_dir else (
            Path.home() / ".claude" / "state" / "parallel_mesh")
        if not d.is_dir():
            return {"bus_dir": str(d), "files": 0, "findings": 0, "wired": False}
        files = list(d.glob("findings_bus_*.jsonl"))
        total = 0
        for f in files:
            try:
                total += sum(1 for ln in f.read_text(
                    encoding="utf-8", errors="replace").split("\n") if ln.strip())
            except OSError:
                continue
        return {"bus_dir": str(d), "files": len(files), "findings": total,
                "wired": total > 0}
    except Exception:  # noqa: BLE001 -- fail-open
        return {"bus_dir": None, "files": 0, "findings": 0, "wired": None}


def audit(proj_base=None, state_dir=None):
    pats = {
        "P1": _Pat("agent self-correction"),
        "P2": _Pat("owner repeats instruction"),
        "P3": _Pat("duplicate reality scan (cross-session)"),
        "P4": _Pat("plan->execution divergence", conf="LOW"),
        "P5": _Pat("question already answered"),
    }
    scan_index = defaultdict(list)
    n = 0
    for fp in iter_transcripts(proj_base):
        s = parse_conversation(fp)
        if not s:
            continue
        n += 1
        _detect(s, pats, scan_index)
    _resolve_p3(scan_index, pats["P3"])
    return {"generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "n_sessions": n, "pats": pats, "pm03": pm03_health(state_dir)}


_FIX = {
    "P1": "Verify before emitting (superpowers:verification-before-completion). "
          "A self-correction pair = the first turn shipped an unverified claim. "
          "Gate: observe evidence before the DONE/assert turn.",
    "P2": "The agent talked without acting between two identical Owner asks. "
          "On any imperative, the next turn must contain the tool_use that "
          "executes it, or an explicit blocker -- never prose-only acknowledgement. "
          "NOTE: hits concentrate in error-retry sessions (Owner re-pastes the "
          "same unresolved blocker); same failure family, real signal.",
    "P3": "Consult the Repo Shared Brain (PM-01) before launching a new scan. "
          "RepoBrainConsumer.get_or_generate is the entry point; only rescan on "
          "brain-miss or stale.",
    "P4": "Bind execution to the approved plan's file list (HR-ONESHOT-002 "
          "fidelity lock). If executed files diverge >40% from plan, pause and "
          "re-confirm rather than silently redoing. CAVEAT (LOW conf): 'planned' "
          "= all paths in the plan block, INCLUDING read-context files, so this "
          "count is an UPPER BOUND; each hit needs manual review, not auto-fix.",
    "P5": "Consult the Findings Bus (PM-03) before asking. "
          "RedundancyTax.reason_or_reuse covers already-answered questions in "
          "the same session.",
}


def build_report(d):
    L = ["# Conversation Quality Audit -- Behavioral Report", "",
         f"**Generated:** {d['generated']}  ",
         f"**Sessions analyzed:** {d['n_sessions']}  ",
         "**Source:** `~/.claude/projects/*/*.jsonl` content (real turns).  ",
         "**Cost = real `message.usage.output_tokens` of the offending turn.**  ",
         "**FP-hardened:** harness wrappers excluded (P2), interrogative-clause "
         "gating (P5), plan-intent cue + dedupe (P4).",
         ""]
    ranked = sorted(d["pats"].values(), key=lambda p: p.tokens, reverse=True)
    L.append("## Ranking by total token cost")
    L.append("")
    L.append("| Pattern | Freq | Total tokens | Confidence | Fix? |")
    L.append("|---|---|---|---|---|")
    for p in ranked:
        fixq = "yes" if p.count >= FIX_MIN else "no (<5)"
        L.append(f"| {p.name} | {p.count} | {p.tokens:,} | {p.conf} | {fixq} |")
    L.append("")
    for key in ("P1", "P2", "P3", "P4", "P5"):
        p = d["pats"][key]
        L.append(f"## {key} -- {p.name}")
        L.append("")
        if p.count < FIX_MIN:
            L.append(f"Frequency **{p.count}** (< {FIX_MIN}). "
                     "Not found with significant frequency -- **no fix proposed.**")
            L.append("")
            continue
        L.append(f"- Frequency: **{p.count}**, total cost **{p.tokens:,}** "
                 f"tokens, confidence: {p.conf}")
        L.append("- Top examples (cost / project / sid / evidence <=3 lines):")
        for (cost, proj, sid, snip) in p.examples:
            L.append(f"  - `{cost:,}` `{proj}` `{sid}` -- {snip}")
        L.append(f"- **Fix:** {_FIX[key]}")
        L.append("")
    L.append("---")
    L.append("*tools/conversation_quality_audit.py -- behavioral axis.*")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--report", default=None)
    ap.add_argument("--proj-base", default=None)
    args = ap.parse_args(argv)
    d = audit(proj_base=args.proj_base)
    print(f"sessions: {d['n_sessions']}")
    for key in ("P1", "P2", "P3", "P4", "P5"):
        p = d["pats"][key]
        flag = "FIX" if p.count >= FIX_MIN else "skip"
        print(f"  {key} {p.name[:34]:34s} freq={p.count:4d} "
              f"tok={p.tokens:>10,} [{flag}]")
    pm = d["pm03"]
    print(f"  PM-03 bus: files={pm['files']} findings={pm['findings']} "
          f"wired={pm['wired']}"
          + ("  -> P5 fix = WIRE PM-03 (bus inert)"
             if pm["wired"] is False else ""))
    if args.report:
        out = Path(args.report)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(build_report(d), encoding="utf-8")
        print(f"report -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
