#!/usr/bin/env python3
"""Catalog every memory file that has no pointer in its project's MEMORY.md.

Spec: vault/specs/prompt-recall.md ("Unindexed memories"). On 2026-10-09, 912 memory files
across 12 projects had no index line, and the indexes were already 13-21k chars, so adding a
line per file would have broken the index cap. Each project gets instead:

  MEMORY_CATALOG.md   one line per unindexed file, from its frontmatter (regenerated each run)
  one pointer line    appended to MEMORY.md once, never duplicated

Relevance-based findability comes from modules/gsd_x/recall.py; the catalog makes the same
files visible to anyone reading the index.

    python tools/memory_catalog.py            # report only
    python tools/memory_catalog.py --apply    # write catalogs + pointer lines
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

CATALOG = "MEMORY_CATALOG.md"
INDEXES = ("MEMORY.md", "MEMORY_ARCHIVE.md")
POINTER = ("- [Unindexed memories catalog](MEMORY_CATALOG.md) -- every memory with no line "
           "here, one line each; prompt recall surfaces them by relevance")
_FRONT = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)
DESC_MAX = 160


def describe(path: Path) -> tuple:
    """(name, description) from frontmatter, falling back to the stem and first prose line."""
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    name, desc = path.stem, ""
    m = _FRONT.match(text)
    if m:
        for line in m.group(1).splitlines():
            k, _, v = line.partition(":")
            v = v.strip().strip('"').strip("'")
            if k.strip() == "name" and v:
                name = v
            elif k.strip() == "description" and v:
                desc = v
        text = text[m.end():]
    if not desc:
        desc = next((ln.strip("# ").strip() for ln in text.splitlines() if ln.strip()), "")
    desc = " ".join(desc.split())
    return name, (desc[:DESC_MAX - 3] + "...") if len(desc) > DESC_MAX else desc


def is_index(name: str) -> bool:
    """MEMORY.md, its archive, and sub-indexes it hands off to (MEMORY-windows-exec.md in TUA-X)."""
    return name.startswith("MEMORY") and name != CATALOG


def unindexed(mem: Path) -> list:
    indexed = "".join(f.read_text(encoding="utf-8-sig", errors="replace")
                      for f in mem.glob("*.md") if is_index(f.name))
    return sorted(f for f in mem.glob("*.md")
                  if not is_index(f.name) and f.name != CATALOG and not mentions(indexed, f.name))


def mentions(text: str, name: str) -> bool:
    """`name` appears as a whole filename: x.md must not count as indexed because prefix_x.md is."""
    return re.search(r"(?<![\w.-])%s(?![\w.-])" % re.escape(name), text) is not None


def apply_one(mem: Path, files: list) -> bool:
    """Write the catalog and the pointer. Returns True when MEMORY.md gained the pointer."""
    lines = ["# Unindexed memories catalog", "",
             "Generated by `tools/memory_catalog.py` -- do not edit; a file listed here has no",
             "line in MEMORY.md. Regenerated on each run.", ""]
    for f in files:
        name, desc = describe(f)
        lines.append("- [%s](%s) -- %s" % (name, f.name, desc))
    (mem / CATALOG).write_text("\n".join(lines) + "\n", encoding="utf-8")
    index = mem / "MEMORY.md"
    raw = index.read_text(encoding="utf-8-sig", errors="replace")
    if CATALOG in raw:
        return False
    with index.open("a", encoding="utf-8") as fh:
        fh.write(("" if raw.endswith("\n") else "\n") + POINTER + "\n")
    return True


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    root = Path(argv[argv.index("--root") + 1]) if "--root" in argv else \
        Path.home() / ".claude" / "projects"
    do = "--apply" in argv
    total = pointers = 0
    for mem in sorted(root.glob("*/memory")):
        if not (mem / "MEMORY.md").is_file():
            continue
        files = unindexed(mem)
        if not files and not (mem / CATALOG).exists():
            continue
        total += len(files)
        added = apply_one(mem, files) if do else False
        pointers += added
        print("%4d  %s%s" % (len(files), mem.parent.name, "  +pointer" if added else ""))
    print("unindexed=%d pointers_added=%d mode=%s" % (total, pointers, "apply" if do else "report"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
