#!/usr/bin/env python3
"""rename_sessions.py -- safe retroactive session rename via inline custom-title append.

MECHANISM (forensically verified -- see PR-TRANSCRIPT-RENAME-SAFETY-001):
  Claude Code's /resume picker renders the LATEST
    {"type":"custom-title","customTitle":"<name>","sessionId":"<uuid>"}
  record found in <proj>/<uuid>.jsonl. The .jsonl is an APPEND-ONLY event log;
  the harness never rewrites prior lines. Setting a display name = appending one
  custom-title line. This is exactly what the Ctrl+R rename does, and exactly what
  hooks/mark-live-session.js already does in production (the "voltage" live marker).
  There is NO separate metadata store -- the name lives inline in the transcript.

SAFETY INVARIANT (prefix-byte-identity, NOT whole-file hash):
  A whole-file sha256 CANNOT stay identical after an append -- and would be
  impossible for Claude Code's OWN Ctrl+R rename too, since it appends as well.
  The real, provable guarantee is:
    * the ORIGINAL N bytes remain byte-identical after the write (append never
      touches prior bytes),
    * the file grew by exactly one valid custom-title line,
    * the appended tail decodes to precisely the expected JSON object.
  The tool records sha256(original_bytes[0:N]) BEFORE, then verifies AFTER:
    len(after) == N + len(line)  AND  sha256(after[0:N]) == pre  AND  after[N:] == line
  Any deviation -> truncate the file back to N (full revert) and report FAIL.
  Message content and transcript structure are never modified.

NAMING SOURCE: the session's own ai-title -- a clean Claude-generated summary
  already embedded in the transcript ({"type":"ai-title","aiTitle":"..."}). A
  session is renamed ONLY when its current effective custom-title is absent or a
  bare hex UUID string (the mark-live-session.js fallback that shadows the real
  name in the picker). A genuine Owner Ctrl+R name is NEVER overwritten. Sessions
  with no ai-title are left untouched (no noisy first-prompt fallback).

EXCLUSIONS:
  * sub-sessions (local-command runs, research / SERP agent prompts) -- SUB_PREFIXES,
    the same set build_pane_map.ps1 uses,
  * mislocated copies -- a transcript whose recorded cwd does NOT munge to its
    physical project dir (a resumed-from-elsewhere fork; renaming it would only
    pollute the wrong picker),
  * sessions that already carry a real custom name,
  * sessions with no ai-title,
  * the currently-running session(s) via --skip-sid / env PP_EVT_SID.

Encoding: writes are BINARY appends of UTF-8 (no BOM), LF terminator, no-space
  separators -- byte-compatible with Node's JSON.stringify output in the harness.

Usage:
  python tools/rename_sessions.py --dry-run                # this repo only, writes nothing
  python tools/rename_sessions.py --all --dry-run          # every repo, writes nothing
  python tools/rename_sessions.py --all --apply            # every repo, waves per dir, verified
  optional:
    --repo-prefix        prepend "<repo> -- " to each name (default off: picker is per-project)
    --project <dir>      operate on one specific <proj> dir (default: this repo's project dir)
    --repo <name>        with --all: restrict to project dirs whose repo leaf matches (substring)
    --skip-sid <uuid>    never touch this session id (repeatable); also honours env PP_EVT_SID
    --verbose            show skipped rows too
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

HOME = Path(os.path.expanduser("~"))
PROJECTS_ROOT = HOME / ".claude" / "projects"
DEFAULT_PROJECT = PROJECTS_ROOT / "C--Users-User--claude-skills-claude-power-pack"

UUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
HEX8_RE = re.compile(r"^[0-9a-fA-F]{8}$")
NONALNUM_RE = re.compile(r"[^a-zA-Z0-9]")   # cwd -> project-dir encoding (same as harness)
LIVE_PREFIX = "⚡ "   # voltage sign + space -- the mark-live-session.js live marker
MAX_LABEL = 50
HEAD_LINE_CAP = 2000      # bounded head scan for ai-title / first-user / cwd
TAIL_BYTES = 64 * 1024    # bounded tail scan for the LATEST custom-title
CWD_RE = re.compile(r'"cwd"\s*:\s*"((?:[^"\\]|\\.)*)"')
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")

# First-user-message markers that identify a sub-session, not a real tab.
# Byte-for-byte the same set build_pane_map.ps1 uses.
SUB_PREFIXES = (
    "messages below were generated by the user while running local commands",
    "expert and insightful researcher",
    "contents from a serp search",
    "generate a list of serp",
    "generate a list of search queries",
)

# Preferred wave order for --apply (prompt R2). Repos not listed come after,
# alphabetically. Match is by case-insensitive substring on the repo leaf.
REPO_ORDER = (
    "claude-power-pack",
    "TUA-X",
    "InfinityOps",
    "KobiiCraft",
    "GEO-audit",
    "moneymaker",
)


# --------------------------------------------------------------------------- #
# Scanning
# --------------------------------------------------------------------------- #
def _extract_user_text(obj: dict) -> str:
    msg = obj.get("message") or {}
    if msg.get("role") != "user":
        return ""
    content = msg.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                return part.get("text") or ""
    return ""


def _clean(text: str) -> str:
    return WS_RE.sub(" ", TAG_RE.sub(" ", text)).strip()


def scan_session(path: Path) -> dict:
    """Bounded scan: head for ai-title / first-user / cwd, tail for the latest
    custom-title. Returns a dict describing the session's naming state."""
    ai = ""
    first_user = ""
    cwd = ""
    n = 0
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                n += 1
                if n > HEAD_LINE_CAP:
                    break
                if not cwd:
                    m = CWD_RE.search(line)
                    if m:
                        cwd = m.group(1).replace("\\\\", "\\")
                if '"ai-title"' in line and not ai:
                    try:
                        o = json.loads(line)
                    except Exception:
                        o = None
                    if o and o.get("type") == "ai-title" and isinstance(o.get("aiTitle"), str):
                        ai = o["aiTitle"]
                elif '"type":"user"' in line and not first_user:
                    try:
                        o = json.loads(line)
                    except Exception:
                        o = None
                    if o and o.get("type") == "user":
                        first_user = _clean(_extract_user_text(o))
                if ai and first_user and cwd:
                    break
    except OSError:
        pass

    last_custom = None
    try:
        size = path.stat().st_size
        start = max(0, size - TAIL_BYTES)
        with open(path, "rb") as fh:
            fh.seek(start)
            tail = fh.read()
        for raw in tail.decode("utf-8", errors="replace").split("\n"):
            if '"custom-title"' not in raw:
                continue
            try:
                o = json.loads(raw)
            except Exception:
                continue
            if o.get("type") == "custom-title" and isinstance(o.get("customTitle"), str):
                last_custom = o["customTitle"]   # keep scanning -> ends on the last
    except OSError:
        pass

    is_sub = any(p in first_user.lower() for p in SUB_PREFIXES) if first_user else False
    return {"ai": ai, "first_user": first_user, "cwd": cwd,
            "last_custom": last_custom, "is_sub": is_sub}


def effective_base(custom_raw: str | None) -> str:
    if custom_raw is None:
        return ""
    return custom_raw[len(LIVE_PREFIX):] if custom_raw.startswith(LIVE_PREFIX) else custom_raw


def is_uuid_fallback_title(base: str) -> bool:
    """True when the effective title is a machine-derived UUID string (empty, a
    bare 8-hex string, or a full UUID) -- never something a human Ctrl+R produces."""
    b = base.strip()
    if not b:
        return True
    return bool(HEX8_RE.match(b) or UUID_RE.match(b))


def is_canonical_location(proj_dir: Path, cwd: str) -> bool:
    """A transcript belongs in <proj_dir> iff its recorded cwd munges to that dir
    name (the harness encodes cwd -> dir by replacing every non-alnum with '-').
    No cwd recorded -> cannot disprove -> treat as canonical (best effort)."""
    if not cwd:
        return True
    return NONALNUM_RE.sub("-", cwd) == proj_dir.name


def repo_of(proj_dir: Path, cwd: str) -> str:
    if cwd:
        leaf = cwd.replace("/", "\\").rstrip("\\").split("\\")[-1]
        if leaf:
            return leaf
    return proj_dir.name.split("-")[-1] or proj_dir.name


def make_title(source: str, repo: str, repo_prefix: bool) -> str:
    label = source.strip()
    if len(label) > MAX_LABEL:
        label = label[: MAX_LABEL - 1].rstrip() + "…"
    return f"{repo} — {label}" if repo_prefix else label


def build_record(uuid: str, title: str) -> bytes:
    obj = {"type": "custom-title", "customTitle": title, "sessionId": uuid}
    return (json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")


# --------------------------------------------------------------------------- #
# Planning
# --------------------------------------------------------------------------- #
def plan_project(proj_dir: Path, repo_prefix: bool, skip_sids: set[str]) -> list[dict]:
    rows: list[dict] = []
    for path in sorted(proj_dir.glob("*.jsonl")):
        uuid = path.stem
        if not UUID_RE.match(uuid):
            continue
        s = scan_session(path)
        base = effective_base(s["last_custom"])
        repo = repo_of(proj_dir, s["cwd"])
        row = {
            "uuid": uuid, "path": path, "repo": repo, "proj": proj_dir.name,
            "current": base if base else "(none)",
            "new": "", "action": "", "source": "",
        }
        if uuid.lower() in skip_sids:
            row["action"] = "SKIP (running/protected)"
        elif not is_canonical_location(proj_dir, s["cwd"]):
            row["action"] = "SKIP (mislocated copy)"
        elif s["is_sub"]:
            row["action"] = "SKIP (sub-session)"
        elif not is_uuid_fallback_title(base):
            row["action"] = "SKIP (has custom name)"
        elif not s["ai"]:
            row["action"] = "SKIP (no ai-title)"
        else:
            row["new"] = make_title(s["ai"], repo, repo_prefix)
            row["source"] = "ai-title"
            row["action"] = "RENAME"
        rows.append(row)
    return rows


def iter_project_dirs() -> list[Path]:
    try:
        entries = sorted(p for p in PROJECTS_ROOT.iterdir() if p.is_dir())
    except OSError:
        return []
    return [p for p in entries if p.name != "_empty_shells"]


def repo_sort_key(repo: str) -> tuple[int, str]:
    low = repo.lower()
    for i, name in enumerate(REPO_ORDER):
        if name.lower() in low:
            return (i, low)
    return (len(REPO_ORDER), low)


# --------------------------------------------------------------------------- #
# Applying
# --------------------------------------------------------------------------- #
def apply_one(path: Path, uuid: str, title: str) -> tuple[bool, str]:
    """Append + verify prefix-byte-identity. Auto-revert on any mismatch."""
    try:
        original = path.read_bytes()
    except OSError as e:
        return False, f"read failed: {e}"
    n = len(original)
    pre = hashlib.sha256(original).hexdigest()
    line = build_record(uuid, title)
    try:
        with open(path, "ab") as fh:   # binary append: no CRLF translation, no BOM
            fh.write(line)
            fh.flush()
            os.fsync(fh.fileno())
    except OSError as e:
        return False, f"append failed: {e}"
    try:
        after = path.read_bytes()
    except OSError as e:
        return False, f"reread failed: {e}"
    ok = (
        len(after) == n + len(line)
        and hashlib.sha256(after[:n]).hexdigest() == pre
        and after[n:] == line
    )
    if ok:
        return True, f"prefix sha256 intact ({pre[:12]}...), +{len(line)}B"
    try:
        with open(path, "r+b") as fh:
            fh.truncate(n)
        return False, "VERIFY FAILED -> reverted (truncated to original size)"
    except OSError as e:
        return False, f"VERIFY FAILED and revert errored: {e}"


# --------------------------------------------------------------------------- #
# Reporting / CLI
# --------------------------------------------------------------------------- #
def summarize(rows: list[dict]) -> dict:
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["action"]] = counts.get(r["action"], 0) + 1
    return counts


def print_group(label: str, proj_name: str, rows: list[dict], verbose: bool) -> None:
    to_rename = [r for r in rows if r["action"] == "RENAME"]
    print(f"\n=== {label}  [{proj_name}]  ({len(rows)} sessions, {len(to_rename)} to rename) ===")
    for r in (rows if verbose else to_rename):
        if r["action"] == "RENAME":
            print(f"  [{r['uuid'][:8]}] -> {r['new']}")
        else:
            print(f"  [{r['uuid'][:8]}] {r['current'][:28]:<28}  {r['action']}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Safe retroactive session rename (inline custom-title append).")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--dry-run", action="store_true", help="print plan, write nothing (default)")
    g.add_argument("--apply", action="store_true", help="perform the rename with verify+revert")
    ap.add_argument("--all", dest="all_repos", action="store_true", help="operate on every project dir")
    ap.add_argument("--project", default=str(DEFAULT_PROJECT), help="single project dir (default: this repo)")
    ap.add_argument("--repo", default="", help="with --all: restrict to repos whose leaf matches (substring)")
    ap.add_argument("--repo-prefix", action="store_true", help="prepend '<repo> -- ' to names")
    ap.add_argument("--skip-sid", action="append", default=[], help="never touch this session id (repeatable)")
    ap.add_argument("--verbose", action="store_true", help="show skipped rows too")
    args = ap.parse_args()

    skip_sids = {s.lower() for s in args.skip_sid}
    for env_key in ("PP_EVT_SID", "CLAUDE_SESSION_ID"):
        v = os.environ.get(env_key)
        if v:
            skip_sids.add(v.lower())

    if args.all_repos:
        proj_dirs = iter_project_dirs()
    else:
        p = Path(args.project)
        if not p.is_dir():
            print(f"ERROR: project dir not found: {p}", file=sys.stderr)
            return 2
        proj_dirs = [p]

    # Plan, keeping physical-dir grouping (mislocated copies never merge across dirs).
    groups: list[dict] = []   # {proj, label, rows}
    for pd in proj_dirs:
        rows = plan_project(pd, args.repo_prefix, skip_sids)
        if not rows:
            continue
        label = rows[0]["repo"]
        if args.repo and args.repo.lower() not in label.lower():
            continue
        groups.append({"proj": pd.name, "label": label, "rows": rows})

    groups.sort(key=lambda g: repo_sort_key(g["label"]))

    all_rows = [r for g in groups for r in g["rows"]]
    total = len(all_rows)
    to_rename = [r for r in all_rows if r["action"] == "RENAME"]
    print(f"Scope: {'ALL repos' if args.all_repos else (proj_dirs[0].name if proj_dirs else '-')}")
    print(f"Sessions scanned: {total} | to rename: {len(to_rename)} | project dirs: {len(groups)}")
    counts = summarize(all_rows)
    print("Breakdown: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))

    for g in groups:
        print_group(g["label"], g["proj"], g["rows"], args.verbose)

    if not args.apply:
        print(f"\nDRY-RUN. Nothing written. {len(to_rename)} session(s) would be renamed.")
        print("Re-run with --apply (waves per project dir, per-file sha256-verified, auto-revert).")
        return 0

    print("\nAPPLY (waves per project dir; a failure in a wave STOPS before the next):")
    ok_ct = fail_ct = 0
    stopped = False
    for g in groups:
        wave = [r for r in g["rows"] if r["action"] == "RENAME"]
        if not wave:
            continue
        print(f"\n--- wave: {g['label']} [{g['proj']}]  ({len(wave)} rename) ---")
        wave_fail = 0
        for r in wave:
            ok, msg = apply_one(r["path"], r["uuid"], r["new"])
            print(f"  {'OK ' if ok else 'FAIL'} [{r['uuid'][:8]}] -> {r['new']}  ({msg})")
            if ok:
                ok_ct += 1
            else:
                fail_ct += 1
                wave_fail += 1
        if wave_fail:
            print(f"  !! {wave_fail} failure(s) in this wave -> STOP (no further waves).")
            stopped = True
            break

    print(f"\nAPPLIED: {ok_ct} ok, {fail_ct} failed"
          + (" -- STOPPED early on failure." if stopped else "."))
    return 0 if fail_ct == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
