#!/usr/bin/env python
"""skill_mirror_drift.py -- the D-02 skills mirror pass (skill-capability, pillar H).

    python3 tools/skill_mirror_drift.py --live                     # one line per repo skill; exit 1 on DRIFT/INCONCLUSIVE
    python3 tools/skill_mirror_drift.py --json                     # the full report as one JSON object
    python3 tools/skill_mirror_drift.py --measure-live --host gex44   # record the plane to evidence/H-live-<host>.json
    python3 tools/skill_mirror_drift.py --compare PATH             # re-measure and name every row that moved (host-bound)

What it compares: every repo skill `skills/<name>/` that holds a tracked SKILL.md against the live copy
`<live-root>/<name>/`, whole directory at a time. The repo side is read from COMMITTED BLOBS at a ref (default
HEAD) through the primitives of `tools/verify_global_mirrors.py` (`tracked_at`, `batch_blobs`, `_norm_sha`,
`_git_exe`); the working tree is never the source, because a concurrent writer's uncommitted edit would stand in
for the mirror. Each directory is reduced to a digest over the sorted lines `<relpath>\\0<lf_sha256>\\n`.

Statuses: IDENTICAL (digests equal; `eol_only` True when only line endings differ), DRIFT (digests differ; the
`missing_live`, `extra_live` and `changed` file lists say how), ABSENT_LIVE (no live directory: reported, never
counted as drift, because not every repo skill is meant to be installed on every host), INCONCLUSIVE (a git or
read failure; carries its reason, never a traceback and never an empty population).

Why a new pass and not a change to `modules/mirror_discovery/discovery.py`: that module files the whole `skills`
domain under OTHER_OWNER and is consumed by `check_pairs` inside the `tools/verify_spp.py` mirror-parity row (a
15 s budget) and by `tools/test_mirror_parity.py`; pairing `skills` there would also pull in the ~160 live skills
that no repo directory owns (gsd-*, plugins) and change `domain_counts` for every estate. This pass pairs only repo
skills that hold a SKILL.md and reuses the comparator's primitives, so there is still ONE comparator.

Live-side exclusions: `__pycache__/` directories and `*.pyc` files (generated bytecode no repo tracks); they are
counted in `excluded`. Symlinked files are hashed by their link text, symlinked directories are not descended.

This module only READS the live tree. It never writes under the home directory.

Exit codes: 0 no DRIFT/INCONCLUSIVE, 1 DRIFT or INCONCLUSIVE, 2 could not run (bad arguments).
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import platform
import subprocess
import sys
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

import verify_global_mirrors as vgm  # noqa: E402

# The checkout whose blobs are read is the one this file lives in. A linked worktree has its own HEAD, so no
# canonical_repo_root indirection is wanted here: the repo argument IS the checkout being judged.
REPO = _THIS_DIR.parent
EVIDENCE_DIR_REL = "vault/programs/skill-capability/evidence"
SCHEMA = "skill-mirror-live/1"
STATUSES = ("IDENTICAL", "DRIFT", "ABSENT_LIVE", "INCONCLUSIVE")
GIT_TIMEOUT = 30


def lf_bytes(b: bytes) -> bytes:
    """CRLF and lone CR to LF. Every committed text read for a comparison goes through this: the laptop clone
    runs core.autocrlf=true and neither evidence/*.md nor evidence/*.json is `-text` in .gitattributes."""
    return b.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


# --------------------------------------------------------------------------- git

def git_run(repo, *args, data: bytes | None = None):
    """(stdout bytes, None) or (None, reason). Never raises: a missing git, an OS error, a timeout and a
    non-zero rc are all a reason (W4)."""
    try:
        exe = vgm._git_exe()
    except FileNotFoundError as e:
        return None, f"git not found: {e}"
    try:
        p = subprocess.run([exe, "-C", str(repo), *args], input=data, capture_output=True, timeout=GIT_TIMEOUT)
    except (OSError, subprocess.SubprocessError) as e:
        return None, f"git {args[0] if args else ''} failed: {e}"
    if p.returncode != 0:
        err = p.stderr.decode("utf-8", "replace").strip().splitlines()
        return None, f"git {args[0] if args else ''} rc={p.returncode}: {err[-1] if err else 'no stderr'}"
    return p.stdout, None


def resolve_commit(repo, ref="HEAD"):
    """(full sha, None) or (None, reason)."""
    out, why = git_run(repo, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}")
    if out is None:
        return None, why
    sha = out.decode("utf-8", "replace").strip()
    if len(sha) != 40:
        return None, f"rev-parse returned {sha!r}"
    return sha, None


# --------------------------------------------------------------------------- digests

def dir_digest(files: dict) -> str:
    """sha256 over the sorted lines `<relpath>\\0<lf_sha>\\n`."""
    h = hashlib.sha256()
    for rel in sorted(files):
        h.update(f"{rel}\0{files[rel]}\n".encode("utf-8"))
    return h.hexdigest()


def repo_skills(repo, ref):
    """({skill: sorted file list relative to skills/<skill>/}, None), or (None, reason) when the ref cannot be
    read: an empty tracked set is UNMEASURED, never an empty population."""
    tracked = vgm.tracked_at(str(repo), ref)
    if not tracked:
        _, why = git_run(repo, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}")
        return None, why or f"nothing tracked at {ref}"
    names = sorted({p.split("/")[1] for p in tracked if p.startswith("skills/") and p.count("/") >= 2
                    and p == f"skills/{p.split('/')[1]}/SKILL.md"})
    out = {}
    for n in names:
        pre = f"skills/{n}/"
        out[n] = sorted(p[len(pre):] for p in tracked if p.startswith(pre))
    return out, None


def repo_side(repo, ref, skills: dict):
    """{skill: {files, raw, digest} | {error}} read in ONE cat-file batch. A blob with a reason makes that
    skill INCONCLUSIVE; an empty blob is a legitimate empty file."""
    rels = [f"skills/{n}/{r}" for n, fl in skills.items() for r in fl]
    blobs = vgm.batch_blobs(str(repo), ref, rels)
    out = {}
    for n, fl in skills.items():
        files, raw, err = {}, {}, None
        for r in fl:
            if r.startswith('"'):
                err = f"quoted path {r!r}"
                break
            data, why = blobs.get(f"skills/{n}/{r}", (None, "not returned"))
            if data is None and why == "git-batch-empty":
                data, why = b"", None
            if data is None:
                err = f"{r}: {why}"
                break
            files[r] = vgm._norm_sha(data)
            raw[r] = hashlib.sha256(data).hexdigest()
        out[n] = {"error": err} if err else {"files": files, "raw": raw, "digest": dir_digest(files)}
    return out


def live_side(live_dir):
    """{files, raw, digest, excluded} for a live skill directory, or None when it does not exist.
    Raises OSError on an unreadable file (the caller turns that into INCONCLUSIVE)."""
    base = Path(live_dir)
    if not base.is_dir():
        return None
    files, raw, excluded = {}, {}, 0
    for root, dirs, names in os.walk(base, followlinks=False):
        kept = []
        for d in dirs:
            if d == "__pycache__":
                excluded += 1
            else:
                kept.append(d)
        dirs[:] = kept
        for nm in names:
            if nm.endswith(".pyc"):
                excluded += 1
                continue
            p = Path(root) / nm
            rel = p.relative_to(base).as_posix()
            data = os.readlink(p).encode("utf-8", "surrogateescape") if p.is_symlink() else p.read_bytes()
            files[rel] = vgm._norm_sha(data)
            raw[rel] = hashlib.sha256(data).hexdigest()
    return {"files": files, "raw": raw, "digest": dir_digest(files), "excluded": excluded}


def compare(repo_entry, live_entry) -> dict:
    """Status of one skill from a repo entry and a live entry (both {files, raw, digest} or None/error)."""
    if repo_entry is None or "error" in repo_entry:
        return {"status": "INCONCLUSIVE", "reason": (repo_entry or {}).get("error", "no repo entry"),
                "eol_only": False, "missing_live": [], "extra_live": [], "changed": []}
    if live_entry is None:
        return {"status": "ABSENT_LIVE", "eol_only": False, "missing_live": [], "extra_live": [], "changed": []}
    if "error" in live_entry:
        return {"status": "INCONCLUSIVE", "reason": live_entry["error"],
                "eol_only": False, "missing_live": [], "extra_live": [], "changed": []}
    rf, lf = repo_entry["files"], live_entry["files"]
    if repo_entry["digest"] == live_entry["digest"]:
        eol = any(repo_entry["raw"].get(r) != live_entry["raw"].get(r) for r in rf)
        return {"status": "IDENTICAL", "eol_only": eol, "missing_live": [], "extra_live": [], "changed": []}
    return {"status": "DRIFT", "eol_only": False,
            "missing_live": sorted(set(rf) - set(lf)),
            "extra_live": sorted(set(lf) - set(rf)),
            "changed": sorted(r for r in set(rf) & set(lf) if rf[r] != lf[r])}


def count_rows(rows) -> dict:
    c = {s: 0 for s in STATUSES}
    c["eol_only"] = 0
    for r in rows:
        c[r["status"]] += 1
        if r["status"] == "IDENTICAL" and r.get("eol_only"):
            c["eol_only"] += 1
    return c


def live_report(repo, live_root, ref="HEAD") -> dict:
    """{status: MEASURED|INCONCLUSIVE, repo_commit, live_root, rows, counts} or {status: INCONCLUSIVE, reason}.
    Never raises."""
    sha, why = resolve_commit(repo, ref)
    if sha is None:
        return {"status": "INCONCLUSIVE", "reason": why}
    skills, why = repo_skills(repo, sha)
    if skills is None:
        return {"status": "INCONCLUSIVE", "reason": why}
    if not skills:
        return {"status": "INCONCLUSIVE", "reason": f"no skill with a tracked SKILL.md at {sha[:8]}"}
    rside = repo_side(repo, sha, skills)
    rows = []
    for n in sorted(skills):
        try:
            lent = live_side(Path(live_root) / n)
        except OSError as e:
            lent = {"error": f"live read failed: {e}"}
        cmp_ = compare(rside[n], lent)
        row = {"skill": n, "status": cmp_["status"], "eol_only": cmp_["eol_only"]}
        if "reason" in cmp_:
            row["reason"] = cmp_["reason"]
        if "files" in rside[n]:
            row["repo_digest"] = rside[n]["digest"]
            row["repo_files"] = rside[n]["files"]
            row["repo_raw"] = rside[n]["raw"]
        row["live_digest"] = lent["digest"] if lent and "digest" in lent else None
        if lent and "files" in lent:
            row["live_files"] = lent["files"]
            row["live_raw"] = lent["raw"]
            row["excluded"] = lent["excluded"]
        row["missing_live"], row["extra_live"], row["changed"] = (
            cmp_["missing_live"], cmp_["extra_live"], cmp_["changed"])
        rows.append(row)
    return {"status": "MEASURED", "repo_commit": sha, "live_root": str(live_root), "rows": rows,
            "counts": count_rows(rows)}


# --------------------------------------------------------------------------- CLI

def _tilde(p) -> str:
    home = str(Path.home())
    s = str(p)
    return "~" + s[len(home):] if s.startswith(home) else s


def default_live_root() -> Path:
    return Path.home() / ".claude" / "skills"


def _line(r) -> str:
    if r["status"] == "DRIFT":
        return (f"DRIFT {r['skill']} missing_live={r['missing_live']} extra_live={r['extra_live']} "
                f"changed={r['changed']}")
    if r["status"] == "IDENTICAL":
        return f"IDENTICAL {r['skill']}" + (" eol_only" if r["eol_only"] else "")
    if r["status"] == "INCONCLUSIVE":
        return f"INCONCLUSIVE {r['skill']} {r.get('reason', '')}"
    return f"{r['status']} {r['skill']}"


def measure(repo, live_root, host, ref="HEAD", command=""):
    rep = live_report(repo, live_root, ref)
    if rep["status"] != "MEASURED":
        return None, rep.get("reason", "unmeasured")
    bad = [r["skill"] for r in rep["rows"] if r["status"] == "INCONCLUSIVE"]
    if bad:
        return None, f"INCONCLUSIVE rows, refusing to record: {bad}"
    return {
        "schema": SCHEMA, "host": host, "node": platform.node(),
        "measured_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "command": command, "repo_commit": rep["repo_commit"], "live_root": _tilde(live_root),
        "rows": rep["rows"], "counts": rep["counts"],
    }, None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--live", action="store_true", help="one line per repo skill; exit 1 on DRIFT/INCONCLUSIVE")
    ap.add_argument("--json", action="store_true", help="print the full report")
    ap.add_argument("--measure-live", action="store_true", help="record this host's plane (needs --host)")
    ap.add_argument("--host", help="label for --measure-live, ^[a-z0-9-]+$")
    ap.add_argument("--compare", metavar="PATH", help="re-measure and name rows that moved vs a recording; "
                    "host-bound: meaningful only on the host that recorded it")
    ap.add_argument("--repo", default=str(REPO))
    ap.add_argument("--live-root", default=None)
    ap.add_argument("--ref", default="HEAD")
    a = ap.parse_args(argv)
    live_root = Path(a.live_root) if a.live_root else default_live_root()
    repo = Path(a.repo)

    if a.measure_live:
        import re
        if not a.host or not re.fullmatch(r"[a-z0-9-]+", a.host):
            print("--measure-live needs --host matching ^[a-z0-9-]+$", file=sys.stderr)
            return 2
        cmd = "python3 tools/skill_mirror_drift.py --measure-live --host " + a.host
        rec, why = measure(repo, live_root, a.host, a.ref, cmd)
        if rec is None:
            print(f"INCONCLUSIVE {why}")
            return 1
        dest = repo / EVIDENCE_DIR_REL / f"H-live-{a.host}.json"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes((json.dumps(rec, indent=1, sort_keys=True) + "\n").encode("utf-8"))
        print(f"recorded {dest} repo_commit={rec['repo_commit'][:8]} counts={rec['counts']}")
        return 0

    if a.compare:
        try:
            rec = json.loads(lf_bytes(Path(a.compare).read_bytes()))
        except (OSError, ValueError) as e:
            print(f"INCONCLUSIVE cannot read recording: {e}")
            return 1
        rep = live_report(repo, live_root, rec.get("repo_commit", a.ref))
        if rep["status"] != "MEASURED":
            print(f"INCONCLUSIVE {rep.get('reason')}")
            return 1
        old = {r["skill"]: r for r in rec.get("rows", [])}
        moved = [r["skill"] for r in rep["rows"]
                 if r["skill"] not in old or old[r["skill"]]["status"] != r["status"]
                 or old[r["skill"]].get("live_digest") != r["live_digest"]]
        for n in moved:
            print(f"MOVED {n}")
        print(f"compared {len(rep['rows'])} skills, moved {len(moved)}")
        return 1 if moved else 0

    rep = live_report(repo, live_root, a.ref)
    if rep["status"] != "MEASURED":
        print(f"INCONCLUSIVE {rep.get('reason')}")
        return 1
    if a.json:
        print(json.dumps(rep, indent=1, sort_keys=True))
        return 0 if not (rep["counts"]["DRIFT"] or rep["counts"]["INCONCLUSIVE"]) else 1
    if a.live:
        for r in rep["rows"]:
            print(_line(r))
        print(f"counts {rep['counts']} repo_commit={rep['repo_commit'][:8]} live_root={_tilde(live_root)}")
        return 1 if (rep["counts"]["DRIFT"] or rep["counts"]["INCONCLUSIVE"]) else 0
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
