#!/usr/bin/env python
"""V-INTENT-* -- post-compact intent must not ride in /compact's arguments.

MEASURED HOST SEMANTICS (2026-09-19, this estate's own transcripts). Two
independent mechanisms destroy the text after `/compact`, and either alone is
fatal:

  (1) CAVEATED. Session 37cfb187 submitted
      `/compact focus on narrow-wall crossing delivery fix, phase 1 two-pane drill`.
      The args DID reach the host and reappear after the boundary as

          <local-command-caveat>Caveat: The messages below were generated by the
          user while running local commands. DO NOT respond to these messages or
          otherwise consider them in your response unless the user explicitly
          asks you to.</local-command-caveat>
          <command-name>/compact</command-name>
          <command-args>focus on narrow-wall crossing delivery fix, ...</command-args>

      The host hands the model the instruction inside an envelope telling it to
      ignore the instruction. `compactMetadata` carries trigger/preTokens/
      postTokens/durationMs/preservedSegment and NO field for the text at all.

  (2) DROPPED AT SUBMISSION. Session de7f3c91's boundary records
      `<command-args></command-args>` -- empty. The automated delivery had been
      blocked (cli_timeout), so the line was submitted by hand as a bare
      `/compact`, and the obligations the model had written were simply gone.

So `/compact` arguments are a summarizer focus hint, never a mission store. The
obligations are captured at the moment the transport validates the model's
line -- which is the last place they exist in full -- and persisted on the
marker, whose contents reach the model through the Stop hook's `reason`, a
channel the host does not caveat.

This closes the CARRIER. It does not decompose the intent into structured
obligations (phase / checker / blocked-until); that remains open and is stated
as such rather than implied by a green.
"""
from __future__ import annotations

import importlib.util
import json
import os
import sys
import tempfile
import uuid
from pathlib import Path

# No bytecode: a same-length mutation restored within one mtime second leaves
# CPython executing a .pyc built from the mutant while the source is correct
# (measured 2026-09-19 on the sibling rearm gate -- source said 28, gate said 50).
sys.dont_write_bytecode = True

STATE = tempfile.mkdtemp(prefix="intent-state-")
os.environ["GSD_LONG_RUN_STATE_DIR"] = STATE
os.environ.pop("CPP_CONTINUATION_TRANSPORT", None)

ROOT = Path(__file__).resolve().parents[1]
TMP = Path(tempfile.mkdtemp(prefix="intent-"))

REAL_LINE = "/compact focus on KELB-01 Phase 13 recheck revised plan then execute"
REAL_ARGS = "focus on KELB-01 Phase 13 recheck revised plan then execute"

FAKE_ORCA = r'''
import json, os, sys, time
st = json.load(open(os.environ["FAKE_ORCA_STATE"], encoding="utf-8"))
argv = sys.argv[1:]
def flag(n):
    return argv[argv.index(n) + 1] if n in argv else None
def out(o):
    print(json.dumps(o)); sys.exit(0)
verb = argv[1] if len(argv) > 1 else ""
h = flag("--terminal") or st["terminals"][0]["handle"]
if verb == "list":
    out({"ok": True, "result": {"terminals": st["terminals"]}})
if verb == "wait":
    out({"ok": True, "result": {"wait": {"handle": h, "satisfied": True}}})
if verb == "send":
    t = st["terminals"][0]
    text = flag("--text") or ""
    iso = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(time.time() + 1)) + ".000Z"
    with open(t["transcript"], "a", encoding="utf-8") as fh:
        fh.write(json.dumps({"type": "user", "timestamp": iso, "message":
                 {"role": "user", "content": "<command-name>" + text.split()[0] +
                  "</command-name>"}}) + "\n")
    out({"ok": True, "result": {"send": {"handle": h, "accepted": True, "bytesWritten": len(text)}}})
out({"ok": False, "error": {"code": "unexpected_verb"}})
'''

_passes = 0
_fails = 0


def _ok(g, e):
    global _passes
    _passes += 1
    print(f"  PASS {g}: {e}")


def _fail(g, d):
    global _fails
    _fails += 1
    print(f"  FAIL {g}: {d}")


def _load(path, name):
    sys.path.insert(0, str(path.parent))
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    mk = _load(ROOT / "tools" / "gsd_autorun_marker.py", "_int_mk")
    ct = _load(ROOT / "tools" / "continuation_transport.py", "_int_ct")
    wd = _load(ROOT / "modules" / "zero-crash" / "hooks" / "context-watchdog.py", "_int_wd")

    # --- the pure extractor --------------------------------------------------
    extract = getattr(ct, "compact_intent", None)
    if not callable(extract):
        _fail("V-INTENT-EXTRACTOR-EXISTS",
              "continuation_transport has no compact_intent(); the obligations in the "
              "model's /compact line are discarded at the only point they exist in full")
    else:
        _ok("V-INTENT-EXTRACTOR-EXISTS", "compact_intent() present")
        if extract(REAL_LINE) == REAL_ARGS:
            _ok("V-INTENT-EXTRACTS-ARGS", f"{REAL_ARGS!r}")
        else:
            _fail("V-INTENT-EXTRACTS-ARGS", f"got {extract(REAL_LINE)!r}, want {REAL_ARGS!r}")
        # A bare /compact must yield NOTHING, not an empty-but-present intent:
        # de7f3c91's boundary shows exactly this case, and inventing an intent
        # for it would be worse than having none.
        if extract("/compact") == "" and extract("/compact   ") == "":
            _ok("V-INTENT-BARE-COMPACT-EMPTY", "a bare /compact records no intent")
        else:
            _fail("V-INTENT-BARE-COMPACT-EMPTY",
                  f"bare /compact produced {extract('/compact')!r}")

    # --- the marker carries it ----------------------------------------------
    record = getattr(mk, "record_intent", None)
    sid = "intent-" + uuid.uuid4().hex[:12]
    if not callable(record):
        _fail("V-INTENT-MARKER-RECORDS", "gsd_autorun_marker has no record_intent()")
    else:
        mk.write_marker(sid, "/gsd-autonomous --from 13", cwd=str(TMP))
        record(sid, REAL_ARGS)
        got = (mk.read_marker(sid) or {}).get("post_compact_intent")
        if got == REAL_ARGS:
            _ok("V-INTENT-MARKER-RECORDS", "intent persisted on the marker")
        else:
            _fail("V-INTENT-MARKER-RECORDS", f"marker holds {got!r}")

        # and recording against a session with no marker must not invent one
        ghost = "intent-ghost-" + uuid.uuid4().hex[:8]
        res = record(ghost, "something")
        if res is False and mk.read_marker(ghost) is None:
            _ok("V-INTENT-NO-MARKER-SAFE", "no marker -> False, and none created")
        else:
            _fail("V-INTENT-NO-MARKER-SAFE", f"returned {res!r}, marker={mk.read_marker(ghost)!r}")

    # --- it reaches the model in the resume message -------------------------
    with_intent = {"resume_command": "/gsd-autonomous --from 13",
                   "post_compact_intent": REAL_ARGS}
    without = {"resume_command": "/gsd-autonomous --from 13"}
    msg_with = wd._resume_dispatch_message(with_intent, {"boundary_ts": "T"}, {"route": "manual", "why": "x"})
    msg_without = wd._resume_dispatch_message(without, {"boundary_ts": "T"}, {"route": "manual", "why": "x"})

    if REAL_ARGS in msg_with:
        _ok("V-INTENT-IN-RESUME-MESSAGE", "the obligations reach the model via the Stop reason")
    else:
        _fail("V-INTENT-IN-RESUME-MESSAGE",
              "the resume message names the command but not what must happen first; "
              "the checker obligation dies at the boundary")

    # Negative control: an ordinary run (no intent) must be byte-identical to
    # what it has always been, or this clause has changed every session.
    if REAL_ARGS not in msg_without and "post_compact_intent" not in msg_without:
        _ok("V-INTENT-ABSENT-UNCHANGED", "no intent -> no clause; ordinary sessions untouched")
    else:
        _fail("V-INTENT-ABSENT-UNCHANGED", "a marker without intent still grew a clause")

    # --- INTEGRATION: the wiring, not three green units ---------------------
    # Without this the extractor, the marker and the message can all be correct
    # while nothing connects them -- the estate's own recurring failure.
    sid2 = "intent-e2e-" + uuid.uuid4().hex[:12]
    tpath = TMP / f"{sid2}.jsonl"
    tpath.write_text(json.dumps({
        "type": "assistant", "timestamp": "2026-09-19T12:00:00.000Z",
        "message": {"role": "assistant", "content": [{"type": "text", "text":
                    "Checkpoint written.\n\n" + REAL_LINE}]}}) + "\n", encoding="utf-8")
    fake = TMP / "fake_orca.py"
    fake.write_text(FAKE_ORCA, encoding="utf-8")
    # The terminal shape resolve() actually requires: tabId + leafId (the pane
    # key is "tab:leaf-uuid"), connected and writable, not orphaned. Guessing
    # this produced TARGET_UNKNOWN and an E2E leg that could only ever be red.
    tab, leaf = "tab-e2e", str(uuid.uuid4())
    pane = f"{tab}:{leaf}"
    state = TMP / f"state-{sid2}.json"
    state.write_text(json.dumps({"terminals": [
        {"handle": "term_e2e", "tabId": tab, "leafId": leaf, "incarnationId": "i1",
         "connected": True, "writable": True, "orphaned": False,
         "transcript": str(tpath)}]}), encoding="utf-8")
    os.environ["FAKE_ORCA_STATE"] = str(state)
    os.environ["CPP_ORCA_CLI"] = json.dumps([sys.executable, str(fake)])

    mk.write_marker(sid2, "/gsd-autonomous --from 13", cwd=str(TMP))
    ep = ct.endpoint_path(sid2)
    ep.parent.mkdir(parents=True, exist_ok=True)
    ep.write_text(json.dumps({"session_id": sid2, "host": "orca", "pane_key": pane}),
                  encoding="utf-8")

    res = ct.deliver(sid2, "compact", expect_prefix="/compact",
                     transcript=str(tpath), cid=f"{sid2}:compact:1")
    # Precondition, asserted rather than assumed: a delivery that never reached
    # the line-validation step says nothing about whether the capture is wired.
    if res.get("outcome") in (ct.NO_ENDPOINT, ct.NOT_FOUND, ct.UNSUPPORTED, ct.PROVIDER_DOWN):
        _fail("V-INTENT-E2E-HARNESS",
              f"HARNESS-FAILED: deliver() stopped at {res.get('outcome')} before reading the "
              "model's line; the fixture, not the subject, is what failed")
    else:
        _ok("V-INTENT-E2E-HARNESS", f"delivery reached line validation (outcome={res.get('outcome')})")
    stored = (mk.read_marker(sid2) or {}).get("post_compact_intent")
    if stored == REAL_ARGS:
        _ok("V-INTENT-E2E-CAPTURED-ON-DELIVERY",
            f"deliver() persisted the obligations (outcome={res.get('outcome')})")
    else:
        _fail("V-INTENT-E2E-CAPTURED-ON-DELIVERY",
              f"marker holds {stored!r} after a real deliver() (outcome={res.get('outcome')}); "
              "the extractor is not wired into the delivery path")

    total = _passes + _fails
    print(f"\nINTENT_PASS={_passes}/{total}  threshold={total}/{total}")
    return 0 if _fails == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
