"""test_pane_map.py -- invariants for the disk-derived pane map.

Validates ~/.claude/state/pane_map.json (produced by build_pane_map.ps1).
The generator's contract: derive every interactive tab from the transcript
.jsonl files on disk per active repo, filter sub-sessions, never invent ids.

Run: python tools/test_pane_map.py
Exit 0 iff all V-gates pass.
"""
import json
import os
import re
import sys

HOME = os.path.expanduser("~")
PM = os.path.join(HOME, ".claude", "state", "pane_map.json")
PROJ = os.path.join(HOME, ".claude", "projects")

# substrings that mark a non-interactive sub-session (must never appear as a tab)
SUB_MARKERS = [
    "messages below were generated by the user while running local commands",
    "expert and insightful researcher",
    "contents from a SERP search",
    "generate a list of SERP",
    "generate a list of search queries",
]

passes = 0
fails = 0


def _ok(g, ev):
    global passes
    passes += 1
    print(f"  OK   {g}: {ev}")


def _fail(g, why):
    global fails
    fails += 1
    print(f"  FAIL {g}: {why}")


def enc(cwd):
    return re.sub(r"[^a-zA-Z0-9]", "-", cwd)


with open(PM, "r", encoding="utf-8-sig") as f:
    data = json.load(f)
panes = data.get("panes", [])

# V-READS-FROM-DISK
src = (data.get("source") or "").lower()
if "disk" in src and "transcript" in src:
    _ok("V-READS-FROM-DISK", f"source={data.get('source')!r}")
else:
    _fail("V-READS-FROM-DISK", f"source not disk-based: {data.get('source')!r}")

# V-HAS-PANES
if panes:
    _ok("V-HAS-PANES", f"{len(panes)} panes across {data.get('counts', {}).get('repos')} repos")
else:
    _fail("V-HAS-PANES", "no panes")

# V-EVERY-PANE-HAS-TRANSCRIPT (never invents ids)
missing = []
for p in panes:
    j = os.path.join(PROJ, enc(p["cwd"]), p["sessionId"] + ".jsonl")
    if not os.path.isfile(j):
        missing.append(p["sessionId"][:8])
if not missing:
    _ok("V-EVERY-PANE-HAS-TRANSCRIPT", f"all {len(panes)} panes have a .jsonl on disk")
else:
    _fail("V-EVERY-PANE-HAS-TRANSCRIPT", f"no transcript for: {missing}")

# V-RESUME-EXACT
bad = [p["sessionId"][:8] for p in panes if p.get("resumeCmd") != f"claude --resume {p['sessionId']}"]
if not bad:
    _ok("V-RESUME-EXACT", "every pane resumeCmd == 'claude --resume <sid>'")
else:
    _fail("V-RESUME-EXACT", f"wrong resumeCmd: {bad}")

# V-LABEL-DERIVED
empty = [p["sessionId"][:8] for p in panes if not (p.get("topic") or "").strip()]
if not empty:
    _ok("V-LABEL-DERIVED", "every pane has a non-empty topic")
else:
    _fail("V-LABEL-DERIVED", f"empty topic: {empty}")

# V-CWD-EXISTS
gone = sorted({p["cwd"] for p in panes if not os.path.isdir(p["cwd"])})
if not gone:
    _ok("V-CWD-EXISTS", "every cwd exists on disk")
else:
    _fail("V-CWD-EXISTS", f"missing cwd: {gone}")

# V-NO-SUBSESSIONS
leaked = [p["sessionId"][:8] for p in panes
          if any(m in (p.get("topic") or "").lower() for m in [s.lower() for s in SUB_MARKERS])]
if not leaked:
    _ok("V-NO-SUBSESSIONS", "no local-command / research sub-session leaked in as a tab")
else:
    _fail("V-NO-SUBSESSIONS", f"sub-session leaked: {leaked}")

# V-SORTED-RECENT-FIRST
acts = [p.get("lastActivity", "") for p in panes]
if acts == sorted(acts, reverse=True):
    _ok("V-SORTED-RECENT-FIRST", "panes ordered most-recent-first")
else:
    _fail("V-SORTED-RECENT-FIRST", "panes not sorted by lastActivity desc")

total = passes + fails
print(f"\nPANE_MAP_PASS={passes}/{total}  threshold={total}/{total}")
sys.exit(0 if fails == 0 else 1)
