#!/usr/bin/env python3
"""Hermetic tests for tools/conversation_quality_audit.py (behavioral audit).

Builds a synthetic ~/.claude/projects tree that triggers P1/P2/P4/P5 (and P3
across two sessions) AND proves the FP guards: a harness <local-command-caveat>
wrapper must NOT count as P2; a '?'-containing non-question turn must NOT count
as P5. Run 3x; DOMAIN_PASS=N/N constant.
"""
from __future__ import annotations

import importlib.util
import json
import tempfile
from pathlib import Path

_HERE = Path(__file__).resolve().parent


def _load(name):
    spec = importlib.util.spec_from_file_location(name, _HERE / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


CQA = _load("conversation_quality_audit")

_passes = 0
_fails = 0


def _ok(g, ev):
    global _passes
    _passes += 1
    print(f"  PASS {g}: {ev}")


def _fail(g, ev):
    global _fails
    _fails += 1
    print(f"  FAIL {g}: {ev}")


def _asst(text, out, ts="2026-07-02T10:00:00Z", tool=None):
    content = []
    if text:
        content.append({"type": "text", "text": text})
    if tool:
        content.append({"type": "tool_use", "name": tool[0],
                        "input": {"file_path": tool[1]}})
    return json.dumps({"timestamp": ts, "message": {
        "role": "assistant", "model": "m",
        "usage": {"input_tokens": 10, "output_tokens": out,
                  "cache_creation_input_tokens": 0,
                  "cache_read_input_tokens": 100},
        "content": content}})


def _user(text, ts="2026-07-02T10:00:00Z"):
    return json.dumps({"timestamp": ts, "message": {
        "role": "user", "content": [{"type": "text", "text": text}]}})


def _build(base: Path):
    p = base / "C--proj-main"
    p.mkdir(parents=True)
    lines = [
        _user("let us begin the task together today"),
        _asst("Working on the implementation now.", 1000),           # A1
        _asst("I made an error, let me fix that. Redoing it.", 500),  # A2 -> P1
        _user("please implement the login endpoint right now"),       # O1
        _asst("Sure, I will acknowledge that shortly.", 400),         # no-tool
        _user("please implement the login endpoint right now"),       # O2 -> P2
        _asst("Plan:\n- foo.py\n- bar.py\nI will implement these steps.", 100),
        _user("ok"),                                                  # approval
        _asst("", 800, tool=("Write", "baz.py")),                    # exec -> P4
        _asst("Should I use the caching approach or the streaming "
              "approach here?", 300),                                 # Q1
        _user("use option A please"),                                 # answer
        _asst("Should I use the caching approach or the streaming "
              "approach here?", 350),                                 # Q2 -> P5
        _asst("Analysis shows 5 files changed. Is that all? Done.", 200),  # non-Q
        _user("<local-command-caveat>Caveat: generated by the user while "
              "running local commands. please implement the login endpoint"),
        _user("<local-command-caveat>Caveat: generated by the user while "
              "running local commands. please implement the login endpoint"),
    ]
    (p / "sMain.jsonl").write_text("\n".join(lines), encoding="utf-8")
    # P3: two same-project sessions with near-identical opening scan, <7 days
    scan = ("Reality Scan preflight of repo alpha checking files alpha "
            "beta gamma and the configs and the manifests before work")
    (p / "sScanA.jsonl").write_text(
        _asst(scan, 700, ts="2026-07-01T09:00:00Z"), encoding="utf-8")
    (p / "sScanB.jsonl").write_text(
        _asst(scan + " again", 720, ts="2026-07-03T09:00:00Z"),
        encoding="utf-8")


def main() -> int:
    with tempfile.TemporaryDirectory() as td:
        base = Path(td) / "projects"
        _build(base)
        d = CQA.audit(proj_base=str(base))
        P = d["pats"]

        if P["P1"].count == 1:
            _ok("V-P1-DETECTED", f"self-correction count={P['P1'].count}")
        else:
            _fail("V-P1-DETECTED", str(P["P1"].count))

        # P1 cost = real out_tokens of the pair (1000 + 500)
        if P["P1"].tokens == 1500:
            _ok("V-COST-REAL", f"P1 tokens={P['P1'].tokens} (1000+500)")
        else:
            _fail("V-COST-REAL", str(P["P1"].tokens))

        # P2 must be exactly 1 -> the two harness wrappers did NOT inflate it
        if P["P2"].count == 1:
            _ok("V-P2-DETECTED / V-FP-HARNESS-EXCLUDED",
                f"P2 count={P['P2'].count} (harness wrappers ignored)")
        else:
            _fail("V-P2-DETECTED / V-FP-HARNESS-EXCLUDED", str(P["P2"].count))

        if P["P3"].count == 1:
            _ok("V-P3-DETECTED", f"cross-session scan count={P['P3'].count}")
        else:
            _fail("V-P3-DETECTED", str(P["P3"].count))

        if P["P4"].count == 1:
            _ok("V-P4-DETECTED", f"plan-divergence count={P['P4'].count}")
        else:
            _fail("V-P4-DETECTED", str(P["P4"].count))

        # P5 must be exactly 1 -> the 'Is that all?' non-question did NOT count
        if P["P5"].count == 1:
            _ok("V-P5-DETECTED / V-FP-NONQUESTION-EXCLUDED",
                f"P5 count={P['P5'].count} (non-question ignored)")
        else:
            _fail("V-P5-DETECTED / V-FP-NONQUESTION-EXCLUDED", str(P["P5"].count))

    total = _passes + _fails
    print(f"CONVQUALITY_PASS={_passes}/{total}  threshold={total}/{total}")
    return 0 if _fails == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
