#!/usr/bin/env python3
"""
vault_summarize.py — Knowledge Vault Self-Optimization (MC-OVO-36)

Parses vault/knowledge_base/errors.md (append-only learning log) and emits
vault/knowledge_base/INDEX.md — a queryable summary grouped by category,
with counts, freshness, and the top-N most-recent lessons per bucket.

The Owner's goal: enable the model to "learn by habit" (internalization)
by surfacing the top recurring lesson categories at the front of the
vault, so frequent patterns become instinct instead of needing a full
scan of the log.

errors.md line format (produced by tools/session_checkpoint.py
learn-error + modules/governance-overlay/hooks/mistake-ingest.js):

    - YYYY-MM-DD [category] symptom -> root-cause -> fix

Usage:
    python tools/vault_summarize.py --project .
    python tools/vault_summarize.py --project . --top 5       # top-5 per category
    python tools/vault_summarize.py --project . --check       # exit 1 if stale

Exit codes:
    0 — INDEX.md written (or --check and up-to-date)
    1 — --check and INDEX.md is stale (older than errors.md)
    2 — errors.md missing or malformed
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ERRORS_REL = "vault/knowledge_base/errors.md"
INDEX_REL = "vault/knowledge_base/INDEX.md"
LINE_REGEX = re.compile(
    r"^- (\d{4}-\d{2}-\d{2}) \[([^\]]+)\] (.+?) -> (.+?) -> (.+?)\s*$"
)


def parse_errors(errors_path: Path) -> list[dict]:
    """Parse errors.md into a list of entry dicts."""
    if not errors_path.exists():
        print(f"ERROR: {errors_path} does not exist", file=sys.stderr)
        sys.exit(2)

    entries = []
    for lineno, line in enumerate(errors_path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.rstrip()
        if not line or not line.startswith("- "):
            continue
        m = LINE_REGEX.match(line)
        if not m:
            # Don't fail on malformed lines — log and skip
            print(f"WARN: skipping malformed line {lineno}: {line[:80]}", file=sys.stderr)
            continue
        entries.append({
            "date": m.group(1),
            "category": m.group(2),
            "symptom": m.group(3).strip(),
            "root_cause": m.group(4).strip(),
            "fix": m.group(5).strip(),
            "line": lineno,
        })
    return entries


def build_index(entries: list[dict], top_n: int) -> str:
    """Build INDEX.md markdown content."""
    by_category: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_category[e["category"]].append(e)

    total = len(entries)
    categories_sorted = sorted(
        by_category.items(), key=lambda kv: (-len(kv[1]), kv[0])
    )

    dates = [e["date"] for e in entries] or ["—"]
    first_date = min(dates)
    last_date = max(dates)

    lines = [
        "# Vault Knowledge Base — INDEX",
        "",
        f"**Auto-generated by `tools/vault_summarize.py`.** Re-run after every batch of new entries in `errors.md` to refresh counts.",
        "",
        f"- **Total lessons logged:** {total}",
        f"- **First entry:** {first_date}",
        f"- **Latest entry:** {last_date}",
        f"- **Categories:** {len(by_category)}",
        f"- **Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S')}Z",
        "",
        "## Categories (ranked by frequency — apply top-3 first as internalized habits)",
        "",
        "| Rank | Category | Count | % of total | Latest |",
        "|-----:|----------|------:|-----------:|--------|",
    ]
    for rank, (cat, items) in enumerate(categories_sorted, 1):
        pct = (len(items) / total * 100) if total else 0
        latest = max(e["date"] for e in items)
        lines.append(f"| {rank} | `{cat}` | {len(items)} | {pct:.1f}% | {latest} |")
    lines.append("")

    lines.append(f"## Top-{top_n} most recent lessons per category")
    lines.append("")
    for cat, items in categories_sorted:
        recent = sorted(items, key=lambda e: e["date"], reverse=True)[:top_n]
        lines.append(f"### `{cat}` ({len(items)} total)")
        lines.append("")
        for e in recent:
            sym = e["symptom"][:120] + ("…" if len(e["symptom"]) > 120 else "")
            fix = e["fix"][:120] + ("…" if len(e["fix"]) > 120 else "")
            lines.append(f"- **{e['date']}** · {sym}")
            lines.append(f"  - *Fix:* {fix}  *(errors.md line {e['line']})*")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("**How to consume this index:**")
    lines.append("")
    lines.append("1. At session start, scan the top-3 categories — those are your highest-probability lessons.")
    lines.append("2. For any new work matching a category name, read that category's section before writing code.")
    lines.append("3. For a specific symptom search, grep `errors.md` directly — this index is a summary, not the SSoT.")
    lines.append("4. After each `/ovo-audit` cycle that registers a new Mistake #N, rerun `vault_summarize.py` to refresh counts.")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--project", type=Path, default=Path("."), help="project root (default: cwd)")
    ap.add_argument("--top", type=int, default=5, help="top-N most-recent per category (default: 5)")
    ap.add_argument("--check", action="store_true", help="exit 1 if INDEX.md is stale vs errors.md")
    args = ap.parse_args()

    root = args.project.resolve()
    errors_path = root / ERRORS_REL
    index_path = root / INDEX_REL

    if args.check:
        if not errors_path.exists():
            print("ERROR: errors.md missing", file=sys.stderr)
            return 2
        if not index_path.exists():
            print("STALE: INDEX.md missing")
            return 1
        if index_path.stat().st_mtime < errors_path.stat().st_mtime:
            print("STALE: INDEX.md older than errors.md")
            return 1
        print("OK: INDEX.md up-to-date")
        return 0

    entries = parse_errors(errors_path)
    content = build_index(entries, args.top)
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content, encoding="utf-8")
    print(f"OK: {index_path} written — {len(entries)} entries across {len(set(e['category'] for e in entries))} categories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
